'use strict';
// ── Bronze Age Missions (age_min: 1) — 50 total ──────────────────────────────

module.exports = [

  // ─── LILLY COMBAT (8) ────────────────────────────────────────────────────

  { id:'ba_l_c01', type:'combat', source:'lilly', age_min:1, cost:60,
    offer:'"Bronze Plains, friend. War boars broke through the settlement fence and the children are inside. The guards are outnumbered. Lilly needs someone very fast and very capable. That is you, yes yes."',
    room:'bronze_plains', monster:'war_boar', monster_label:'the rampaging war boars',
    good:{ text:'Drive the boars back, repair the fence, check every child.',
           alignment:+14, item:'bronze_remedy',
           line:'"Every child accounted for. Every child unharmed. The fence is repaired. You repaired the fence without being asked. Lilly noticed. She always notices, yes yes."' },
    evil:{ text:'Kill the boars for the bronze-capped tusk trophies, then clear out.',
           alignment:-9, item:'blood_token',
           line:'"The boars are dead. The children were fine. The fence remained broken for three days after. Someone else fixed it eventually. Someone else."' },
  },

  { id:'ba_l_c02', type:'combat', source:'lilly', age_min:1, cost:70,
    offer:'"Bronze Forge, friend. A bronze golem has reactivated and is blocking access to the healing furnaces. The healers need those furnaces for medicines. The golem does not negotiate. You do."',
    room:'bronze_forge', monster:'bronze_golem', monster_label:'the reactivated forge golem',
    good:{ text:'Find a way to deactivate it without destroying it — there may be knowledge in it.',
           alignment:+13, item:'bronze_remedy',
           line:'"Deactivated intact. The healers found the activation rune and preserved it. The golem holds knowledge from the age before this one. Lilly is going to sit with it for a while."' },
    evil:{ text:'Destroy it. Healer access is more valuable than whatever it knows.',
           alignment:-10, item:'dark_talisman',
           line:'"It is destroyed. The healers have access. The knowledge it held went with it. Lilly has made peace with this. She is still a little sad."' },
  },

  { id:'ba_l_c03', type:'combat', source:'lilly', age_min:1, cost:65,
    offer:'"Tribal Village, friend. A tribal warrior who protects the young in that settlement was captured in a raid. They will be used as a demonstration. Lilly cannot allow demonstrations. Please go."',
    room:'tribal_village', monster:'tribal_warrior', monster_label:'the raiding warriors',
    good:{ text:'Rescue the captive and negotiate their release through the elders.',
           alignment:+16, item:'mission_token',
           line:'"The captive is free. The negotiation opened a dialogue between settlements that has lasted two generations. Small rescues have long shadows, yes yes."' },
    evil:{ text:'Fight through and take the captive by force — negotiations take too long.',
           alignment:-8, item:'blood_token',
           line:'"The captive is free. Six others were wounded in the extraction. The dialogue that could have opened here is closed now. Lilly notes the math of forceful solutions."' },
  },

  { id:'ba_l_c04', type:'combat', source:'lilly', age_min:1, cost:75,
    offer:'"Cursed Temple, friend. The high priests there perform rituals that poison the water supply. Not metaphorically — literally poisoned. The tribe upstream gets sick every season. Stop the ritual."',
    room:'cursed_temple', monster:'tribal_high_priest', monster_label:'the water-poisoning priests',
    good:{ text:'Interrupt the ritual, then speak with the priests about why — maybe they don\'t know.',
           alignment:+17, item:'bronze_remedy',
           line:'"The priests did not know the ritual poisoned water. They thought it purified it. An ancient mistranslation. Lilly finds this heartbreaking and fixable. Yes yes."' },
    evil:{ text:'Stop the ritual by whatever means necessary.',
           alignment:-11, item:'dark_talisman',
           line:'"The ritual stopped. Violently. The priests who survived are angry. The water is clear. The anger will find a direction. It always does."' },
  },

  { id:'ba_l_c05', type:'combat', source:'lilly', age_min:1, cost:80,
    offer:'"Guardian Gate, friend. A bronze golem is preventing a peace delegation from passing to the next region. The delegation carries a treaty. The first treaty in this age. Lilly needs the gate clear."',
    room:'guardian_gate', monster:'bronze_golem', monster_label:'the gate-blocking bronze golem',
    good:{ text:'Clear the gate and honor the delegation — walk them through personally.',
           alignment:+18, item:'mission_token',
           line:'"The treaty was delivered. The first one in this age. It held for forty years. Lilly keeps a copy. She has read it many times. Yes."' },
    evil:{ text:'Clear the gate. The delegation can manage from there.',
           alignment:-6, item:'bronze_seal',
           line:'"The gate is clear. The delegation passed. The treaty was delivered. Lilly notes you could have done more. She notes it and says nothing."' },
  },

  { id:'ba_l_c06', type:'combat', source:'lilly', age_min:1, cost:70,
    offer:'"Bronze Plains. The war boars have been trained by a rival tribe — trained, friend, organized. They are raiding the eastern settlements systematically. Someone taught them this. Stop the raids."',
    room:'bronze_plains', monster:'war_boar', monster_label:'the trained war boar assault',
    good:{ text:'Stop the raid and find the trainer — maybe the teaching can stop.',
           alignment:+12, item:'bronze_remedy',
           line:'"The raids stopped. The trainer was a child trying to protect their family. Lilly sits with that. The solution was unexpected. Yes yes."' },
    evil:{ text:'Destroy the boars and send the trainer\'s tribe a message.',
           alignment:-13, item:'dark_talisman',
           line:'"The raids stopped. The message was received. The trainer\'s family has no boars now and no protection. Lilly is not happy about this outcome."' },
  },

  { id:'ba_l_c07', type:'combat', source:'lilly', age_min:1, cost:85,
    offer:'"Ancient Ruins, friend. A bronze golem has activated near the merchant stall — a very old one. The merchant is trapped. She is the only person in this age who knows the old trade routes. Get her out."',
    room:'ancient_ruins', monster:'bronze_golem', monster_label:'the ruins-stalking golem',
    good:{ text:'Extract the merchant safely and help her document the trade routes for all.',
           alignment:+15, item:'mission_token',
           line:'"The merchant lived. She documented the routes. Three settlements found each other through those routes. Lilly calls this a network. It is beautiful, yes."' },
    evil:{ text:'Get her out and buy the exclusive rights to the trade routes.',
           alignment:-10, item:'bronze_seal',
           line:'"The merchant lived. You hold exclusive knowledge of the routes. Trade monopolies are a natural development of this age. Lilly acknowledges this and dislikes it."' },
  },

  { id:'ba_l_c08', type:'combat', source:'lilly', age_min:1, cost:60,
    offer:'"Tribal Village. An elder who teaches children is being targeted by a warrior faction that considers teaching a threat. They may be right about that. Protect the teacher, friend. Please."',
    room:'tribal_village', monster:'tribal_warrior', monster_label:'the anti-education warrior faction',
    good:{ text:'Protect the teacher and stay to make the case for teaching being valuable.',
           alignment:+16, item:'bronze_remedy',
           line:'"The teacher lives. The case was made. Two warriors sent their own children the following season. Change is slow and then suddenly very fast, yes yes."' },
    evil:{ text:'Protect the teacher and leave before you become a target too.',
           alignment:-5, item:'mission_token',
           line:'"The teacher is safe. You are gone. The faction tried again two days later. Someone else stopped them. Lilly notes: protection that leaves is incomplete."' },
  },

  // ── LILLY HUNT (5) ───────────────────────────────────────────────────────

  { id:'ba_l_h01', type:'hunt', source:'lilly', age_min:1, cost:65,
    offer:'"The Ancient Guardian, friend — the Guardian Gate. It has reactivated and it is hunting. Not stationary anymore. It is following someone. Lilly needs to know who and why. Find it."',
    room:'guardian_gate', monster:'ancient_guardian', monster_label:'the hunting Ancient Guardian',
    good:{ text:'Find who it is hunting and protect them first, then address the Guardian.',
           alignment:+17, item:'mission_token',
           line:'"It was hunting a child who wandered near the gate. The child is safe. The Guardian returned to its post. Lilly thinks it was protecting the gate, not hunting. She could be wrong."' },
    evil:{ text:'Kill the Guardian — a hunting guardian is more dangerous than a posted one.',
           alignment:-14, item:'dark_talisman',
           line:'"The Guardian falls. What it was hunting remains unknown. The gate is now unguarded. Something has already noticed."' },
  },

  { id:'ba_l_h02', type:'hunt', source:'lilly', age_min:1, cost:70,
    offer:'"Cursed Temple. The high priest there — the eldest one — is said to know a healing ritual that predates this age. The ritual would save the fever camp. Find the priest. Ask. If they refuse, Lilly understands."',
    room:'cursed_temple', monster:'tribal_high_priest', monster_label:'the eldest high priest',
    good:{ text:'Find the priest and listen fully before asking. They may need to trust you first.',
           alignment:+19, item:'bronze_remedy',
           line:'"The priest shared the ritual. Freely, once you listened to them for an hour. The fever camp recovered. Lilly transcribed the ritual carefully. It will be needed again."' },
    evil:{ text:'Find the priest and demand the ritual. There is no time for ceremony.',
           alignment:-9, item:'dark_talisman',
           line:'"The priest was found. The ritual was obtained. With difficulty. The priest will not share anything again. Lilly notes: one time saves a camp, one relationship saves ages."' },
  },

  { id:'ba_l_h03', type:'hunt', source:'lilly', age_min:1, cost:75,
    offer:'"Bronze Forge. One of the bronze golems there carries the original crafting knowledge of the first Bronze Age builders. If it is destroyed — as others have been — that knowledge is lost. Find it first."',
    room:'bronze_forge', monster:'bronze_golem', monster_label:'the knowledge-carrying golem',
    good:{ text:'Identify it by its markings and find a way to preserve what it carries.',
           alignment:+14, item:'mission_token',
           line:'"Identified and preserved. The crafting knowledge was transferred to clay tablets before the golem was deactivated. Three techniques from the before-time. Lilly is delighted. Yes yes."' },
    evil:{ text:'Identify it and claim its knowledge for yourself — give it only to trusted allies.',
           alignment:-10, item:'bronze_seal',
           line:'"The knowledge is yours. Three people know it. The world needed twelve. Lilly notes the gap between what you had and what you shared."' },
  },

  { id:'ba_l_h04', type:'hunt', source:'lilly', age_min:1, cost:60,
    offer:'"Bronze Plains. A war boar — tamed, branded, a settlement\'s livestock — was captured in a raid and is somewhere on the plains. The settlement\'s winter food depends on it. Find and return it."',
    room:'bronze_plains', monster:'war_boar', monster_label:'the captured settlement boar',
    good:{ text:'Find it, return it, and report the raiding party to prevent future thefts.',
           alignment:+12, item:'bronze_remedy',
           line:'"Boar home. Raid reported. The raiding party was warned by the elders — genuinely warned. They stopped. Lilly notes that warnings sometimes work. Yes yes."' },
    evil:{ text:'Find it and sell it back to the settlement at a profit.',
           alignment:-7, item:'bronze_seal',
           line:'"The boar was returned — for a price. The settlement paid. They remember the price. They remember who set it. Lilly notes: small profits, long memories."' },
  },

  { id:'ba_l_h05', type:'hunt', source:'lilly', age_min:1, cost:80,
    offer:'"Tribal Village. A tribal warrior who has been defecting — leaving the dark war-faction and seeking another way. The faction has sent hunters after them. Find the defector first, friend. Please."',
    room:'tribal_village', monster:'tribal_warrior', monster_label:'the faction hunters',
    good:{ text:'Find the defector, protect them, and help them find a new community.',
           alignment:+18, item:'mission_token',
           line:'"The defector is safe. They joined a light settlement. They became a teacher. Three generations later their descendant builds bridges. Lilly knows all of this. She has been watching."' },
    evil:{ text:'Find the defector. Negotiate with the faction hunters — maybe there is a deal.',
           alignment:-12, item:'dark_talisman',
           line:'"A deal was made. The defector was handed back. They survived the faction\'s response. Barely. The deal preserved your standing. Lilly notes what the deal cost."' },
  },

  // ── LILLY ESCORT (5) ─────────────────────────────────────────────────────

  { id:'ba_l_e01', type:'escort', source:'lilly', age_min:1, cost:55,
    offer:'"A peace delegate — the first person in this age willing to walk into a rival settlement and talk. She needs an escort through Bronze Plains. This matters more than it sounds, friend. The first dialogue."',
    room:'bronze_plains', monster:'war_boar', monster_label:'the plains predators',
    good:{ text:'Escort her and speak on behalf of dialogue when you arrive.',
           alignment:+17, item:'mission_token',
           line:'"She arrived. She spoke. She was heard. The first dialogue of the Bronze Age happened because someone walked with her. That was you. Yes yes."',
           chain_next:'ba_l_e01_chain' },
    evil:{ text:'Escort her there safely and leave her to manage the dialogue.',
           alignment:-4, item:'bronze_seal',
           line:'"She arrived safely. The dialogue was harder without support. It almost failed. It did not fail. Lilly notes: almost matters."' },
  },

  { id:'ba_l_e01_chain', type:'escort', source:'lilly', age_min:1, cost:0, is_chain_followup:true,
    offer:'"Friend — she did it! The delegate opened the dialogue. Now she needs to return safely with the response. The rival settlement is watching. Escort her back. Make the return matter."',
    room:'bronze_plains', monster:'tribal_warrior', monster_label:'the faction watching the return',
    good:{ text:'Escort her back safely and announce the dialogue to every settlement you pass.',
           alignment:+15, item:'bronze_remedy',
           line:'"The response was delivered publicly. Four settlements heard it. The dialogue network began that day. Lilly has named it. She named it after the delegate. Yes."' },
    evil:{ text:'Escort her back quietly. Let the dialogue find its own pace.',
           alignment:-3, item:'mission_token',
           line:'"She returned safely. The response was delivered quietly. The network that could have formed that day formed six seasons later instead. Quietly was slower."' },
  },

  { id:'ba_l_e02', type:'escort', source:'lilly', age_min:1, cost:65,
    offer:'"Bronze Forge, friend. A craftsman who knows the secret of bronze tempering — the technique that makes blades that don\'t break — is being moved. War-faction warriors want that knowledge controlled. Escort him."',
    room:'bronze_forge', monster:'bronze_golem', monster_label:'the forge guardians',
    good:{ text:'Escort the craftsman and ensure the tempering secret becomes public knowledge.',
           alignment:+15, item:'bronze_remedy',
           line:'"The secret was published openly. Every settlement in the Bronze Age can now make unbreakable blades. The war-faction lost their advantage. Lilly considers this excellent."' },
    evil:{ text:'Escort him to a specific buyer who offered a significant payment.',
           alignment:-12, item:'bronze_seal',
           line:'"The craftsman and his secret went to the highest bidder. The advantage is now someone else\'s monopoly. The pattern changes. The problem does not."' },
  },

  { id:'ba_l_e03', type:'escort', source:'lilly', age_min:1, cost:70,
    offer:'"Cursed Temple. A former priest who rejected the temple\'s practices carries records of what was done there. She wants to testify to the elders. She needs to get there alive. Please, friend."',
    room:'cursed_temple', monster:'tribal_high_priest', monster_label:'the silencing priests',
    good:{ text:'Escort her to the elders and stand as a witness when she testifies.',
           alignment:+19, item:'mission_token',
           line:'"She testified. The elders heard. The temple practices were investigated. Three were stopped. Lilly stood outside the council and waited. She did not sleep. Worth it."' },
    evil:{ text:'Escort her to the elders and leave before the testimony becomes political.',
           alignment:-6, item:'bronze_seal',
           line:'"She testified. Alone. Without corroboration the elders were skeptical. One practice was stopped. Three continued. Lilly notes: witnesses matter."' },
  },

  { id:'ba_l_e04', type:'escort', source:'lilly', age_min:1, cost:60,
    offer:'"Ancient Ruins, friend. Three children from different settlements — brought together for a trading fair, now separated from their families. They found each other. They need someone to find their families. Please."',
    room:'ancient_ruins', monster:'bronze_golem', monster_label:'the ruins hazards',
    good:{ text:'Find all three families and bring the children home yourself.',
           alignment:+14, item:'bronze_remedy',
           line:'"All three home. To three different settlements. The children told the story of the friend who found them. Lilly has heard it told three different ways. All are true."' },
    evil:{ text:'Find the nearest family and let the ruins merchants handle the other two.',
           alignment:-9, item:'hunters_mark',
           line:'"One child home quickly. Two children home eventually, through merchants who charged for the service. The two families paid. Lilly notes who did not pay."' },
  },

  { id:'ba_l_e05', type:'escort', source:'lilly', age_min:1, cost:75,
    offer:'"Guardian Gate, friend. An elderly scholar wants to reach the knowledge vault beyond the gate before he dies. He is the last person who knows where the vault is. He needs to reach it. Walk with him."',
    room:'guardian_gate', monster:'ancient_guardian', monster_label:'the gate guardian',
    good:{ text:'Walk with him slowly. Listen to everything he says on the way.',
           alignment:+16, item:'mission_token',
           line:'"He reached the vault. He shared everything on the way there. You listened to all of it. Lilly has asked you to write it down. You have time. She will wait."' },
    evil:{ text:'Get him there efficiently. The location is what matters.',
           alignment:-5, item:'bronze_seal',
           line:'"The vault is located. The scholar arrived. He is too tired to speak. The things he would have said on the way are gone with his energy. Lilly does not say this to you. She is thinking it."' },
  },

  // ── LILLY COLLECTION (4) ─────────────────────────────────────────────────

  { id:'ba_l_k01', type:'collection', source:'lilly', age_min:1, cost:60, kill_count:3,
    offer:'"Bronze Plains. Three war boars for the settlement\'s winter — but taken from the wild population, friend, not the tribal herds. The tribal herds must not be touched. The wild population can spare three."',
    room:'bronze_plains', monster:'war_boar', monster_label:'the wild war boar population',
    good:{ text:'Take three from the wild. Mark the tribal herd boundaries before leaving.',
           alignment:+10, item:'mission_token',
           line:'"Three from the wild. Boundaries marked. The tribal herds were not touched and the markers have held for two seasons. Lilly checked. Yes yes."' },
    evil:{ text:'Three is three. Take the easiest three — tribal or wild.',
           alignment:-14, item:'dark_talisman',
           line:'"Three taken. Two from the tribal herd. The settlement does not know. The tribe knows. The tribe will find out who. They always find out."' },
  },

  { id:'ba_l_k02', type:'collection', source:'lilly', age_min:1, cost:65, kill_count:4,
    offer:'"Bronze Forge. Four bronze shard samples from deactivated golems — for the healers to study. Bronze has medicinal properties when properly processed. The healers need samples to learn. Four, please."',
    room:'bronze_forge', monster:'bronze_golem', monster_label:'the forge golems',
    good:{ text:'Collect the shards from golems already deactivated, not fresh ones.',
           alignment:+11, item:'bronze_remedy',
           line:'"Four shards, all from already-deactivated golems. The healers note the ethical sourcing. The medicine they develop works equally well. Lilly notes that method matters."' },
    evil:{ text:'Four shards from the most convenient source.',
           alignment:-8, item:'dark_talisman',
           line:'"Four shards collected. From four golems that were not yet deactivated. The healers do not ask. Lilly does not ask either. She already knows."' },
  },

  { id:'ba_l_k03', type:'collection', source:'lilly', age_min:1, cost:55, kill_count:2,
    offer:'"Tribal Village. Two tribal warrior weapons — for the elders to study. If they understand how the weapons are made, they can find defensive counters. Knowledge over armor, friend. Two weapons."',
    room:'tribal_village', monster:'tribal_warrior', monster_label:'the village warriors',
    good:{ text:'Obtain the weapons through trade or combat, then share the defensive analysis.',
           alignment:+12, item:'bronze_remedy',
           line:'"Two weapons and a defensive manual written from the analysis. The manual was copied twelve times and distributed. Lilly wrote the third copy herself."' },
    evil:{ text:'Take the weapons and keep the defensive analysis private.',
           alignment:-10, item:'dark_talisman',
           line:'"Two weapons. The analysis stays with you. The settlements remain vulnerable. Your settlement is less so. Lilly notes the radius of your care."' },
  },

  { id:'ba_l_k04', type:'collection', source:'lilly', age_min:1, cost:70, kill_count:3,
    offer:'"Guardian Gate. Three ancient relics are scattered near the gate — fragments of something older than this age. The elders want to assemble them. They believe they form a map. Three relics, friend."',
    room:'guardian_gate', monster:'ancient_guardian', monster_label:'the gate and its guardians',
    good:{ text:'Collect all three and bring them to the elders for assembly.',
           alignment:+14, item:'mission_token',
           line:'"Assembled. The map shows a location that predates the Bronze Age. Lilly has been sitting very quietly since it was unrolled. She recognizes the location."' },
    evil:{ text:'Collect all three and keep one — the most interesting one.',
           alignment:-11, item:'bronze_seal',
           line:'"Two relics delivered. One kept. The map assembled with a gap. It shows something but not clearly enough. Lilly stares at it for a long time. She is looking at the missing piece."' },
  },

  // ── LILLY SURVIVAL (3) ───────────────────────────────────────────────────

  { id:'ba_l_s01', type:'survival', source:'lilly', age_min:1, cost:70, kill_count:4,
    offer:'"Bronze Plains. The settlement is under assault — four waves of tribal warriors and war boars, coordinated. Someone planned this. Lilly needs the settlement to survive long enough to find out who."',
    room:'bronze_plains', monster:'tribal_warrior', monster_label:'the coordinated assault',
    good:{ text:'Defend the settlement and keep the elders safe so they can negotiate.',
           alignment:+15, item:'bronze_remedy',
           line:'"Settlement survived. The elders negotiated after the assault. It was the rival tribe\'s water rights — a solvable problem. Lilly notes: most assaults have a solvable problem behind them."' },
    evil:{ text:'Defend aggressively. Make the cost of attack so high they never try again.',
           alignment:-11, item:'dark_talisman',
           line:'"Settlement survived. The cost of attack was made extremely high. The rival tribe has not tried again. They have found a different approach. Lilly is watching for it."' },
  },

  { id:'ba_l_s02', type:'survival', source:'lilly', age_min:1, cost:80, kill_count:5,
    offer:'"Bronze Forge. The furnaces are under attack — if the golems reach the central furnace, the entire forge collapses. The healers are inside. Five golems approaching. Lilly needs the furnace held."',
    room:'bronze_forge', monster:'bronze_golem', monster_label:'the forge assault golems',
    good:{ text:'Hold the furnace and get every healer out through the back passage.',
           alignment:+16, item:'mission_token',
           line:'"Every healer out. Furnace held. Five golems stopped. Lilly counted the healers herself after. She counts things when she is worried. She counted three times."' },
    evil:{ text:'Hold the furnace. The healers can manage their own exit.',
           alignment:-8, item:'bronze_seal',
           line:'"Furnace held. Two healers did not find the back passage in time. They survived — inside a furnace room with no exit for six hours. Lilly notes: managing own exits is harder under pressure."' },
  },

  { id:'ba_l_s03', type:'survival', source:'lilly', age_min:1, cost:65, kill_count:3,
    offer:'"Cursed Temple. The rituals there are escalating — and now spilling out. Three priests are performing a ritual that is drawing predators from every direction. Survive it. Stop the ritual. Both, friend."',
    room:'cursed_temple', monster:'tribal_high_priest', monster_label:'the ritual-escalating priests',
    good:{ text:'Interrupt the ritual and help the priests understand what they were actually doing.',
           alignment:+14, item:'bronze_remedy',
           line:'"Ritual interrupted. The priests did not know what the ritual attracted. They were as surprised as the settlement. Lilly is beginning to suspect the temple\'s founding texts have errors."' },
    evil:{ text:'Survive the encounter and stop the ritual by force.',
           alignment:-10, item:'dark_talisman',
           line:'"Survived. Ritual stopped. By force. The priests will restart the ritual after you leave. Lilly notes: stopping without explaining only pauses."' },
  },

  // ── LILLY COOPERATIVE (2) ─────────────────────────────────────────────────

  { id:'ba_l_co01', type:'cooperative', source:'lilly', age_min:1, cost:100, kill_count:1,
    offer:'"The Ancient Guardian, friend — the Guardian Gate. It cannot be faced alone. Every settlement needs this gate clear. Lilly is asking for a collective effort. Together, yes yes. For all of them."',
    room:'guardian_gate', monster:'ancient_guardian', monster_label:'the Ancient Guardian',
    good:{ text:'Fight together and share the gate\'s knowledge cache equally.',
           alignment:+22, item:'mission_token',
           line:'"The Guardian fell. The gate opened. The knowledge cache was shared with every settlement. The Bronze Age advanced three seasons ahead of Lilly\'s estimate. She is delighted."' },
    evil:{ text:'Fight together but reach the knowledge cache first and share selectively.',
           alignment:-14, item:'dark_talisman',
           line:'"The Guardian fell. The gate opened. The knowledge was distributed unevenly. The uneven distribution creates the power dynamics that cause the next war. Lilly knows this pattern."' },
  },

  { id:'ba_l_co02', type:'cooperative', source:'lilly', age_min:1, cost:90, kill_count:2,
    offer:'"Tribal Village siege — two factions of warriors simultaneously. Lilly needs multiple defenders. This is not a one-person situation. She is asking everyone she trusts. Please come."',
    room:'tribal_village', monster:'tribal_warrior', monster_label:'the dual-faction siege',
    good:{ text:'Coordinate the defense and keep communication open between all defenders.',
           alignment:+17, item:'bronze_remedy',
           line:'"Village defended. All defenders coordinated. The two factions met each other in the defense line and recognized each other. They had names. The siege ended without final violence. Lilly counts this as a miracle. Yes yes."' },
    evil:{ text:'Defend your sector and let others manage theirs.',
           alignment:-9, item:'dark_talisman',
           line:'"Village defended. Sectors managed separately. One sector held better than another. The difference in outcome became a grievance. Lilly had hoped for better."' },
  },

  // ── LILLY SABOTAGE (1) ───────────────────────────────────────────────────

  { id:'ba_l_sa01', type:'sabotage', source:'lilly', age_min:1, cost:85,
    offer:'"There is a war preparation happening at the Tribal Village — weapons stockpiled, a signal fire planned. If the signal fires, the attack begins. Lilly is asking you to prevent an entire war. Please."',
    room:'tribal_village', monster:'tribal_warrior', monster_label:'the war preparation guard',
    good:{ text:'Prevent the signal and request a meeting between the faction leaders.',
           alignment:+20, item:'mission_token',
           line:'"The signal never fired. The meeting happened. The war that would have begun that night did not begin. Lilly does not know how many people that saved. She prefers it that way."' },
    evil:{ text:'Prevent the signal. A war delayed is still delayed — that is enough for now.',
           alignment:-7, item:'bronze_seal',
           line:'"The signal did not fire. The preparation resumed the following week. The war delayed by ten days. Lilly notes: ten days is ten days. Also ten days is not a resolution."' },
  },

  // ── LILLY INVESTIGATION (1) ───────────────────────────────────────────────

  { id:'ba_l_i01', type:'investigation', source:'lilly', age_min:1, cost:65,
    offer:'"The Ancient Ruins hold something Lilly has been looking for — clay tablets with the earliest written records of this age. They may be buried under the rubble. The merchant has not found them. You might."',
    room:'ancient_ruins', monster:'bronze_golem', monster_label:'the ruins-guard golem',
    good:{ text:'Search carefully, find the tablets, and help translate them for everyone.',
           alignment:+16, item:'mission_token',
           line:'"Found. Translated. Distributed. The earliest written laws, the first trade agreements, and — Lilly pauses here — a record of a flood that happened before this age. She is reading it a fourth time."',
           chain_next:'ia_l_i_chain2' },
    evil:{ text:'Find the tablets and sell them to the highest bidder — knowledge is currency.',
           alignment:-13, item:'bronze_seal',
           line:'"Found. Sold. The highest bidder used the trade agreements to restructure every market in this age. Lilly notes: the first laws, held by one entity. She notes this very carefully."' },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ZOMB MISSIONS (25) — Bronze Age
  // ─────────────────────────────────────────────────────────────────────────

  // Chain continuation: ba_z_k_chain1 (from sa_z_k02 bone harvest)
  { id:'ba_z_k_chain1', type:'collection', source:'zomb', age_min:1, cost:0, is_chain_followup:true, kill_count:4,
    offer:'"The structure requires more. Bronze Age materials now. Four ancient relics from the Guardian Gate. Zomb\'s project enters the next phase. The project is architectural. You have seen the bones. Now bring the bronze."',
    room:'guardian_gate', monster:'ancient_guardian', monster_label:'the gate guardians',
    good:{ text:'Gather the relics and ask Zomb directly what the structure is for.',
           alignment:+5, item:'spirit_ash',
           line:'"You asked. Zomb pauses. Zomb answers: the structure is a record of every cycle. Every flood. Every world. Carved in bone and bronze. Zomb has been building it since before you were born."',
           chain_next:'ia_z_k_chain2' },
    evil:{ text:'Gather everything. The structure must be complete.',
           alignment:-15, item:'dark_talisman',
           line:'"Relics delivered. The structure grows. You have not asked what it is. Zomb notes this. Either you trust Zomb or you do not care. Both are interesting."',
           chain_next:'ia_z_k_chain2' },
  },

  // ── ZOMB COMBAT (5) ──────────────────────────────────────────────────────

  { id:'ba_z_c01', type:'combat', source:'zomb', age_min:1, cost:65,
    offer:'"Bronze Plains. A settlement leader has achieved stability. Stability breeds complacency. Complacency produces weakness. The stable are not ready for what comes. Destabilize. Begin at the source."',
    room:'bronze_plains', monster:'tribal_warrior', monster_label:'the stability guard',
    good:{ text:'Challenge the leader to prepare rather than destabilize their work.',
           alignment:+10, item:'bronze_remedy',
           line:'"The leader was challenged to prepare. They responded by building defenses. The settlement is stable and prepared. Zomb recalculates: stable and prepared is not the variable Zomb predicted."' },
    evil:{ text:'Destabilize the settlement leadership. Chaos produces adaptation.',
           alignment:-16, item:'dark_talisman',
           line:'"Destabilized. The settlement fractures over succession. Three factions emerge. The strongest wins. The winning faction is harder than the original. Zomb notes: chaos sometimes produces exactly what Zomb calculates."' },
  },

  { id:'ba_z_c02', type:'combat', source:'zomb', age_min:1, cost:70,
    offer:'"Bronze Forge. The forge master holds the knowledge of large-scale bronze production. If production scales, armies equip. Equipped armies fight. Conflict accelerates. Remove the block on the forge master\'s production."',
    room:'bronze_forge', monster:'bronze_golem', monster_label:'the production-limiting golems',
    good:{ text:'Clear the golems but recommend the production be used for tools, not weapons.',
           alignment:+9, item:'mission_token',
           line:'"Golems cleared. The forge master heard the recommendation. Production scaled toward tools. The Bronze Age advanced economically before militarily. Zomb recalculates. This sequence is... acceptable."' },
    evil:{ text:'Clear the golems and report to the war faction that production is unblocked.',
           alignment:-15, item:'dark_talisman',
           line:'"Golems cleared. War faction notified. Weapons production began this season. Armies equipped within three seasons. The next war begins as Zomb calculated."' },
  },

  { id:'ba_z_c03', type:'combat', source:'zomb', age_min:1, cost:75,
    offer:'"Cursed Temple. The rituals performed there sustain an order that prevents certain conflicts. Zomb has observed this order for one hundred and twelve years. The order is too effective. Disrupt the ritual infrastructure."',
    room:'cursed_temple', monster:'tribal_high_priest', monster_label:'the order-sustaining priests',
    good:{ text:'Protect the ritual infrastructure. A hundred-year peace is not an obstacle.',
           alignment:+17, item:'bronze_remedy',
           line:'"The rituals continue. The order holds. Zomb\'s disruption timeline is pushed by an unspecified amount. Zomb recalculates. One hundred and thirteen years of peace. Zomb is updating its assessment of peace."' },
    evil:{ text:'Disrupt the infrastructure. Let the order dissolve naturally.',
           alignment:-19, item:'blood_token',
           line:'"The infrastructure is disrupted. The order begins to dissolve. The conflicts it prevented are stirring. Zomb\'s timeline resumes. Zomb watches with something it declines to name."' },
  },

  { id:'ba_z_c04', type:'combat', source:'zomb', age_min:1, cost:80,
    offer:'"Guardian Gate. An entity approaches who will, if they reach the knowledge vault beyond, advance this age by thirty years. Thirty years of advancement without conflict produces soft entities. Stop the approach."',
    room:'guardian_gate', monster:'ancient_guardian', monster_label:'the gate and its keeper',
    good:{ text:'Let the entity pass. Advancement without conflict may produce different entities — not soft ones.',
           alignment:+13, item:'mission_token',
           line:'"The entity passed. The advancement occurred. The entities it produced are different from Zomb\'s prediction. Not soft. Different. Zomb updates the model. The model was wrong. Zomb notes this."' },
    evil:{ text:'Stop the approach. Advancement earned through conflict produces harder results.',
           alignment:-14, item:'dark_talisman',
           line:'"The approach is stopped. The advancement is delayed. Conflict fills the thirty years instead. The entities that emerge are harder. Whether harder is better — Zomb is still calculating."' },
  },

  { id:'ba_z_c05', type:'combat', source:'zomb', age_min:1, cost:70,
    offer:'"Ancient Ruins. A group is excavating the ruins for history. History that is preserved is history that teaches. Lessons that are learned slow the cycle. Remove the excavation guards. Let the ruins remain unexamined."',
    room:'ancient_ruins', monster:'bronze_golem', monster_label:'the excavation guardians',
    good:{ text:'Protect the excavation. Lessons learned from history change outcomes.',
           alignment:+14, item:'mission_token',
           line:'"The excavation continues. History is preserved. Lessons are being compiled. Zomb\'s cycle projection extends by an estimated forty years. Zomb notes the extension with something like irritation and something like respect."' },
    evil:{ text:'Remove the guards. Let the ruins return to ruin.',
           alignment:-13, item:'blood_token',
           line:'"Guards removed. Excavation abandoned. The history of that site is lost to this age. The same mistakes will recur on schedule. Zomb\'s projections hold."' },
  },

  // ── ZOMB HUNT (5) ────────────────────────────────────────────────────────

  { id:'ba_z_h01', type:'hunt', source:'zomb', age_min:1, cost:65,
    offer:'"Bronze Plains. A war boar — Zomb has tracked this specific animal for seven seasons. It has survived every conflict on those plains. Zomb wants to understand the mechanism of its survival. Find it. Study it. Report."',
    room:'bronze_plains', monster:'war_boar', monster_label:'the seven-season war boar',
    good:{ text:'Study it alive. Document its survival behaviors in detail.',
           alignment:+7, item:'bronze_remedy',
           line:'"Documented alive. Zomb reviews the data. The boar avoids every conflict vector by approximately three seconds. This is not luck. It is a learned behavior. Zomb is deeply interested in learned survival."' },
    evil:{ text:'Kill it and examine the physical characteristics that enabled its survival.',
           alignment:-10, item:'hunters_mark',
           line:'"Examined post-mortem. Physical characteristics are within normal range. The survival mechanism was behavioral, not physical. The dead entity cannot demonstrate it. Zomb notes the epistemological limitation of this approach."' },
  },

  { id:'ba_z_h02', type:'hunt', source:'zomb', age_min:1, cost:70,
    offer:'"Tribal Village. A warrior who has won every combat they have entered — seventeen consecutive. Zomb has never observed this consistency. Find them. Fight them if necessary. Understand what they are."',
    room:'tribal_village', monster:'tribal_warrior', monster_label:'the seventeen-win warrior',
    good:{ text:'Speak with them before fighting. Listen to how they think.',
           alignment:+8, item:'mission_token',
           line:'"Spoke with them first. The warrior trains twice as long as anyone else and sleeps less. Discipline, not talent. Zomb updates the talent variable in its model. Discipline is more interesting."' },
    evil:{ text:'Find them and test them in combat directly.',
           alignment:-9, item:'dark_talisman',
           line:'"Found and tested. They fought well. The result was close. Zomb observes the engagement data and notes: eighteen consecutive is theoretically achievable. You interrupted seventeen."' },
  },

  { id:'ba_z_h03', type:'hunt', source:'zomb', age_min:1, cost:75,
    offer:'"Bronze Forge. A golem — old enough to predate the Bronze Age — moves through the forge at irregular intervals. It should not exist. It should not be conscious. Zomb needs to know what it is carrying. Find it."',
    room:'bronze_forge', monster:'bronze_golem', monster_label:'the pre-Bronze-Age golem',
    good:{ text:'Find it gently. What it carries might be from the world before the flood.',
           alignment:+12, item:'spirit_ash',
           line:'"Found. What it carries is from the world before. Instructions for a device. Zomb reads the instructions. Zomb sits very still for a long time. Then Zomb starts writing."' },
    evil:{ text:'Find it and take everything it carries. Priority over method.',
           alignment:-13, item:'dark_talisman',
           line:'"Found. Carried contents extracted by force. The golem was damaged. The instructions are partially intact. Partial instructions for a partial device. Zomb is frustrated. Zomb does not say this."' },
  },

  { id:'ba_z_h04', type:'hunt', source:'zomb', age_min:1, cost:60,
    offer:'"Cursed Temple. A priest who has left the temple system carries the original founding text — unmodified. The current temple leadership has edited the text over generations. The original is a variable. Find it."',
    room:'cursed_temple', monster:'tribal_high_priest', monster_label:'the text-hunters',
    good:{ text:'Find the original text and ensure it is preserved for all to read.',
           alignment:+14, item:'mission_token',
           line:'"Original text recovered and published. The modifications span four hundred years. The comparison causes the first theological crisis of the Bronze Age. Zomb observes the crisis with interest."' },
    evil:{ text:'Find the original text and bring it to Zomb directly.',
           alignment:-12, item:'dark_talisman',
           line:'"Original text delivered to Zomb. Zomb reads it carefully. The modifications tell Zomb more about power than the original does. Both are useful. Zomb keeps both."' },
  },

  { id:'ba_z_h05', type:'hunt', source:'zomb', age_min:1, cost:80,
    offer:'"Guardian Gate. An Ancient Guardian — not the standard model. Different markings, different movement patterns. Zomb has studied the standard model for decades. This deviation requires investigation. Find it."',
    room:'guardian_gate', monster:'ancient_guardian', monster_label:'the deviant Ancient Guardian',
    good:{ text:'Study it and report the differences without engaging it aggressively.',
           alignment:+9, item:'spirit_ash',
           line:'"Differences documented. The deviant Guardian is older than the gate itself. It predates the Bronze Age entirely. Zomb spends six days reviewing the implications. Zomb\'s model of the gate\'s origin is wrong. Wrong."' },
    evil:{ text:'Kill it. Deviants in the model are variables that complicate calculation.',
           alignment:-14, item:'blood_token',
           line:'"Deviant Guardian ended. The complicating variable is removed. Zomb\'s model is simpler. Zomb notes: simplicity gained at the cost of the oldest entity in this zone. The trade-off has a weight."' },
  },

  // ── ZOMB ESCORT (3) ──────────────────────────────────────────────────────

  { id:'ba_z_e01', type:'escort', source:'zomb', age_min:1, cost:70,
    offer:'"Tribal Village. An entity Zomb has placed there — a patient, long-term asset — must be extracted before the village discovers their function. Escort them out through Bronze Plains. Ask nothing about the function."',
    room:'tribal_village', monster:'tribal_warrior', monster_label:'the discovering village warriors',
    good:{ text:'Escort them and ask what they were doing there anyway.',
           alignment:+8, item:'bronze_remedy',
           line:'"They were cataloguing the village\'s food supply to predict famine cycles. The information helps. It was never intended to help. Zomb notes: sometimes beneficial outcomes emerge from neutral intentions."' },
    evil:{ text:'Escort them without question. Zomb does not need your curiosity.',
           alignment:-11, item:'blood_token',
           line:'"Extracted. Function undisclosed. The asset is repositioned. Zomb\'s network is intact. You are useful in exactly the way Zomb requires. Zomb notes this as high praise."' },
  },

  { id:'ba_z_e02', type:'escort', source:'zomb', age_min:1, cost:65,
    offer:'"Bronze Forge. A golem technician who has decoded the golem activation sequence must reach the Guardian Gate before the temple faction intercepts. If the temple gets the sequence, they control the golems. Escort."',
    room:'bronze_forge', monster:'bronze_golem', monster_label:'the forge pursuit',
    good:{ text:'Escort the technician and ensure the sequence becomes public knowledge.',
           alignment:+13, item:'mission_token',
           line:'"Technician and sequence at the gate. Sequence published. No single faction controls the golems. Zomb notes: distributed knowledge is more stable. Also harder to manipulate. Tradeoff acknowledged."' },
    evil:{ text:'Escort the technician to Zomb\'s contact at the gate.',
           alignment:-13, item:'dark_talisman',
           line:'"Technician at Zomb\'s contact. Sequence delivered to a single point. Zomb\'s network now controls the golem activation. This was the calculation. Calculation confirmed."' },
  },

  { id:'ba_z_e03', type:'escort', source:'zomb', age_min:1, cost:75,
    offer:'"Ancient Ruins. An old entity — pre-Bronze — is being moved through the ruins by individuals who do not understand what they have. Intercept. Escort the old entity to Zomb\'s archive. This is priority."',
    room:'ancient_ruins', monster:'bronze_golem', monster_label:'the ruins pursuers',
    good:{ text:'Escort the old entity somewhere safe and let them choose their destination.',
           alignment:+11, item:'spirit_ash',
           line:'"The old entity chose a light settlement. They spent thirty years there teaching. What they taught advanced the settlement by a generation. Zomb\'s archive is poorer for the choice. The world is richer."' },
    evil:{ text:'Escort the old entity to Zomb\'s archive. Priority over preference.',
           alignment:-14, item:'blood_token',
           line:'"Old entity archived. Zomb studies them intensively. The knowledge in that entity is extraordinary. The entity appears to be choosing, within the archive, to cooperate. Zomb finds this unexpected."' },
  },

  // ── ZOMB COLLECTION (4) ──────────────────────────────────────────────────

  { id:'ba_z_k02', type:'collection', source:'zomb', age_min:1, cost:65, kill_count:4,
    offer:'"Bronze Plains. Four war boar tusks — the bronze-capped ones, specifically. Zomb requires them for a structural purpose. The structure is architectural. The architecture is archival. Four."',
    room:'bronze_plains', monster:'war_boar', monster_label:'the bronze-tusked war boars',
    good:{ text:'Bring the tusks and ask what the archive documents.',
           alignment:+5, item:'hunters_mark',
           line:'"Four tusks. You asked. Zomb answers: everything. The archive documents every world that has ended. Every choice that ended them. Zomb is the only continuous record. Zomb has been the archive since the third world."' },
    evil:{ text:'Four tusks. No questions.',
           alignment:-9, item:'blood_token',
           line:'"Four tusks, no questions. The most efficient interaction Zomb has recorded in this age. Zomb notes efficiency as a value. Not the only value. But a value."' },
  },

  { id:'ba_z_k03', type:'collection', source:'zomb', age_min:1, cost:70, kill_count:3,
    offer:'"Cursed Temple. Three ritual implements — the ones the priests use to mark the transition between ritual states. Zomb studies transitions. These implements carry residue of every ritual since the temple\'s founding. Three."',
    room:'cursed_temple', monster:'tribal_high_priest', monster_label:'the temple ritualists',
    good:{ text:'Bring three but leave one — the priests need something for continuation.',
           alignment:+8, item:'spirit_ash',
           line:'"Three delivered. One left. The priests continue functioning. Zomb notes: partial collection is sometimes preferable to total. The remaining implement informs the three taken."' },
    evil:{ text:'Take all three. Ritual continuity is not Zomb\'s concern.',
           alignment:-12, item:'dark_talisman',
           line:'"All three taken. The temple rituals are disrupted for two seasons while replacements are crafted. Disruption of two seasons. Zomb notes the lag."' },
  },

  { id:'ba_z_k04', type:'collection', source:'zomb', age_min:1, cost:80, kill_count:2,
    offer:'"Guardian Gate. Two bronze shards from the Ancient Guardian\'s armour. Specifically: the shoulder plates. They were forged in a process Zomb cannot replicate and has spent decades trying to understand. Two shards."',
    room:'guardian_gate', monster:'ancient_guardian', monster_label:'the Ancient Guardian',
    good:{ text:'Obtain two shards without destroying the Guardian — pry them carefully.',
           alignment:+7, item:'spirit_ash',
           line:'"Two shards. Guardian intact. Zomb studies the alloy for six months. The forging process is older than the Guardian Gate itself. Older than the Bronze Age. Zomb revises the dating of this age\'s beginning."' },
    evil:{ text:'Take the shards by the most direct method.',
           alignment:-13, item:'dark_talisman',
           line:'"Two shards acquired. The Guardian took significant damage. The alloy reveals under study: the same process as the bones in Zomb\'s archive. The worlds share a maker. Zomb sits with this."' },
  },

  { id:'ba_z_k05', type:'collection', source:'zomb', age_min:1, cost:60, kill_count:5,
    offer:'"Bronze Forge. Five bronze shard samples — from five different golem generations. Zomb maps the degradation of bronze quality over time. The degradation has a pattern. Five samples, different ages if possible."',
    room:'bronze_forge', monster:'bronze_golem', monster_label:'the forge golems',
    good:{ text:'Select carefully — five from genuinely different construction periods.',
           alignment:+6, item:'hunters_mark',
           line:'"Five samples, distinct periods. Zomb maps the degradation. The pattern shows: bronze quality degrades as the age advances, then recovers sharply at age transition. The transition is doing something to the materials. Zomb recalculates the nature of age transitions."' },
    evil:{ text:'Five shards, fastest method.',
           alignment:-8, item:'blood_token',
           line:'"Five shards. Three from the same period. Zomb notes the limited variance. Adjusts the study. The degradation pattern is partially revealed. Partial data. Zomb dislikes partial data."' },
  },

  // ── ZOMB SURVIVAL (3) ────────────────────────────────────────────────────

  { id:'ba_z_s01', type:'survival', source:'zomb', age_min:1, cost:75, kill_count:5,
    offer:'"Bronze Plains — simultaneous war boar and tribal warrior assault on the trade route. Zomb needs the trade route intact. Not for commerce. For information flow. Information flow is Zomb\'s circulatory system. Defend it."',
    room:'bronze_plains', monster:'tribal_warrior', monster_label:'the trade route assault',
    good:{ text:'Defend the route and help the traders understand what they are moving beyond goods.',
           alignment:+11, item:'mission_token',
           line:'"Route defended. The traders were told: information travels with goods. They start using the routes to carry news as well as commerce. Zomb watches its network expand via mechanisms it did not install."' },
    evil:{ text:'Defend the route. Information is Zomb\'s. Do not explain this.',
           alignment:-12, item:'blood_token',
           line:'"Route defended. Information flows. Zomb\'s network is intact. The traders carry goods without knowing they carry Zomb\'s data. This is how Zomb prefers it."' },
  },

  { id:'ba_z_s02', type:'survival', source:'zomb', age_min:1, cost:80, kill_count:4,
    offer:'"Bronze Forge. Four waves of ancient guardian constructs approaching the archive Zomb keeps beneath the forge floor. The archive cannot be lost. It predates this age by three cycles. Defend it."',
    room:'bronze_forge', monster:'bronze_golem', monster_label:'the archive-seeking guardians',
    good:{ text:'Defend the archive and ask what it contains.',
           alignment:+9, item:'spirit_ash',
           line:'"Archive defended. You asked. Zomb shows you three pages. The pages describe a world before this one, in a language you do not recognize. Zomb translates three lines. You do not speak for a long time after."' },
    evil:{ text:'Defend the archive without asking. Questions are not the mission.',
           alignment:-11, item:'dark_talisman',
           line:'"Archive defended. Intact. Zomb notes the discretion. The archive remains Zomb\'s alone. This is correct. It has always been Zomb\'s alone. Since the third world."' },
  },

  { id:'ba_z_s03', type:'survival', source:'zomb', age_min:1, cost:70, kill_count:3,
    offer:'"Tribal Village. Three consecutive attack waves — escalating pattern. Zomb has been observing this tribe\'s attack escalation for eight seasons. This is the culminating assault. Zomb needs to see how it resolves. Survive it."',
    room:'tribal_village', monster:'tribal_warrior', monster_label:'the escalating assault waves',
    good:{ text:'Survive all three waves and find what is driving the escalation.',
           alignment:+10, item:'bronze_remedy',
           line:'"Survived. The escalation was driven by water scarcity two valleys over — a resource conflict that presented as aggression. Addressed at the source. Zomb notes: the data behind aggression is often mundane."' },
    evil:{ text:'Survive all three waves. Let Zomb draw its own conclusions.',
           alignment:-10, item:'blood_token',
           line:'"All three waves survived. Zomb observes the pattern resolution. The eighth season of escalation data is complete. Zomb\'s conclusion: this tribe will not exist in six seasons. The projection is accurate."' },
  },

  // ── ZOMB COOPERATIVE (2) ─────────────────────────────────────────────────

  { id:'ba_z_co01', type:'cooperative', source:'zomb', age_min:1, cost:110, kill_count:1,
    offer:'"The Ancient Guardian — Guardian Gate. Zomb has studied it for this entire age. It cannot be faced alone. Zomb acknowledges this. Zomb is asking for collective action. Zomb will observe the collective action closely."',
    room:'guardian_gate', monster:'ancient_guardian', monster_label:'the Ancient Guardian',
    good:{ text:'Fight together. Share everything the Guardian was protecting equally.',
           alignment:+18, item:'mission_token',
           line:'"Guardian falls. Contents shared equally. Zomb notes: collective action achieved in ninety seconds what individual action could not achieve in any amount of time. Zomb updates efficiency calculations substantially."' },
    evil:{ text:'Fight together. Take the lead position. The lead earns the best share.',
           alignment:-13, item:'dark_talisman',
           line:'"Guardian falls. Lead position claimed. Primary share taken. The group notes the hierarchy. Zomb notes the group noting it. Hierarchies, once perceived, are either accepted or contested. Zomb waits."' },
  },

  { id:'ba_z_co02', type:'cooperative', source:'zomb', age_min:1, cost:95, kill_count:3,
    offer:'"Three simultaneous bronze golem activations — Bronze Forge. Zomb ran the calculation. Three people, minimum. No single entity survives three activated golems. Zomb does not make this statement easily. Come."',
    room:'bronze_forge', monster:'bronze_golem', monster_label:'the triple golem activation',
    good:{ text:'Cooperate fully. Share observations in real time during the fight.',
           alignment:+13, item:'bronze_remedy',
           line:'"Three golems down. Cooperation functioned. Real-time observations were shared. The group developed a new tactic mid-fight that Zomb had not calculated. Zomb updates the collective creativity variable upward."' },
    evil:{ text:'Cooperate instrumentally. Win first, sort the hierarchy after.',
           alignment:-11, item:'blood_token',
           line:'"Three golems down. Cooperation sufficient. Hierarchy sorted after. The hierarchy produced by combat is different from the hierarchy that entered combat. Zomb observes the reordering with interest."' },
  },

  // ── ZOMB SABOTAGE (2) ────────────────────────────────────────────────────

  { id:'ba_z_sa01', type:'sabotage', source:'zomb', age_min:1, cost:85,
    offer:'"Ancient Ruins. The excavation team has nearly found the complete founding records of this age. Complete founding records create continuity. Continuity creates loyalty to existing structures. Remove the team\'s ability to continue."',
    room:'ancient_ruins', monster:'bronze_golem', monster_label:'the excavation guardians',
    good:{ text:'Protect the excavation instead. Founding records are a foundation, not a trap.',
           alignment:+16, item:'mission_token',
           line:'"Excavation protected. Complete founding records recovered. The Bronze Age has its history now. Zomb recalculates the disruption timeline. Extended by one full age. Zomb notes this with something it does not name."' },
    evil:{ text:'Remove the team\'s ability to continue the excavation.',
           alignment:-17, item:'dark_talisman',
           line:'"Excavation disrupted. Founding records remain fragmented. The Bronze Age will not have its history. It will have its mythology instead. Mythology is more useful for Zomb\'s purposes."' },
  },

  { id:'ba_z_sa02', type:'sabotage', source:'zomb', age_min:1, cost:90,
    offer:'"Cursed Temple. The head priest is about to perform a ritual that will unite three warring factions under one spiritual authority. Unity produces stability. Zomb has explained the problem with stability. Disrupt the ritual."',
    room:'cursed_temple', monster:'tribal_high_priest', monster_label:'the unification ritual priest',
    good:{ text:'Let the ritual proceed. Three factions united under peace is not a problem.',
           alignment:+18, item:'bronze_remedy',
           line:'"Ritual completed. Three factions united. Stability follows. Zomb\'s conflict timeline extends by forty years. Zomb observes the forty years without enthusiasm and without active disruption. Zomb is waiting."' },
    evil:{ text:'Disrupt the ritual. Unity is a variable that complicates Zomb\'s model.',
           alignment:-20, item:'blood_token',
           line:'"Ritual disrupted. The three factions remain divided. The war between them begins within two seasons. Zomb watches from the archive. The pattern continues. As calculated."' },
  },

  // ── ZOMB INVESTIGATION (1) ────────────────────────────────────────────────

  { id:'ba_z_i01', type:'investigation', source:'zomb', age_min:1, cost:70,
    offer:'"Guardian Gate. The gate itself contains markings Zomb has never been able to access — carved on the inner face of the arch, only visible from inside the gate when it is open. Zomb needs someone to read them."',
    room:'guardian_gate', monster:'ancient_guardian', monster_label:'the gate guardian',
    good:{ text:'Access the markings and share exactly what they say with everyone.',
           alignment:+14, item:'spirit_ash',
           line:'"The markings are a warning. In the oldest language. They say: the gate is a door to what was before. Do not open it expecting what you know. Shared widely. Lilly is re-reading the translation. She is quiet."' },
    evil:{ text:'Access the markings and report only to Zomb.',
           alignment:-15, item:'dark_talisman',
           line:'"The markings report to Zomb. Zomb reads them three times. The gate was not built by the Bronze Age. The gate was built by the world before the flood before this one. Zomb updates the archive. The update is significant."' },
  },
];
