'use strict';
// ── Iron Age Missions (age_min: 2) — 50 total ────────────────────────────────

module.exports = [

  // ── Chain continuation from Bronze Age ────────────────────────────────────

  // ia_l_i_chain2 (from ba_l_i01 — ancient tablets good choice)
  { id:'ia_l_i_chain2', type:'investigation', source:'lilly', age_min:2, cost:0, is_chain_followup:true,
    offer:'"Friend — the tablet translation referenced something. A location. Iron Crossroads, the scholar thinks. The record from before the Bronze Age is incomplete without what is buried there. Will you look?"',
    room:'iron_crossroads', monster:'iron_wolf', monster_label:'the crossroads guardians',
    good:{ text:'Search carefully and share every fragment found with the scholar community.',
           alignment:+17, item:'iron_mandate',
           line:'"Found. Three more fragments. The combined record now spans four ages. Lilly reads it slowly. It describes what comes before every flood. She recognizes the description. She is sitting very still."',
           chain_next:'me_l_i_chain3' },
    evil:{ text:'Find the fragments and decide what gets shared based on what is safe to know.',
           alignment:-9, item:'iron_curse',
           line:'"Fragments found. Selectively shared. The record is partially assembled. The omitted sections are the most important ones. Lilly notes the omissions. She counts their weight."' },
  },

  // ia_z_k_chain2 (from ba_z_k_chain1 — relic collection)
  { id:'ia_z_k_chain2', type:'collection', source:'zomb', age_min:2, cost:0, is_chain_followup:true, kill_count:3,
    offer:'"The structure requires iron. Three iron ingots from the Iron Mines — specifically from the deepest level. The deepest level has not been mined in this age. The iron there predates this age. Zomb requires it."',
    room:'iron_mines', monster:'iron_wolf', monster_label:'the deep mine guardians',
    good:{ text:'Mine the iron and ask Zomb when the structure will be complete.',
           alignment:+5, item:'spirit_ash',
           line:'"Iron delivered. You asked. Zomb answers: when the last age ends. The structure will be complete at the moment the final flood begins. Zomb has been building it since the third world. It has never been complete. It will be complete this time."',
           chain_next:'me_z_k_chain3' },
    evil:{ text:'Mine the iron. The structure will be what it is.',
           alignment:-14, item:'iron_curse',
           line:'"Iron delivered. The structure grows. Zomb notes: the iron from the deepest level has properties the surface iron does not. Age-specific properties. The structure records them."',
           chain_next:'me_z_k_chain3' },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // LILLY MISSIONS (25) — Iron Age
  // ─────────────────────────────────────────────────────────────────────────

  // ── LILLY COMBAT (8) ─────────────────────────────────────────────────────

  { id:'ia_l_c01', type:'combat', source:'lilly', age_min:2, cost:80,
    offer:'"Iron Mines, friend. Miners — working miners, good people — are trapped by iron wolves in the lower shafts. The wolves got in through a collapsed section. The miners cannot get out. Please be fast, yes yes."',
    room:'iron_mines', monster:'iron_wolf', monster_label:'the shaft-blocking iron wolves',
    good:{ text:'Clear the wolves and help stabilize the collapsed section before leaving.',
           alignment:+14, item:'iron_elixir',
           line:'"Miners out. Section stabilized. No one was hurt. Lilly helped carry the youngest miner out — she was there for the rescue. She does not mention this. You may."' },
    evil:{ text:'Clear the wolves. The miners can handle the structural repair.',
           alignment:-8, item:'iron_curse',
           line:'"Wolves cleared. Miners out. The section collapsed further before they got the repair crew. Two miners were delayed by it. They got out. Lilly notes the sequence of events."' },
  },

  { id:'ia_l_c02', type:'combat', source:'lilly', age_min:2, cost:90,
    offer:'"Scarred Battlefield, friend. A medic unit — trying to treat the wounded from an old battle — is being harassed by iron warriors who never got the cease-order. The medics cannot fight and will not leave. Go."',
    room:'battlefield_scarred', monster:'iron_warrior', monster_label:'the cease-order warriors',
    good:{ text:'Clear the warriors and stay to help the medics treat the wounded.',
           alignment:+16, item:'iron_elixir',
           line:'"Medics protected. Wounded treated. Two people walked away from that battlefield who would not have otherwise. Lilly counts the walking ones. She always does."' },
    evil:{ text:'Clear the warriors and move on — the medics are professionals.',
           alignment:-6, item:'iron_mandate',
           line:'"Warriors cleared. Medics continued their work. One additional person did not walk away because there was no one to help carry them. Lilly counted. She always counts."' },
  },

  { id:'ia_l_c03', type:'combat', source:'lilly', age_min:2, cost:85,
    offer:'"Iron Fortress, friend. A prisoner — a scholar who discovered evidence of systematic deception in the fortress leadership — is being held before their silencing. The evidence must leave with them. Please go."',
    room:'iron_fortress', monster:'iron_knight', monster_label:'the fortress jailers',
    good:{ text:'Extract the scholar and help them publish the evidence widely.',
           alignment:+19, item:'iron_mandate',
           line:'"Scholar free. Evidence published. The fortress leadership investigated. Three systemic deceptions ended. The Iron Age governing structures are slightly more honest today. Slightly. Lilly counts slight improvements. Yes yes."' },
    evil:{ text:'Extract the scholar. The evidence is their business.',
           alignment:-7, item:'mission_token',
           line:'"Scholar free. Evidence in their hands. They published it two months later — alone, without support. The impact was smaller than it could have been. Lilly notes impact and timing are related."' },
  },

  { id:'ia_l_c04', type:'combat', source:'lilly', age_min:2, cost:75,
    offer:'"Watchtower, friend — iron sentinels are preventing humanitarian supply wagons from reaching the siege camp. The wagons carry medicine. The sentinels have no reason given for the blockade. The medicine has to get through."',
    room:'iron_watchtower', monster:'iron_sentinel', monster_label:'the supply-blocking sentinels',
    good:{ text:'Clear the sentinels and investigate why the blockade was ordered.',
           alignment:+15, item:'iron_elixir',
           line:'"Sentinels cleared. Blockade investigated. The order came from a supply contractor who wanted the camp to buy his medicine instead. The contractor was reported. Lilly notes: systems contain people, and people contain motives."' },
    evil:{ text:'Clear the sentinels. The wagons can move — that is enough.',
           alignment:-5, item:'iron_mandate',
           line:'"Sentinels cleared. Wagons moved. The blockade order was reinstated via a different route three days later. Clearing without investigating is temporary. Lilly notes."' },
  },

  { id:'ia_l_c05', type:'combat', source:'lilly', age_min:2, cost:95,
    offer:'"Volcano Heart, friend. A community of smelters who live at the volcano — who have nowhere else to go — are being driven out by iron knights who want the caldera exclusively. They built their homes there. Help them."',
    room:'volcano_heart', monster:'iron_knight', monster_label:'the displacement iron knights',
    good:{ text:'Drive the knights back and help the community establish legal claim to their homes.',
           alignment:+18, item:'iron_mandate',
           line:'"Knights driven back. Legal claim established with the elders. The community stayed. Lilly helped them draft the claim document. She has very neat handwriting for someone who grew up in a cave. Yes yes."' },
    evil:{ text:'Drive the knights back. The community will manage the rest.',
           alignment:-6, item:'iron_elixir',
           line:'"Knights driven back. The community is safe for now. No legal claim established. The knights returned with a different argument six weeks later. Lilly notes: safety without foundation is a tent, not a house."' },
  },

  { id:'ia_l_c06', type:'combat', source:'lilly', age_min:2, cost:80,
    offer:'"Iron Crossroads, friend. The merchant there — the good one, who charges fair prices — is being pressured by an iron warrior faction to leave or pay protection. She will not pay. She needs someone to make her point."',
    room:'iron_crossroads', monster:'iron_warrior', monster_label:'the protection-demanding warriors',
    good:{ text:'Defend the merchant and help her organize the other crossroads traders into a mutual defense.',
           alignment:+14, item:'mission_token',
           line:'"Merchant defended. Mutual defense established. Four traders organized. The protection faction moved on to easier targets. Lilly notes: collective resistance is more durable than individual courage."' },
    evil:{ text:'Defend the merchant. This time.',
           alignment:-4, item:'iron_elixir',
           line:'"Merchant defended this visit. Next visit — different approach from the faction, same goal. The merchant is alone again. Lilly notes the inadequacy of single interventions."' },
  },

  { id:'ia_l_c07', type:'combat', source:'lilly', age_min:2, cost:85,
    offer:'"Iron Mines. A group of workers — the youngest ones, sent in first as is the custom — are trapped in a cave-in section. The iron wolves moved in after the collapse. Every age has customs Lilly cannot stand. This is one of them."',
    room:'iron_mines', monster:'iron_wolf', monster_label:'the post-collapse iron wolves',
    good:{ text:'Clear the wolves and bring the youngest workers out first, whatever the rescue order says.',
           alignment:+17, item:'iron_elixir',
           line:'"Youngest workers out first. All workers out. The custom was challenged at the elders\' council after. Lilly attended the council. She spoke. The custom was reviewed. Progress."' },
    evil:{ text:'Clear the wolves and follow the established rescue order.',
           alignment:-9, item:'iron_mandate',
           line:'"Wolves cleared. Standard rescue order followed. The youngest were last. They survived. Lilly challenges the custom regardless. The custom continues. She challenges it again."' },
  },

  { id:'ia_l_c08', type:'combat', source:'lilly', age_min:2, cost:90,
    offer:'"Battlefield, friend. An iron revenant — a fallen warrior reanimated by unresolved conflict — is haunting the old lines. It attacks anyone who comes to bury the dead. The dead deserve burial. Please go."',
    room:'battlefield_scarred', monster:'iron_warrior', monster_label:'the burial-preventing revenant',
    good:{ text:'Defeat the revenant and stay to help complete the burials.',
           alignment:+16, item:'iron_mandate',
           line:'"Revenant laid to rest. The dead were buried. Lilly came after and put flowers on three of the graves — the ones with no names. She came back the following spring and the flowers were still there. Someone else had added more."' },
    evil:{ text:'Defeat the revenant and leave the burial to the burial crew.',
           alignment:-4, item:'iron_elixir',
           line:'"Revenant cleared. The burial crew came. The dead were buried. Lilly notes the outcome was the same and also different. She knows the difference. You may think about what it is."' },
  },

  // ── LILLY HUNT (4) ───────────────────────────────────────────────────────

  { id:'ia_l_h01', type:'hunt', source:'lilly', age_min:2, cost:90,
    offer:'"Iron Fortress, friend. An iron knight — the warden of the knowledge vault there — holds the keys to a sealed archive of pre-war records. The archive needs to be opened before the faction purges it. Find the warden."',
    room:'iron_fortress', monster:'iron_knight', monster_label:'the vault warden',
    good:{ text:'Find the warden and ask if they will open the archive willingly.',
           alignment:+18, item:'iron_mandate',
           line:'"The warden opened it willingly. They had been waiting for someone to ask. The archive contains forty years of pre-war correspondence — proposals for peace that never reached the right desks. Lilly reads them all."' },
    evil:{ text:'Find the warden and take the keys by the most direct method.',
           alignment:-12, item:'iron_curse',
           line:'"Keys taken. Archive opened. The warden is not dead — injured. They knew where the keys were because they were going to open it themselves next week. Lilly notes: asking first takes ten minutes."' },
  },

  { id:'ia_l_h02', type:'hunt', source:'lilly', age_min:2, cost:85,
    offer:'"Iron Mines. The deepest shift — a team lead who knows how to read the structural warnings in the rock before a collapse. She trains others in this. If she is lost in the collapse, the knowledge is lost. Find her."',
    room:'iron_mines', monster:'iron_wolf', monster_label:'the collapse-zone wolves',
    good:{ text:'Find her and get her out while listening to everything she says about the rock.',
           alignment:+15, item:'iron_elixir',
           line:'"Found. Out. She talked the entire extraction. The structural warning system she described was written down and distributed to every mine in the Iron Age. Lilly transcribed the technical parts. It saved thirty-seven people she never met."' },
    evil:{ text:'Find her and extract her fast. The knowledge can be documented after.',
           alignment:-5, item:'iron_mandate',
           line:'"Found and extracted quickly. Documentation attempted after — the urgency is gone and the recollection is incomplete. Twelve warnings from the original knowledge are missing. Twelve gaps in safety."' },
  },

  { id:'ia_l_h03', type:'hunt', source:'lilly', age_min:2, cost:95,
    offer:'"Scarred Battlefield, friend. Someone is still fighting a war that ended twenty years ago. An iron warrior who never received the cease-fire order. They are dangerous, yes — but they are also simply not informed. Please find them."',
    room:'battlefield_scarred', monster:'iron_warrior', monster_label:'the twenty-years-isolated warrior',
    good:{ text:'Find them and tell them the war is over before engaging.',
           alignment:+20, item:'iron_mandate',
           line:'"Told. The war is over. The warrior stopped. Sat down. Cried. Came back with you. Became a teacher of conflict resolution in a light settlement for the next thirty years. Lilly cried about this story too. Yes yes."' },
    evil:{ text:'Find them and end the threat.',
           alignment:-15, item:'iron_curse',
           line:'"Found and ended. The threat is removed. Lilly learns later they were fighting a war that had ended twenty years earlier. She is quiet for a long time. She was asked what was wrong. She did not answer."' },
  },

  { id:'ia_l_h04', type:'hunt', source:'lilly', age_min:2, cost:80,
    offer:'"Watchtower, friend. An iron sentinel has separated from its post and is wandering the mines — which means the watchtower has a gap. But also the sentinel is behaving strangely. Something may be wrong with it. Find it."',
    room:'iron_watchtower', monster:'iron_sentinel', monster_label:'the wandering sentinel',
    good:{ text:'Find it gently. Understand what is wrong before acting.',
           alignment:+12, item:'iron_elixir',
           line:'"Found. Something damaged its directive during the last battle. It has been walking the mine route its original charge walked — before the battle changed everything. Lilly considers this the saddest thing she has heard this age."' },
    evil:{ text:'Find it and return it to its post by force if necessary.',
           alignment:-8, item:'iron_mandate',
           line:'"Found. Returned to post. The watchtower gap is filled. What was wrong with the sentinel remains unaddressed. It walks the route again three weeks later."' },
  },

  // ── LILLY ESCORT (4) ─────────────────────────────────────────────────────

  { id:'ia_l_e01', type:'escort', source:'lilly', age_min:2, cost:85,
    offer:'"A philosopher, friend — the first one willing to speak in public about what the war has cost. She will speak at the Iron Crossroads market. She needs to get there. The faction that does not want her speaking knows the route."',
    room:'iron_crossroads', monster:'iron_warrior', monster_label:'the silencing faction',
    good:{ text:'Escort her and stand beside her while she speaks.',
           alignment:+17, item:'iron_mandate',
           line:'"She spoke. You stood beside her. The crowd that gathered was three times the size of any previous public speech in this age. Lilly listened from the second row. She remembers every word."' },
    evil:{ text:'Escort her to the crossroads and slip away before the speech.',
           alignment:-6, item:'mission_token',
           line:'"She spoke alone. Smaller crowd. The speech was still important. It would have been more important with someone standing beside her. Lilly notes: presence multiplies impact."' },
  },

  { id:'ia_l_e02', type:'escort', source:'lilly', age_min:2, cost:90,
    offer:'"Iron Fortress. Three civilian families are inside the fortress and the command structure just changed — the new command does not recognize civilian protections. Lilly needs them out before anyone gives an order. Please."',
    room:'iron_fortress', monster:'iron_knight', monster_label:'the new-order fortress knights',
    good:{ text:'Extract all three families and help them establish safety in the light settlement.',
           alignment:+19, item:'iron_elixir',
           line:'"All three families out. Established in the light settlement. All children attending the school Lilly helped found two ages ago. One of those children becomes something important later. Lilly knows which one."' },
    evil:{ text:'Extract all three. The settlement placement is their decision.',
           alignment:-4, item:'iron_mandate',
           line:'"All three families out. They managed their own placement. One family found the light settlement; two were absorbed into a faction settlement. The outcomes diverged. Lilly wonders about the two."' },
  },

  { id:'ia_l_e03', type:'escort', source:'lilly', age_min:2, cost:80,
    offer:'"Battlefield, friend. A wounded iron warrior — not fighting anymore, just wounded — needs to reach the field medic camp. Other warriors are treating them as a deserter. They are not a deserter. They are hurt."',
    room:'battlefield_scarred', monster:'iron_warrior', monster_label:'the deserter-hunting warriors',
    good:{ text:'Escort them and publicly dispute the deserter accusation.',
           alignment:+15, item:'iron_elixir',
           line:'"Escorted and dispute made public. The accusation was withdrawn — there was no formal desertion record. The warrior received treatment. The medic camp director later cites this case in the new field standards. Lilly helped draft those standards."' },
    evil:{ text:'Escort them quietly. Get them to the medic camp without the argument.',
           alignment:-4, item:'mission_token',
           line:'"Escorted quietly. Medic camp reached. The accusation was never disputed. The warrior was treated but the deserter record remained. Lilly notes: quiet solutions sometimes leave quiet problems."' },
  },

  { id:'ia_l_e04', type:'escort', source:'lilly', age_min:2, cost:95,
    offer:'"Volcano Heart, friend. The smelter foreman — who holds the combined technical knowledge of every Iron Age metal process — is being coerced to join a war faction. She refuses. They are going to stop asking soon. Get her out."',
    room:'volcano_heart', monster:'iron_knight', monster_label:'the coercion detail',
    good:{ text:'Extract the foreman and help her establish an independent teaching foundry.',
           alignment:+18, item:'iron_mandate',
           line:'"Foreman free. Independent foundry established. The technical knowledge is now taught openly to anyone who wants to learn. The war faction\'s monopoly on advanced metalwork breaks within one season. Lilly considers this structurally beautiful."' },
    evil:{ text:'Extract the foreman. What she does with the knowledge is her decision.',
           alignment:-5, item:'iron_elixir',
           line:'"Foreman free. She established a foundry with a selective admissions process — only her chosen students. The knowledge spreads, but slowly, and the hierarchy it creates is not what Lilly hoped for."' },
  },

  // ── LILLY COLLECTION (3) ─────────────────────────────────────────────────

  { id:'ia_l_k01', type:'collection', source:'lilly', age_min:2, cost:80, kill_count:3,
    offer:'"Iron Mines. Three iron ingots for the settlement forge — the settlement that has been waiting nine months for these because the faction controlled distribution collapsed. Lilly is doing this the direct way. Three ingots, please."',
    room:'iron_mines', monster:'iron_wolf', monster_label:'the mine guardians',
    good:{ text:'Collect three and report the distribution collapse to the settlement elders.',
           alignment:+12, item:'mission_token',
           line:'"Three ingots. Distribution collapse reported. The elders established a direct sourcing agreement that bypassed the faction. Lilly helped write the agreement. She had a good lawyer in the Iron Age. She was the lawyer."' },
    evil:{ text:'Collect three and deliver them without the report.',
           alignment:-4, item:'iron_elixir',
           line:'"Three ingots delivered. The distribution collapse continues for other settlements that did not get a personal advocate. Lilly notes: solving one problem without addressing the system solves one problem."' },
  },

  { id:'ia_l_k02', type:'collection', source:'lilly', age_min:2, cost:85, kill_count:4,
    offer:'"Scarred Battlefield. Four runed stones — artifacts from soldiers who carried them for protection. They are scattered on the field, unclaimed. Families are looking for them. They have names carved in them. Four stones, friend."',
    room:'battlefield_scarred', monster:'iron_warrior', monster_label:'the battlefield wolves',
    good:{ text:'Collect all four and spend the time to match them to the right families.',
           alignment:+16, item:'iron_mandate',
           line:'"Four stones. Four families found through three weeks of searching. Lilly helped search. All four stones returned. The response from the families was not something Lilly describes. She just nods when asked."' },
    evil:{ text:'Collect all four. Leave them with the settlement for families to claim.',
           alignment:-3, item:'iron_elixir',
           line:'"Four stones left at the settlement. Two were claimed in the first week. Two waited unclaimed for eight months. The families never came. Lilly visits the unclaimed ones."' },
  },

  { id:'ia_l_k03', type:'collection', source:'lilly', age_min:2, cost:90, kill_count:5,
    offer:'"Watchtower, friend. Five iron ingots from the tower\'s abandoned stores — abandoned when the last watch rotation was pulled. The stores will be looted before the end of the season. Let them go to the settlement hospital instead."',
    room:'iron_watchtower', monster:'iron_sentinel', monster_label:'the tower guardians',
    good:{ text:'Collect all five and personally deliver them to the hospital.',
           alignment:+14, item:'iron_elixir',
           line:'"Five ingots to the hospital. The hospital used them to build a new treatment wing. The wing treated sixty-three patients in its first season. Lilly counts the patients. Yes yes."' },
    evil:{ text:'Collect all five. Best price, most benefit.',
           alignment:-7, item:'iron_mandate',
           line:'"Five ingots sold to the best buyer. Good price. The hospital did not get the wing. The best buyer built a warehouse. Lilly notes: efficiency and good are not synonyms."' },
  },

  // ── LILLY SURVIVAL (2) ───────────────────────────────────────────────────

  { id:'ia_l_s01', type:'survival', source:'lilly', age_min:2, cost:95, kill_count:5,
    offer:'"Iron Crossroads under siege, friend — five waves of iron warriors. The merchant there, the good one, has nowhere to run. The crossroads is the only place she can be. Hold it. Hold it long enough for the elders to arrive."',
    room:'iron_crossroads', monster:'iron_warrior', monster_label:'the crossroads siege waves',
    good:{ text:'Hold every wave and make sure the merchant is behind you the whole time.',
           alignment:+17, item:'iron_elixir',
           line:'"Five waves. Held. The elders arrived and the siege withdrew. The merchant is alive. She gave Lilly a large discount for the rest of the age. Lilly did not use it. She told the merchant to give it to someone who needed it instead."' },
    evil:{ text:'Hold the crossroads. The merchant manages her own cover.',
           alignment:-8, item:'iron_mandate',
           line:'"Crossroads held. Merchant survived behind a barrel. Close. Very close. Five waves. Lilly notes the barrel. She notes it specifically."' },
  },

  { id:'ia_l_s02', type:'survival', source:'lilly', age_min:2, cost:100, kill_count:4,
    offer:'"Volcano Heart. The last smelter team — the ones who refused to leave despite the iron knight occupation — are holding the caldera access point. They cannot fight. They hold it by being present. Back them up, friend."',
    room:'volcano_heart', monster:'iron_knight', monster_label:'the caldera occupation force',
    good:{ text:'Defend their position and help them articulate why they have the right to be there.',
           alignment:+19, item:'iron_mandate',
           line:'"Position defended. Case articulated. The occupation was challenged through the elder council. The smelter team\'s right was recognized. The caldera stayed with those who built it. Lilly helped with the argument structure. She is good at argument structure."' },
    evil:{ text:'Defend their position. Victory is the argument.',
           alignment:-10, item:'iron_curse',
           line:'"Position defended. Victory held the caldera. The recognition did not come — only the force did. When the force is removed, the challenge returns. Lilly notes: force holds position; right holds it indefinitely."' },
  },

  // ── LILLY COOPERATIVE (2) ─────────────────────────────────────────────────

  { id:'ia_l_co01', type:'cooperative', source:'lilly', age_min:2, cost:120, kill_count:1,
    offer:'"Iron Colossus, friend — Volcano Heart. It cannot be faced alone. It was not meant to be faced alone. The smelters built it to be defeated by people working together. They built in that lesson on purpose. Please come."',
    room:'volcano_heart', monster:'iron_colossus', monster_label:'the Iron Colossus',
    good:{ text:'Cooperate fully. Share the rewards equally. Honor the lesson built into the Colossus.',
           alignment:+23, item:'iron_mandate',
           line:'"Colossus fell. Rewards shared. The smelters were right — there is a way through that only works if every person does their part. Lilly says: the smelters knew something. Let us be worthy of that knowledge."' },
    evil:{ text:'Cooperate enough to win. Lead claims lead reward.',
           alignment:-14, item:'iron_curse',
           line:'"Colossus fell. Lead reward claimed. The cooperation that earned it is already fracturing over the distribution. The smelters built the lesson in. You are the lesson\'s opposing variable."' },
  },

  { id:'ia_l_co02', type:'cooperative', source:'lilly', age_min:2, cost:110, kill_count:3,
    offer:'"Scarred Battlefield, friend. Three iron knights — simultaneously, coordinated, from three approaches. Lilly has asked every capable defender she knows. This requires everyone. Yes yes please come."',
    room:'battlefield_scarred', monster:'iron_knight', monster_label:'the three-direction iron knight assault',
    good:{ text:'Fight as a true unit. Cover each other. No one left behind.',
           alignment:+18, item:'iron_elixir',
           line:'"Three knights. Three defenders covering each other. Zero casualties. The battlefield coordination developed in this fight becomes the basis for a new defense doctrine. Lilly copies the doctrine and distributes it."' },
    evil:{ text:'Fight together but prioritize your own survival when it comes to it.',
           alignment:-10, item:'iron_mandate',
           line:'"Three knights down. Two defenders injured because coverage slipped when priorities shifted. Fought. Won. Lilly notes the difference between won together and won at different costs."' },
  },

  // ── LILLY SABOTAGE (1) ───────────────────────────────────────────────────

  { id:'ia_l_sa01', type:'sabotage', source:'lilly', age_min:2, cost:100,
    offer:'"The Empire Standard, friend — the faction that plans to raise it over the Iron Crossroads marketplace claims everything beneath it by that act. They are raising it at dawn. If it rises, all the independent traders lose their standing."',
    room:'iron_crossroads', monster:'iron_warrior', monster_label:'the standard-raising guard',
    good:{ text:'Prevent the raising and help the traders establish a formal independent charter.',
           alignment:+20, item:'iron_mandate',
           line:'"Standard not raised. Charter established. The Independent Traders Charter of the Iron Age is one of Lilly\'s proudest documents. She keeps a copy in the cave. She has re-read it eleven times."' },
    evil:{ text:'Prevent the raising. That is enough for today.',
           alignment:-7, item:'iron_elixir',
           line:'"Standard not raised. Today. The faction is already planning a different approach. Lilly notes: delay is not victory. Delay is delay."' },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ZOMB MISSIONS (25) — Iron Age
  // ─────────────────────────────────────────────────────────────────────────

  // ── ZOMB COMBAT (5) ──────────────────────────────────────────────────────

  { id:'ia_z_c01', type:'combat', source:'zomb', age_min:2, cost:85,
    offer:'"Iron Mines. The mine superintendent has established a safety system — inspection protocols, structural ratings, rest requirements. The system slows production. Slower production delays conflict. Remove the safety system\'s enforcer."',
    room:'iron_mines', monster:'iron_sentinel', monster_label:'the safety enforcement sentinel',
    good:{ text:'Protect the enforcer. Safety systems produce sustainable outcomes.',
           alignment:+13, item:'iron_elixir',
           line:'"Enforcer protected. Safety system continues. Production is slower. The mine has not collapsed in six seasons. Zomb notes: sustainable production has a longer output than accelerated collapse. The calculation is not wrong."' },
    evil:{ text:'Remove the enforcer. Production acceleration matters more.',
           alignment:-16, item:'iron_curse',
           line:'"Enforcer removed. Production accelerated. Mine collapse projected in four seasons. Zomb\'s conflict timeline advances. The miners who remain are producing at higher rates. Temporarily."' },
  },

  { id:'ia_z_c02', type:'combat', source:'zomb', age_min:2, cost:90,
    offer:'"Scarred Battlefield. A ceasefire negotiation is in progress — both factions, in person. Successful negotiation ends the current war. Ended wars produce peaceful entities. Disrupt the negotiation. The battlefield serves the cycle."',
    room:'battlefield_scarred', monster:'iron_warrior', monster_label:'the ceasefire guard',
    good:{ text:'Protect the negotiation instead. War\'s end is not a problem.',
           alignment:+17, item:'iron_elixir',
           line:'"Negotiation protected. Ceasefire signed. The war ends. Zomb\'s conflict timeline extends by twelve years. Zomb observes twelve years of relative peace from the archive. Zomb updates the value of peace in the long model. Hesitantly."' },
    evil:{ text:'Disrupt the negotiation. The cycle requires conflict.',
           alignment:-18, item:'iron_curse',
           line:'"Negotiation disrupted. Ceasefire failed. The war resumes on schedule. Zomb\'s calculation holds. Zomb watches from the archive. The pattern continues. Zomb is not comfortable naming what it feels about that."' },
  },

  { id:'ia_z_c03', type:'combat', source:'zomb', age_min:2, cost:95,
    offer:'"Iron Fortress. An iron knight has begun training others in a defensive technique that makes the fortress essentially impregnable. Impregnable fortresses do not fall. Falling is part of the cycle. End the training program."',
    room:'iron_fortress', monster:'iron_knight', monster_label:'the defensive training knight',
    good:{ text:'Let the training continue. Defense is not the enemy of the cycle.',
           alignment:+12, item:'iron_mandate',
           line:'"Training continues. Fortress increasingly impregnable. Zomb notes: the cycle does not require every fortress to fall, only enough to create pressure. Impregnable nodes redirect conflict elsewhere. Zomb updates the model."' },
    evil:{ text:'End the training program.',
           alignment:-14, item:'iron_curse',
           line:'"Training ended. Fortress defense degrades. Projection: fortress vulnerable within eight seasons. Zomb\'s cycle continues on schedule."' },
  },

  { id:'ia_z_c04', type:'combat', source:'zomb', age_min:2, cost:100,
    offer:'"Volcano Heart. The iron colossus there serves as a deterrent — its presence prevents certain attacks on the caldera. Deterrents prevent conflict. Deterrent removal creates conflict. Remove the deterrent\'s ability to function."',
    room:'volcano_heart', monster:'iron_colossus', monster_label:'the deterrent Colossus',
    good:{ text:'Leave the Colossus. Deterrents that prevent unnecessary conflict serve a function.',
           alignment:+15, item:'iron_elixir',
           line:'"Colossus left intact. Its deterrent effect continues. Zomb calculates: fourteen conflicts prevented by its presence in the last age. Fourteen conflicts. Zomb sits with the calculation."' },
    evil:{ text:'Reduce the Colossus\'s functionality. Remove the deterrent.',
           alignment:-17, item:'iron_curse',
           line:'"Colossus functionality reduced. Deterrent effect diminished. Three attack attempts on the caldera follow within two seasons. Zomb\'s projection confirmed. The cycle is served."' },
  },

  { id:'ia_z_c05', type:'combat', source:'zomb', age_min:2, cost:85,
    offer:'"Iron Crossroads. The neutral merchant who maintains trade between all factions regardless of alignment — she is a stabilizing node. Stabilizing nodes reduce volatility. Volatility produces pressure. Pressure produces events. Remove the node."',
    room:'iron_crossroads', monster:'iron_warrior', monster_label:'the crossroads protection',
    good:{ text:'Protect the merchant. Neutral nodes enable communication between adversaries.',
           alignment:+13, item:'mission_token',
           line:'"Merchant protected. Neutral trade continues. Three faction disputes were resolved through the crossroads in the following season — disputes that would have escalated to violence without the neutral node. Zomb notes: nodes have functions Zomb has been undervaluing."' },
    evil:{ text:'Remove the stabilizing node.',
           alignment:-15, item:'iron_curse',
           line:'"Merchant displaced. Neutral trade interrupted. Three faction disputes escalate to violence within one season. Zomb\'s volatility calculation was correct. The calculation does not feel like a success. Zomb notes this discomfort."' },
  },

  // ── ZOMB HUNT (4) ────────────────────────────────────────────────────────

  { id:'ia_z_h01', type:'hunt', source:'zomb', age_min:2, cost:90,
    offer:'"Iron Mines. An iron revenant — a fallen knight reanimated by pure unresolved purpose. Zomb has been watching it for two seasons. Its purpose was architectural: to complete a structure in the mine. Zomb wants the structure found. Find the revenant."',
    room:'iron_mines', monster:'iron_warrior', monster_label:'the purpose-driven iron revenant',
    good:{ text:'Find the revenant and try to help it complete what it started.',
           alignment:+11, item:'spirit_ash',
           line:'"The revenant was helped to complete the structure. It was a sealed vault inside the mine — sealed before the Iron Age. Inside: records from an age before the Bronze Age. The revenant rested after completion. Lilly cried about this story. Zomb noted her response."' },
    evil:{ text:'Find the revenant and end its patrol. The structure is not the priority.',
           alignment:-12, item:'iron_curse',
           line:'"Revenant ended. The structure was never found. Zomb searches the mine independently for three seasons. The sealed vault eludes discovery. Zomb recalculates the loss."' },
  },

  { id:'ia_z_h02', type:'hunt', source:'zomb', age_min:2, cost:95,
    offer:'"Watchtower. The iron sentinel there has been recording every entity that passes below for one hundred years. One hundred years of passage data. Zomb needs the record. The sentinel is the record. Find it."',
    room:'iron_watchtower', monster:'iron_sentinel', monster_label:'the record-keeping sentinel',
    good:{ text:'Find the sentinel and help it share the record with everyone who is mentioned in it.',
           alignment:+10, item:'iron_mandate',
           line:'"Record shared. One hundred years of passage data, publicly accessible. Three genealogies were traced. Two land disputes resolved. One person found their grandmother\'s name. Zomb found six patterns that advance the cycle model significantly."' },
    evil:{ text:'Find the sentinel and bring the record to Zomb exclusively.',
           alignment:-13, item:'dark_talisman',
           line:'"Record delivered to Zomb exclusively. One hundred years of data in Zomb\'s archive. The patterns it reveals update the model substantially. The three genealogies and the grandmother\'s name remain undiscovered. Zomb notes: exclusive data has a cost to others."' },
  },

  { id:'ia_z_h03', type:'hunt', source:'zomb', age_min:2, cost:85,
    offer:'"Battlefield. A specific iron warrior — alive, not a revenant — who has fought in twelve battles and never been injured. Statistically impossible. Zomb needs to understand the mechanism. Find this entity."',
    room:'battlefield_scarred', monster:'iron_warrior', monster_label:'the uninjured veteran',
    good:{ text:'Find them and talk to them. How you survive twelve battles is information worth sharing.',
           alignment:+9, item:'iron_elixir',
           line:'"Found. Spoken with. They trained with the mine shift lead\'s structural warning system — applied to bodies instead of rock. Felt what was about to happen before it happened. Shared the method openly. Fourteen people learned it. Zomb notes the multiplication."' },
    evil:{ text:'Find them and study what makes them survive. Exclusively.',
           alignment:-11, item:'iron_curse',
           line:'"Found. Studied. The mechanism is identified. Exclusive knowledge of a survival technique. Zomb notes the method can be applied to Zomb\'s own movement patterns. The application is implemented."' },
  },

  { id:'ia_z_h04', type:'hunt', source:'zomb', age_min:2, cost:100,
    offer:'"Volcano Heart. An iron knight — the only one who knows the caldera\'s structural weakness, the specific point that would cause collapse if struck. This knowledge must not spread. Find this knight. Secure the knowledge."',
    room:'volcano_heart', monster:'iron_knight', monster_label:'the structural knowledge knight',
    good:{ text:'Find them and convince them to share the knowledge with the structural safety team.',
           alignment:+14, item:'iron_mandate',
           line:'"Found. Knowledge shared with the structural safety team. The weakness was reinforced before anyone could exploit it. Zomb recalculates the caldera threat level to near zero. Zomb is annoyed and correct about being annoyed."' },
    evil:{ text:'Find them. Secure the knowledge for Zomb\'s use.',
           alignment:-15, item:'iron_curse',
           line:'"Found. Knowledge secured by Zomb. The caldera weakness is documented in the archive. One entity knows it. The caldera is vulnerable to that entity. Zomb notes: power concentrated is power exposed to single points of failure."' },
  },

  // ── ZOMB ESCORT (3) ──────────────────────────────────────────────────────

  { id:'ia_z_e01', type:'escort', source:'zomb', age_min:2, cost:90,
    offer:'"Iron Mines. A data courier — carrying Zomb\'s observation records from the mine to the archive. The route passes through the wolves\' primary territory. The data must arrive. Escort the courier. The records cannot be lost."',
    room:'iron_mines', monster:'iron_wolf', monster_label:'the wolf-pack route hazard',
    good:{ text:'Escort the courier safely and ask what the records contain.',
           alignment:+7, item:'spirit_ash',
           line:'"Courier delivered. You asked. Zomb considers the answer. The records document every entity who worked in that mine for fifty years. Their choices. Their outcomes. The relationship between choice and outcome. You have contributed to that record."' },
    evil:{ text:'Escort the courier. Do not ask about the records.',
           alignment:-10, item:'iron_curse',
           line:'"Courier delivered. Records intact. Zomb\'s archive grows. You have performed this function efficiently. Zomb notes efficiency. Also notes the absence of curiosity. Both are data."' },
  },

  { id:'ia_z_e02', type:'escort', source:'zomb', age_min:2, cost:95,
    offer:'"Iron Fortress. A defector — a former faction operative who carries information on the faction\'s three-year plan. Zomb wants this information before the faction recovers the defector. Escort them to the archive."',
    room:'iron_fortress', monster:'iron_knight', monster_label:'the faction recovery force',
    good:{ text:'Escort the defector to safety and ensure their information becomes public.',
           alignment:+14, item:'iron_mandate',
           line:'"Defector safe. Three-year plan public. Three faction initiatives disrupted by counter-preparation. The defector was granted protection by the light settlement. Zomb\'s archive received a copy. Mutual benefit. Zomb notes this outcome neutrally."' },
    evil:{ text:'Escort the defector to Zomb\'s archive. Exclusively.',
           alignment:-12, item:'iron_curse',
           line:'"Defector at Zomb\'s archive. Three-year plan exclusive to Zomb. Faction initiatives proceed unchallenged publicly. Zomb uses the information for its own calculations. The defector is safe. The plan they betrayed continues."' },
  },

  { id:'ia_z_e03', type:'escort', source:'zomb', age_min:2, cost:85,
    offer:'"Scarred Battlefield. An archivist who was copying battlefield records for Zomb\'s collection was caught in a skirmish. They are alive but pinned. The records they carry are three months of documentation. Extract both."',
    room:'battlefield_scarred', monster:'iron_warrior', monster_label:'the battlefield skirmish',
    good:{ text:'Extract the archivist and help them continue the work more safely.',
           alignment:+9, item:'iron_elixir',
           line:'"Archivist extracted. Work continues from a safer position. The battlefield record is complete for the first time in this age. Lilly asks for a copy. Zomb provides one. This exchange surprises both of them."' },
    evil:{ text:'Extract the records first, then the archivist.',
           alignment:-11, item:'iron_curse',
           line:'"Records extracted first. Archivist extracted second — sixteen seconds after. They noted the priority order. They continue working for Zomb. They note the priority order every time they see you."' },
  },

  // ── ZOMB COLLECTION (3) ──────────────────────────────────────────────────

  { id:'ia_z_k01', type:'collection', source:'zomb', age_min:2, cost:85, kill_count:4,
    offer:'"Watchtower. Four iron ingots from the tower stores — the old stock, pre-age. They carry compositional markers that Zomb is mapping across the age transitions. Four ingots, old stock specifically."',
    room:'iron_watchtower', monster:'iron_sentinel', monster_label:'the tower sentinels',
    good:{ text:'Collect four, verify they are old stock, and ask what the compositional mapping reveals.',
           alignment:+7, item:'spirit_ash',
           line:'"Four old-stock ingots. You asked. Zomb shows you the mapping. The iron composition changes at each age transition — a signature shift. The same signature appears in the bones of the archive. Everything is connected. Zomb has been noting this since the third world."' },
    evil:{ text:'Four ingots. Old stock if possible.',
           alignment:-9, item:'iron_curse',
           line:'"Four ingots collected. Two confirmed old stock. Two ambiguous. The mapping is partially complete. Zomb notes: partial maps produce conclusions with error margins. Zomb dislikes error margins."' },
  },

  { id:'ia_z_k02', type:'collection', source:'zomb', age_min:2, cost:90, kill_count:3,
    offer:'"Battlefield. Three runed stones — specifically the ones carved with the pre-war settlement agreements. Zomb studies the agreements that preceded wars. The stones carry them. Three stones."',
    room:'battlefield_scarred', monster:'iron_warrior', monster_label:'the battlefield hazard',
    good:{ text:'Collect three and share the pre-war agreements they contain with the current negotiators.',
           alignment:+12, item:'iron_elixir',
           line:'"Three stones. Agreements shared with current negotiators. Two terms from the pre-war agreements were adopted into the current ceasefire draft. Zomb notes: the past\'s good terms sometimes survive into the future."' },
    evil:{ text:'Three stones to Zomb\'s archive.',
           alignment:-10, item:'iron_curse',
           line:'"Three stones in Zomb\'s archive. The pre-war agreements are documented. The current negotiators do not have them. The ceasefire terms are weaker without them. Zomb\'s archive holds the difference."' },
  },

  { id:'ia_z_k03', type:'collection', source:'zomb', age_min:2, cost:95, kill_count:5,
    offer:'"Volcano Heart. Five iron shards from the Colossus\'s construction debris — the shards that broke off during its creation. The original forge process is encoded in the failure patterns. Five construction-era shards."',
    room:'volcano_heart', monster:'iron_knight', monster_label:'the caldera protectors',
    good:{ text:'Collect five and work with the smelters to decode the forge process together.',
           alignment:+10, item:'iron_mandate',
           line:'"Five shards. Smelter analysis conducted jointly. The forge process is decoded and published. The Colossus can theoretically be replicated. The smelters name the process after the first smelter who decoded it. Zomb notes the naming convention."' },
    evil:{ text:'Five shards to Zomb. The forge process stays with the archive.',
           alignment:-12, item:'iron_curse',
           line:'"Five shards in Zomb\'s archive. Forge process decoded and archived exclusively. The Colossus cannot be replicated by anyone without the archive. One entity holds the key to Iron Age metallurgy. The entity is Zomb."' },
  },

  // ── ZOMB SURVIVAL (2) ────────────────────────────────────────────────────

  { id:'ia_z_s01', type:'survival', source:'zomb', age_min:2, cost:100, kill_count:5,
    offer:'"Archive approach — five entities approaching the mine entrance that conceals Zomb\'s primary Iron Age archive. They do not know what they are approaching. But they will find it if they proceed. Five entities. Stop them."',
    room:'iron_mines', monster:'iron_warrior', monster_label:'the archive approach',
    good:{ text:'Deflect them without violence. Redirect their path.',
           alignment:+8, item:'spirit_ash',
           line:'"Redirected without violence. They found a different section of the mine — which contained a sealed room they opened, which was not Zomb\'s archive but was old. Zomb notes: deflection sometimes creates its own discoveries."' },
    evil:{ text:'Stop all five. The archive is not found.',
           alignment:-13, item:'iron_curse',
           line:'"All five stopped. The archive is protected. Zomb notes the protection cost. Notes it specifically. The number of entities who now know an archive exists has increased by five."' },
  },

  { id:'ia_z_s02', type:'survival', source:'zomb', age_min:2, cost:95, kill_count:4,
    offer:'"Iron Fortress. Four consecutive knight patrols approaching a section of the fortress Zomb uses for observation. The observation post cannot be compromised. Four patrols. Manage them without pattern."',
    room:'iron_fortress', monster:'iron_knight', monster_label:'the fort patrol waves',
    good:{ text:'Manage the patrols without harming them — redirect each one.',
           alignment:+7, item:'iron_elixir',
           line:'"Four patrols redirected. No injuries. Observation post intact. Zomb notes: pattern-free redirection requires creativity. Creativity is not Zomb\'s strongest variable. The execution suggests otherwise."' },
    evil:{ text:'Stop four patrols by the most effective means.',
           alignment:-12, item:'iron_curse',
           line:'"Four patrols stopped. Observation post intact. The missing patrols triggered an investigation. The investigation found nothing because Zomb had anticipated it. Zomb planned four moves ahead. Zomb always plans four moves ahead."' },
  },

  // ── ZOMB COOPERATIVE (2) ─────────────────────────────────────────────────

  { id:'ia_z_co01', type:'cooperative', source:'zomb', age_min:2, cost:130, kill_count:1,
    offer:'"Iron Colossus. Zomb has observed four previous attempts. All failed solo. The Colossus was built to be a collective test. Zomb acknowledges this. Zomb is requesting collective action from specific entities. You are one of them."',
    room:'volcano_heart', monster:'iron_colossus', monster_label:'the Iron Colossus',
    good:{ text:'Fight together and split rewards equally. Honor the collective.',
           alignment:+20, item:'iron_mandate',
           line:'"Colossus falls. Collective honored. Zomb observes the fight closely. Collective action against a superior single entity succeeds at a rate Zomb had underestimated. Model updated. Substantially."' },
    evil:{ text:'Fight together. Claim first access to the Colossus\'s vault.',
           alignment:-15, item:'iron_curse',
           line:'"Colossus falls. First access claimed. The vault was accessed before collective distribution. The distribution that followed was smaller than it would have been. The team noted. Zomb noted the team noting."' },
  },

  { id:'ia_z_co02', type:'cooperative', source:'zomb', age_min:2, cost:115, kill_count:3,
    offer:'"Watchtower. Three iron sentinels have synchronized — a behavior Zomb has not observed before. Synchronized sentinels cannot be addressed individually. This requires multiple entities. Zomb is requesting specific entities. You are one."',
    room:'iron_watchtower', monster:'iron_sentinel', monster_label:'the synchronized sentinels',
    good:{ text:'Synchronize the team to match the sentinels\' pattern and disrupt it together.',
           alignment:+14, item:'iron_elixir',
           line:'"Synchronized team disrupted synchronized sentinels. The method used — matching the pattern to break it — is not a method Zomb had calculated. Zomb updates creativity as a collective variable. The update is significant."' },
    evil:{ text:'Break the synchronization through overwhelming simultaneous force.',
           alignment:-11, item:'iron_curse',
           line:'"Synchronization broken. All three sentinels addressed simultaneously. Effective. No creativity variable required — raw simultaneity sufficient. Zomb notes: some problems do not require elegance."' },
  },

  // ── ZOMB SABOTAGE (2) ────────────────────────────────────────────────────

  { id:'ia_z_sa01', type:'sabotage', source:'zomb', age_min:2, cost:100,
    offer:'"Iron Crossroads. The independent trade charter — the one that creates economic stability across faction lines. Stability creates conditions where the cycle slows. The charter\'s key provision requires a specific signatory. Remove the signatory\'s ability to sign."',
    room:'iron_crossroads', monster:'iron_warrior', monster_label:'the charter signatory guard',
    good:{ text:'Protect the signatory. The charter is worth protecting.',
           alignment:+18, item:'iron_mandate',
           line:'"Signatory protected. Charter signed. Economic stability across faction lines established. Zomb\'s conflict cycle slows significantly. Zomb observes twelve seasons of reduced conflict. Zomb notes: twelve seasons is twelve seasons. The weight of it is not nothing."' },
    evil:{ text:'Remove the signatory\'s ability to sign.',
           alignment:-18, item:'iron_curse',
           line:'"Charter unsigned. Economic stability fails to establish. Faction economic conflicts resume within one season. The cycle accelerates. Zomb\'s projection was accurate. Zomb notes accuracy and notes also: the accuracy was purchased at cost."' },
  },

  { id:'ia_z_sa02', type:'sabotage', source:'zomb', age_min:2, cost:95,
    offer:'"Battlefield. The medic post there provides care to both sides of the current conflict — making conflict less costly, extending it longer. Longer conflicts produce weaker endings. Disrupt the medic post\'s supply line."',
    room:'battlefield_scarred', monster:'iron_warrior', monster_label:'the supply line guard',
    good:{ text:'Protect the supply line. Medical care for both sides reduces suffering.',
           alignment:+15, item:'iron_elixir',
           line:'"Supply line protected. Medic post continues operating for both sides. Conflict becomes more costly — enough that both sides negotiate seriously within four seasons. Care produced the end faster than disruption would have. Zomb recalculates."' },
    evil:{ text:'Disrupt the supply line.',
           alignment:-16, item:'iron_curse',
           line:'"Supply line disrupted. Medic post degrades. Conflict becomes less costly to continue — both sides can sustain it longer. The war extends. Zomb\'s projection was wrong. Disrupting care extended the conflict rather than ending it. Error noted."' },
  },

  // ── ZOMB INVESTIGATION (1) ────────────────────────────────────────────────

  { id:'ia_z_i01', type:'investigation', source:'zomb', age_min:2, cost:90,
    offer:'"Volcano Heart. The original Colossus activation sequence — written in the caldera walls before the Iron Age began. Visible only when the caldera is at specific temperature. Find the sequence. Document it precisely."',
    room:'volcano_heart', monster:'iron_knight', monster_label:'the caldera guard',
    good:{ text:'Document and share the sequence — knowledge like this belongs to all.',
           alignment:+13, item:'iron_mandate',
           line:'"Sequence documented and shared. The activation process for the Colossus is now public. Three forge-masters say it contains implications beyond golem activation — hints at the mechanism of age transition itself. Lilly is very interested in this. Zomb notes Lilly\'s interest."' },
    evil:{ text:'Document the sequence for Zomb\'s archive exclusively.',
           alignment:-14, item:'iron_curse',
           line:'"Sequence in Zomb\'s archive exclusively. The activation process known to one entity. The age-transition implications unnoticed by everyone else. Zomb sits with the sequence for three days. The implications are significant. Zomb does not share them."' },
  },
];
