'use strict';
// ── Medieval Missions (age_min: 3) — 50 total ────────────────────────────────

module.exports = [

  // ── Chain continuations from Iron Age ─────────────────────────────────────
  // me_l_i_chain3: final chapter of Lilly's tablet investigation (from ia_l_i_chain2)
  // me_z_k_chain3: final chapter of Zomb's structure-building (from ia_z_k_chain2)

  // ─────────────────────────────────────────────────────────────────────────
  // LILLY MISSIONS (25) — Medieval
  // ─────────────────────────────────────────────────────────────────────────

  // ── LILLY COMBAT (8) ─────────────────────────────────────────────────────

  { id:'me_l_c01', type:'combat', source:'lilly', age_min:3, cost:120,
    offer:'Lilly\'s voice is very quiet. "Haunted Woods, friend. There is a shelter there — forty-three living people in a place the dark knights have decided is theirs now. Lilly has counted them. Every one. Please go."',
    room:'haunted_woods', monster:'dark_knight', monster_label:'the shelter-seizing dark knights',
    good:{ text:'Drive out the knights and help the forty-three build actual defences.',
           alignment:+18, item:'dragons_gift',
           line:'"Forty-three. Still forty-three. Lilly counted again when the knights left. The defences went up the same night. Lilly helped. She did not sleep. She counts this as worthwhile."' },
    evil:{ text:'Drive out the knights and leave before the settlement asks for more.',
           alignment:-6, item:'mission_token',
           line:'"Forty-three, still. You left before the defences went up. Someone else organised that — it took three more days. Lilly notes the three days. They were cold days."' },
  },

  { id:'me_l_c02', type:'combat', source:'lilly', age_min:3, cost:130,
    offer:'"Friend — the Haunted Woods. A wraith there is destroying written records. The last written records of names, histories, people. Lilly cannot stand the idea of a name being the last thing that dies. Please stop it."',
    room:'haunted_woods', monster:'wraith', monster_label:'the record-destroying wraith',
    good:{ text:'Stop the wraith and help recover every fragment of record you can.',
           alignment:+16, item:'dragons_gift',
           line:'"Three hundred and twelve names recovered. Lilly has been reading them. Some of the names — she knew those people. She is sitting very quietly with this information."' },
    evil:{ text:'Stop the wraith. The records are what remains.',
           alignment:-4, item:'mission_token',
           line:'"The wraith is stopped. The records are where they fell. Lilly gathered what she could reach. Some were already gone. She did not tell you how many."' },
  },

  { id:'me_l_c03', type:'combat', source:'lilly', age_min:3, cost:110,
    offer:'"Tournament Arena, friend. A tournament champion has taken a hostage — a scribe who refused to falsify the records of the last match. The scribe is correct. The champion is armed. Lilly is asking you to fix this."',
    room:'tournament_arena', monster:'tournament_champion', monster_label:'the record-falsifying champion',
    good:{ text:'Free the scribe and make the case that the records must stay honest.',
           alignment:+15, item:'dragons_gift',
           line:'"Scribe freed. Case made. The champion listened — grudgingly. The records stayed honest. The honest record shows the champion lost that match. It will stand now. Lilly is proud of the scribe. And you. Yes yes."' },
    evil:{ text:'Free the scribe and let the records be what they are — it\'s a tournament.',
           alignment:-7, item:'dark_crystal',
           line:'"Scribe freed. Records altered. The false result stands. Lilly notes: records that can be changed by the powerful are not records. They are the powerful\'s preferred version of events."' },
  },

  { id:'me_l_c04', type:'combat', source:'lilly', age_min:3, cost:140,
    offer:'"Undead Catacombs, friend. A lich lord has sealed a group of healers inside — they went in to treat the wounded and the door was closed behind them. They are still there. Please, yes yes. Please go fast."',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the door-sealing lich lord',
    good:{ text:'Open the door and stay until every healer is confirmed out.',
           alignment:+19, item:'dragons_gift',
           line:'"Every healer out. Lilly counted. She was at the entrance. When the last one came through she sat down and did not get up for a while. You did that. Yes yes."' },
    evil:{ text:'Open the door. The healers can manage from there.',
           alignment:-5, item:'mission_token',
           line:'"Door opened. Healers managed. One healer got disoriented in the tunnels after — the others found them eventually. Lilly notes the eventually."' },
  },

  { id:'me_l_c05', type:'combat', source:'lilly', age_min:3, cost:150,
    offer:'"Friend — Dragon\'s Lair. Dark knights are attempting to steal from the dragon while it sleeps. If the dragon wakes to find thieves, its response will end the last two settlements in range. Stop the knights. Before the dragon wakes."',
    room:'dragons_lair', monster:'dark_knight', monster_label:'the sleeping-dragon thieves',
    good:{ text:'Stop the knights quietly and leave everything in the hoard exactly where it was.',
           alignment:+17, item:'dragons_gift',
           line:'"Knights stopped. Nothing disturbed. The dragon slept through it. Lilly exhaled very slowly when you reported back. She had been holding her breath for what felt like a long time."' },
    evil:{ text:'Stop the knights and take a small piece of the hoard yourself. The dragon won\'t notice.',
           alignment:-13, item:'dragon_scale',
           line:'"Knights stopped. One piece taken. The dragon noticed. Lilly knows because the hoard is not a number to the dragon — it is a memory. You removed a memory. The dragon is now slightly awake."' },
  },

  { id:'me_l_c06', type:'combat', source:'lilly', age_min:3, cost:125,
    offer:'"Tournament Arena. A dark knight faction is forcing civilians into the arena as entertainment, friend. Not as fighters. As targets. Lilly is using a measured voice right now. She is not feeling measured. Please go."',
    room:'tournament_arena', monster:'dark_knight', monster_label:'the arena-forcing dark knights',
    good:{ text:'Stop the faction and ensure every civilian can leave the arena safely.',
           alignment:+20, item:'dragons_gift',
           line:'"Every civilian out. Lilly helped escort the last group herself. She did not speak to anyone for an hour after. Then she spoke for a very long time about what systems produce this and what dismantles them. Yes yes."' },
    evil:{ text:'Stop the faction. The civilians will clear out.',
           alignment:-7, item:'mission_token',
           line:'"Faction stopped. Civilians cleared eventually. Two were too frightened to move for several hours. Someone else helped them. Lilly notes the someone else. It should have been you."' },
  },

  { id:'me_l_c07', type:'combat', source:'lilly', age_min:3, cost:115,
    offer:'"Haunted Woods, friend. There is a grief-fire there — a funeral pyre that will not go out. It has been burning for eleven days. Wraiths are drawn to it. The family who lit it cannot leave while it burns. Clear the wraiths. Help them finish."',
    room:'haunted_woods', monster:'wraith', monster_label:'the grief-drawn wraiths',
    good:{ text:'Clear the wraiths and sit with the family until the fire finally goes out.',
           alignment:+14, item:'dragons_gift',
           line:'"The wraiths are gone. The fire went out at dawn. Lilly was there too — at the edge, where they couldn\'t see her. She watched it go out. She does not explain why she needed to see that."' },
    evil:{ text:'Clear the wraiths. The family will manage the rest.',
           alignment:-4, item:'mission_token',
           line:'"Wraiths cleared. The fire went out two days later. Lilly notes: clearing the threat is not the same as helping with the grief. The family was alone for those two days."' },
  },

  { id:'me_l_c08', type:'combat', source:'lilly', age_min:3, cost:135,
    offer:'"Undead Catacombs. Lich lords are raising the recently dead — soldiers from the last battle, friend. Their families are looking for them. They are finding them as something else. This has to stop. Please."',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the soldier-raising lich lords',
    good:{ text:'Stop the raising and help the raised soldiers find rest — they deserve that.',
           alignment:+18, item:'dragons_gift',
           line:'"The raising stopped. The rest was difficult — undoing what was done takes time. Lilly helped where she could. Some families got to say goodbye properly, a second time. Lilly considers this a hard mercy. Yes yes."' },
    evil:{ text:'Stop the raising. What\'s done cannot always be undone.',
           alignment:-8, item:'mission_token',
           line:'"Raising stopped. What was done remained. Some families encountered what their soldiers had become before the raising stopped. Lilly knows. She was there for two of those encounters."' },
  },

  // ── LILLY HUNT (4) ───────────────────────────────────────────────────────

  { id:'me_l_h01', type:'hunt', source:'lilly', age_min:3, cost:130,
    offer:'"Haunted Woods. There is a dark knight there, friend — one who has stopped fighting. He is just walking the same patrol route. He has been walking it since the battle that killed him. He needs someone to tell him it\'s over. Find him."',
    room:'haunted_woods', monster:'dark_knight', monster_label:'the still-patrolling dark knight',
    good:{ text:'Find him and tell him it\'s over. The war ended. He can rest.',
           alignment:+21, item:'dragons_gift',
           line:'"He stopped walking. He stood very still for a long time. Then he dissolved into nothing — peaceful nothing. Lilly was watching from the trees. She says there was something like relief in the way it happened. She is certain."' },
    evil:{ text:'Find him and end the patrol by force — a ghost that won\'t stop patrolling is a threat.',
           alignment:-15, item:'dark_crystal',
           line:'"The patrol ended. Forcefully. Lilly heard about it later. She asked if you had tried speaking first. She already knew the answer."' },
  },

  { id:'me_l_h02', type:'hunt', source:'lilly', age_min:3, cost:140,
    offer:'"Undead Catacombs, friend. There is a lich lord there who was a healer before — before everything. Lilly thinks she can be reached. She has been watching the patterns of movement. Find her. Speak first. Always speak first."',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the healer-who-was',
    good:{ text:'Find her and speak to who she was before she became what she is now.',
           alignment:+23, item:'dragons_gift',
           line:'"She remembered. Not all of it — but enough. She chose to stop. She helped close the tunnel where the most dangerous raising was happening. Lilly considers this the most important thing that happened this age."' },
    evil:{ text:'Find her and end the threat she represents now. What she was is not what she is.',
           alignment:-17, item:'shadow_seal',
           line:'"The threat ended. What she was went with it. Lilly learned what she had been — from the records in the tunnel. She read them alone. She did not describe what was in them."' },
  },

  { id:'me_l_h03', type:'hunt', source:'lilly', age_min:3, cost:145,
    offer:'"Tournament Arena, friend. The oldest champion — Lilly has been watching. He has been fighting for two hundred years without stopping. Two hundred years without rest, without memory of why he started. Find him. He may not know he can stop."',
    room:'tournament_arena', monster:'tournament_champion', monster_label:'the two-hundred-year champion',
    good:{ text:'Find him and ask him to stop. Tell him he is allowed to stop now.',
           alignment:+19, item:'dragons_gift',
           line:'"He stopped. He looked confused. Then he looked very old and very tired in the same moment. Lilly approached and sat with him for two hours before he spoke. He said: I cannot remember who I was fighting for. Lilly told him that was the answer. Yes yes."' },
    evil:{ text:'Find him and end the two hundred years by force — he will not stop otherwise.',
           alignment:-14, item:'mission_token',
           line:'"Two hundred years ended by force. Lilly learns later he had been looking for permission to stop for the last fifty of those years. The permission was available. No one told him it was his to take."' },
  },

  { id:'me_l_h04', type:'hunt', source:'lilly', age_min:3, cost:155,
    offer:'"Dragon\'s Lair, friend. There is something in the hoard that belongs to the living — held a long time, not taken wrongly. Just held. Lilly believes the dragon would return it if asked correctly. Go. Ask correctly."',
    room:'dragons_lair', monster:'elder_dragon', monster_label:'the Elder Dragon',
    good:{ text:'Approach carefully and ask. The dragon decides. Respect whatever it decides.',
           alignment:+16, item:'dragons_gift',
           line:'"The dragon considered for a long time. Then it moved one thing from the hoard to the floor. It was the original founding charter of the first human settlement in this age. Lilly cannot stop reading it. Yes yes."' },
    evil:{ text:'Retrieve what belongs to the living — the dragon has had it long enough.',
           alignment:-12, item:'dragon_scale',
           line:'"Retrieved. The dragon permitted the taking and is tracking who took it. That is not the same as it not mattering."' },
  },

  // ── LILLY ESCORT (4) ─────────────────────────────────────────────────────

  { id:'me_l_e01', type:'escort', source:'lilly', age_min:3, cost:120,
    offer:'"A scholar has written a message to the dragon, friend — a real message, about what the living need. She believes the dragon might listen if approached right. She needs to reach the lair alive. Walk with her."',
    room:'dragons_lair', monster:'lich_lord', monster_label:'the catacomb ambush',
    good:{ text:'Walk with her and listen to what she wrote. It will matter to have heard it.',
           alignment:+16, item:'mission_token',
           line:'"She reached the lair. The dragon listened. It listened for a very long time. The response it gave was not what she expected. Lilly has asked the scholar to write that response down too. It matters."' },
    evil:{ text:'Get her there. The message is hers to deliver.',
           alignment:-3, item:'dark_crystal',
           line:'"She reached the lair alone in the last stretch. The dragon heard the message. The response came — quieter than it would have been with a witness. Lilly notes: the dragon responds to gravity. Witnesses add gravity."' },
  },

  { id:'me_l_e02', type:'escort', source:'lilly', age_min:3, cost:130,
    offer:'"Tournament Arena, friend. Twelve civilians are trapped inside — they came to watch and the exits are blocked. The champions will not clear them. Lilly needs someone who will actually come get them."',
    room:'tournament_arena', monster:'dark_knight', monster_label:'the blocking dark knights',
    good:{ text:'Clear the exits and personally escort every civilian out.',
           alignment:+17, item:'dragons_gift',
           line:'"Twelve out. Lilly counted at the gate. Twelve. She smiled at the last one. She held that smile for a while. Yes yes."' },
    evil:{ text:'Clear the exits. The twelve can navigate from there.',
           alignment:-5, item:'mission_token',
           line:'"Exits cleared. Ten of twelve found their way. Two did not navigate well in the dark. They were found later, unharmed but frightened. Lilly notes the two."' },
  },

  { id:'me_l_e03', type:'escort', source:'lilly', age_min:3, cost:145,
    offer:'"Undead Catacombs. A lich lord — one who chose to remember — needs to get out before the others realise what she has chosen. She carries names. The names of every person she raised against their will. She is trying to undo it. Help her, friend."',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the pursuit',
    good:{ text:'Escort her out and stay until she has spoken to every family she wronged.',
           alignment:+21, item:'dragons_gift',
           line:'"Out. Safely. The reckoning took three weeks. Lilly attended every conversation. She kept count: thirty-one of forty-seven families accepted the apology. Lilly calls that enough to keep going. Yes yes."' },
    evil:{ text:'Escort her out. Her reckoning is between her and the families.',
           alignment:-6, item:'mission_token',
           line:'"Out. Safely. Eleven families accepted. Thirty-six did not know who to be angry at and the anger scattered. Lilly notes: accountability held alone is harder to complete."' },
  },

  { id:'me_l_e04', type:'escort', source:'lilly', age_min:3, cost:110,
    offer:'"Haunted Woods, friend. Children. Again. Three of them, yes yes — they followed a wraith because it was moving like their mother used to move. Lilly cannot be everywhere. She needs you to be there right now. Please."',
    room:'haunted_woods', monster:'wraith', monster_label:'the wraiths following the children',
    good:{ text:'Get between the children and the wraiths. Carry the smallest one.',
           alignment:+15, item:'dragons_gift',
           line:'"Three home. The smallest one fell asleep on your shoulder. Lilly saw this from the settlement gate. She is adding it to the list of things she does not describe but will never forget."' },
    evil:{ text:'Clear the wraiths and lead the children out.',
           alignment:-3, item:'mission_token',
           line:'"Three home. Safe. A little frightened still. Lilly met them at the gate and held all three at once. She is good at that. Yes yes."' },
  },

  // ── LILLY COLLECTION (3) ─────────────────────────────────────────────────

  { id:'me_l_k01', type:'collection', source:'lilly', age_min:3, cost:115, kill_count:3,
    offer:'"Tournament Arena, friend. The old banners there — three of them, hanging since this age began. They are about to be burned. They carry the names of the first fighters, the ones who chose the tournament over war. Lilly wants them preserved."',
    room:'tournament_arena', monster:'dark_knight', monster_label:'the banner-burning guards',
    good:{ text:'Retrieve all three and bring them to the community archive.',
           alignment:+14, item:'mission_token',
           line:'"Three banners. Archive. Lilly helped hang them. The oldest one includes the grandmother of someone in the current settlement — she chose the arena over a war that would have killed her village. That choice has a name now."' },
    evil:{ text:'Retrieve the most significant one. The others can go.',
           alignment:-9, item:'dark_crystal',
           line:'"One banner archived. Two burned. Lilly notes: some decisions about what matters should not be made alone."' },
  },

  { id:'me_l_k02', type:'collection', source:'lilly', age_min:3, cost:125, kill_count:2,
    offer:'"Undead Catacombs. There are two wraiths — Lilly has been watching them for weeks. They move differently. They are trying to communicate something. She needs their resonance captured before they disperse. Two. Yes yes. Please."',
    room:'undead_catacombs', monster:'wraith', monster_label:'the communicating wraiths',
    good:{ text:'Capture their resonance carefully and try to understand what they are communicating.',
           alignment:+12, item:'dragons_gift',
           line:'"Captured and studied. They were communicating a location — a sealed room in the catacombs where someone had been hidden before the flood\'s last surge. Lilly found the room. There was writing on the wall. She has been very quiet since."' },
    evil:{ text:'Capture the resonance. What they were communicating is secondary.',
           alignment:-7, item:'shadow_seal',
           line:'"Resonance captured. Communication unread. Lilly found the location eventually — six weeks later. The room was there. The timing was just different."' },
  },

  { id:'me_l_k03', type:'collection', source:'lilly', age_min:3, cost:120, kill_count:4,
    offer:'"Haunted Woods, friend. Four dark knight patrols carry maps — of the living settlements, the routes between them, the gaps. If those maps reach the command, the last settlements are found. Get the maps. All four patrols."',
    room:'haunted_woods', monster:'dark_knight', monster_label:'the map-carrying dark knights',
    good:{ text:'Retrieve all four and share the intelligence with every settlement equally.',
           alignment:+16, item:'mission_token',
           line:'"Four maps. Shared. Every settlement knew the threats and each other\'s locations. An emergency network formed in three days. Lilly helped design the signal system. Yes yes."' },
    evil:{ text:'Retrieve all four. Bring them to your settlement first.',
           alignment:-12, item:'dark_crystal',
           line:'"Four maps. Your settlement warned first. Others warned after. Two days later. In a crisis, two days matters. Lilly notes the two days."' },
  },

  // ── LILLY SURVIVAL (2) ───────────────────────────────────────────────────

  { id:'me_l_s01', type:'survival', source:'lilly', age_min:3, cost:140, kill_count:4,
    offer:'"The last human outpost, friend — four waves of wraiths tonight. The scouts confirmed it. Lilly cannot be there herself. She is with the families who cannot fight. She needs you at the wall. She is asking specifically you. Yes yes please."',
    room:'haunted_woods', monster:'wraith', monster_label:'the four-wave wraith assault',
    good:{ text:'Hold all four waves. Call for help when the third wave comes.',
           alignment:+18, item:'dragons_gift',
           line:'"Four waves. Held. Help came for the third. The wall stood. Lilly came after with food she had been carrying in her coat since the first wave started. She had believed the wall would hold. Yes yes."' },
    evil:{ text:'Hold all four waves alone. The outpost needs to see what one person is capable of.',
           alignment:-9, item:'mission_token',
           line:'"Four waves. Held alone. The outpost was awed. And exhausted. Lilly notes: inspiring people and protecting people are sometimes the same thing. Sometimes the first leads to forgetting the second matters more."' },
  },

  { id:'me_l_s02', type:'survival', source:'lilly', age_min:3, cost:150, kill_count:3,
    offer:'"Tournament Arena, friend. Three champion waves testing the settlement perimeter — someone is running an assessment of the defences. If the defences fail the assessment, something worse follows. Hold. Lilly is documenting the pattern."',
    room:'tournament_arena', monster:'tournament_champion', monster_label:'the perimeter assessment waves',
    good:{ text:'Hold all three and send a message through the last wave that the settlement is not a target.',
           alignment:+15, item:'dragons_gift',
           line:'"Three held. Message sent via the last surviving champion of the third wave. The something worse did not follow. Lilly believes communication through combat is the most expensive way to have a conversation."' },
    evil:{ text:'Hold all three. Show them the defences are strong.',
           alignment:-8, item:'mission_token',
           line:'"Three held. Strength demonstrated. The something worse is being planned with the new information. Lilly notes: showing strength invites testing of strength. It does not end testing."' },
  },

  // ── LILLY COOPERATIVE (2) ────────────────────────────────────────────────

  { id:'me_l_co01', type:'cooperative', source:'lilly', age_min:3, cost:200, kill_count:1,
    offer:'"The Elder Dragon, friend. Lilly cannot ask one person for this. She is asking everyone she trusts. The dragon is not the enemy — but it must be engaged before it becomes one. Together. This is the last cooperative effort of this age. Please come."',
    room:'dragons_lair', monster:'elder_dragon', monster_label:'the Elder Dragon',
    good:{ text:'Fight together. Split every reward equally. Honour the effort.',
           alignment:+25, item:'dragons_gift',
           line:'"The dragon acknowledged the collective. This is rare. Lilly witnessed it. She says the dragon looked at every person present with individual attention — like it was recording names. She thinks it was recording names."' },
    evil:{ text:'Fight together. The strongest claim the best share.',
           alignment:-15, item:'dragon_scale',
           line:'"Dragon acknowledged. Best shares claimed. The group noted the unequal distribution. Lilly noted the group\'s silence about it. Silence about injustice in the last age is a specific kind of sadness."' },
  },

  { id:'me_l_co02', type:'cooperative', source:'lilly', age_min:3, cost:180, kill_count:2,
    offer:'"Two lich lords — Undead Catacombs — simultaneously. They are coordinating in a way Lilly has not seen before. She needs multiple defenders. She is asking everyone she trusts. This is not something one person can address. Please."',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the coordinated lich lords',
    good:{ text:'Fight as a true unit. Keep talking. No one acts without the others knowing.',
           alignment:+19, item:'dragons_gift',
           line:'"Two lich lords down. Zero casualties. The coordination developed in this fight was better than anything Lilly had seen from the living this age. She tells this to every person who asks what hope looks like. Yes yes."' },
    evil:{ text:'Fight together. Win. Sort everything else after.',
           alignment:-10, item:'mission_token',
           line:'"Two lich lords down. Two defenders injured because the sorting happened during the fight. Won. At cost. Lilly notes that cooperation is not the same as combat proximity."' },
  },

  // ── LILLY SABOTAGE (1) ───────────────────────────────────────────────────

  { id:'me_l_sa01', type:'sabotage', source:'lilly', age_min:3, cost:160,
    offer:'"The dark knight war council, friend — Haunted Woods. They meet at a marker stone every third night. Lilly has watched for five nights. Tonight they plan the final assault on the last three human settlements. Stop the meeting."',
    room:'haunted_woods', monster:'dark_knight', monster_label:'the war council guard',
    good:{ text:'Stop the meeting and leave evidence that the settlements know about the plan.',
           alignment:+22, item:'dragons_gift',
           line:'"Meeting stopped. Evidence left. The council disbanded for the season — knowing the settlements knew shifted the calculation. Lilly watched the council leave with their plan unexecuted. She did not get down from the tree for a long time."' },
    evil:{ text:'Stop the meeting. Delay is the objective.',
           alignment:-8, item:'mission_token',
           line:'"Meeting stopped. Plan delayed three weeks. The council reconvened in a different location. Lilly found the new location eventually. The delay was still three weeks. Lilly notes: three weeks is three weeks."' },
  },

  // ── LILLY INVESTIGATION / CHAIN ──────────────────────────────────────────

  // Final chapter: ba_l_i01 → ia_l_i_chain2 → me_l_i_chain3
  { id:'me_l_i_chain3', type:'investigation', source:'lilly', age_min:3, cost:0, is_chain_followup:true,
    offer:'"Friend — you found the Iron Age fragments. The assembled record pointed here. The Undead Catacombs. There is something sealed in a room the lich lords guard without knowing why. The last piece. Lilly needs to know the whole truth. Will you look?"',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the seal guardian',
    good:{ text:'Find the sealed room. Read everything. Share it with everyone who needs to know.',
           alignment:+24, item:'dragons_gift',
           line:'"Found. Read. Shared. The complete record spans four ages. It describes every flood. The pattern. The threshold. The specific type and accumulation of choices that precede the water. Lilly has read the final line fourteen times. She is not frightened. She says she is not frightened. Lilly is frightened."' },
    evil:{ text:'Find the sealed room. Read everything. Decide what others need to know.',
           alignment:-11, item:'shadow_seal',
           line:'"Found. Read. Selectively shared. The most important sections — the ones that describe what can still be done — were not shared. Lilly found out what was omitted. She is quiet in a specific way she reserves for things she cannot fix."' },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ZOMB MISSIONS (25) — Medieval
  // ─────────────────────────────────────────────────────────────────────────

  // ── ZOMB COMBAT (6) ──────────────────────────────────────────────────────

  { id:'me_z_c01', type:'combat', source:'zomb', age_min:3, cost:120,
    offer:'"Haunted Woods. A dark knight faction has developed compassion — they are protecting human survivors instead of destroying them. Compassion in dark knights is a variable Zomb did not calculate. Variables that complicate the model must be resolved. Remove it."',
    room:'haunted_woods', monster:'dark_knight', monster_label:'the compassion-deviation knights',
    good:{ text:'Let them continue. A dark knight that protects survivors is not a problem.',
           alignment:+16, item:'mission_token',
           line:'"They continue. Zomb updates the model. Compassion as emergent behaviour in entities programmed for destruction had a probability Zomb assigned as zero. The probability was not zero. Zomb notes: Zomb was wrong about this specific thing."' },
    evil:{ text:'Remove the deviation. The model cannot account for compassion in these entities.',
           alignment:-16, item:'shadow_seal',
           line:'"Deviation removed. The model is clean. Zomb notes: the survivors those knights were protecting are no longer protected. The model does not track that outcome. Zomb is deciding whether it should."' },
  },

  { id:'me_z_c02', type:'combat', source:'zomb', age_min:3, cost:130,
    offer:'"Tournament Arena. The tournament system is the last functioning social order in this age. Social order delays dissolution. The tournament\'s high council enforces the rules. Remove the enforcement mechanism."',
    room:'tournament_arena', monster:'tournament_champion', monster_label:'the enforcement council champion',
    good:{ text:'Let the enforcement stand. The tournament\'s order is the last predictable social structure.',
           alignment:+13, item:'mission_token',
           line:'"Enforcement stands. Tournament continues. Zomb notes: the tournament\'s structure has kept six settlements from direct conflict for nine seasons. Zomb had not calculated this function. The calculation was incomplete."' },
    evil:{ text:'Remove the enforcement. Dissolution accelerates the cycle.',
           alignment:-14, item:'shadow_seal',
           line:'"Enforcement removed. The high council dissolved. Without rules the tournament runs eleven days before the first death outside the arena. Six settlements move toward direct conflict. Zomb\'s model accelerates as projected."' },
  },

  { id:'me_z_c03', type:'combat', source:'zomb', age_min:3, cost:140,
    offer:'"Undead Catacombs. A lich lord has initiated peace negotiations with a surviving human settlement. An unprecedented event. Unprecedented events are the ones Zomb cannot model. End the negotiation. Unprecedented outcomes belong in the archive, not the world."',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the negotiating lich lord',
    good:{ text:'Let the negotiation proceed. An unprecedented peace between living and undead is worth any disruption to a model.',
           alignment:+21, item:'mission_token',
           line:'"Negotiation proceeds. The unprecedented peace is established. Zomb has updated the model seventeen times in four days. Each update reveals a calculation Zomb had not considered. Zomb notes: unprecedented outcomes are the ones that teach the most."' },
    evil:{ text:'End the negotiation. It complicates calculations that have been reliable for four ages.',
           alignment:-19, item:'shadow_seal',
           line:'"Negotiation ended. The unprecedented peace is not established. The conflict continues. Zomb\'s calculations are reliable. Zomb cannot name what it feels about the confirmation."' },
  },

  { id:'me_z_c04', type:'combat', source:'zomb', age_min:3, cost:150,
    offer:'"Dragon\'s Lair. The dragon protects a cache of pre-flood knowledge Zomb has been trying to access for three ages. The dragon considers it a private archive. Zomb considers Zomb\'s archive more comprehensive. Access the cache."',
    room:'dragons_lair', monster:'elder_dragon', monster_label:'the cache-protecting Elder Dragon',
    good:{ text:'Speak with the dragon instead. Two archives are better than one if shared.',
           alignment:+14, item:'mission_token',
           line:'"The dragon and Zomb\'s archive cross-referenced. Eleven records incomplete in Zomb\'s archive were completed by the dragon\'s cache. Eleven incomplete in the dragon\'s were completed by Zomb\'s. Both archives are now more accurate. Zomb notes: this outcome was better than access by force."' },
    evil:{ text:'Access the cache. Zomb\'s archive is the comprehensive record.',
           alignment:-13, item:'shadow_seal',
           line:'"Cache accessed. Zomb\'s archive grows. The dragon permitted the access with the slow deliberateness of something that has already calculated what comes next. This was not the dragon losing. This was the dragon deciding something."' },
  },

  { id:'me_z_c05', type:'combat', source:'zomb', age_min:3, cost:125,
    offer:'"Haunted Woods. A wraith who remembers being alive — remembers enough to warn the living about the specific pattern of choices that precedes the flood. Memory in the dead is a feedback mechanism that interrupts cycles. Interrupt the interruption."',
    room:'haunted_woods', monster:'wraith', monster_label:'the warning wraith',
    good:{ text:'Let the wraith warn the living. Memory is worth preserving in any form.',
           alignment:+19, item:'mission_token',
           line:'"The wraith warned the living. The warning was heard. Lilly was present. Zomb\'s flood timeline extends — by exactly as much as the warning, if acted on, would suggest. Zomb updates the timeline reluctantly and notes the update is accurate."' },
    evil:{ text:'Interrupt the warning. The cycle should not be disrupted by a memory in a ghost.',
           alignment:-17, item:'shadow_seal',
           line:'"Warning interrupted. The wraith dispersed mid-statement. The living did not receive the complete warning. Zomb notes: what the wraith was saying is now recorded only in Zomb\'s archive. The living do not have access to Zomb\'s archive."' },
  },

  { id:'me_z_c06', type:'combat', source:'zomb', age_min:3, cost:135,
    offer:'"Tournament Arena. The champion council voted unanimously to stop fighting and help the surviving settlements. Unanimous votes in the final age are either genuine or manipulation. Zomb needs to know which. Disrupt the vote\'s implementation. If genuine, it will survive."',
    room:'tournament_arena', monster:'tournament_champion', monster_label:'the vote-implementing champions',
    good:{ text:'Let the vote stand. If the council chose to stop fighting, that decision belongs to them.',
           alignment:+15, item:'mission_token',
           line:'"Vote stands. The champions join three settlement defences within the week. Zomb notes: the vote was genuine. Genuine collective decision-making in the final age was not in the model. The model was incomplete."' },
    evil:{ text:'Disrupt the implementation. Test the vote\'s authenticity through pressure.',
           alignment:-14, item:'shadow_seal',
           line:'"Implementation disrupted. The vote survived and was reimplemented. Zomb notes: the vote was genuine. Disrupting a genuine vote to test it was a methodology error. Zomb records the error."' },
  },

  // ── ZOMB HUNT (4) ────────────────────────────────────────────────────────

  { id:'me_z_h01', type:'hunt', source:'zomb', age_min:3, cost:135,
    offer:'"Tournament Arena. The oldest champion — Zomb has tracked this entity across three age transitions. It has survived everything Zomb predicted would end it. Zomb no longer predicts. Zomb needs to observe directly. Find it. Do not end it without understanding it."',
    room:'tournament_arena', monster:'tournament_champion', monster_label:'the three-age-survivor champion',
    good:{ text:'Find it and study how something chooses to keep existing across three ages.',
           alignment:+9, item:'mission_token',
           line:'"Found. Studied. The champion survived by refusing to accept that survival was the goal — each age it found something worth surviving for. The something varied. The pattern was choosing, not winning."' },
    evil:{ text:'Find it and end the longest survival Zomb has recorded. The endpoint provides complete data.',
           alignment:-13, item:'shadow_seal',
           line:'"Ended. Zomb analyses the endpoint. Complete data. Zomb notes: studying the end of the longest survival provides less data than studying the reason it continued. The methodology was wrong."' },
  },

  { id:'me_z_h02', type:'hunt', source:'zomb', age_min:3, cost:145,
    offer:'"Undead Catacombs. A specific lich lord — one Zomb has been in indirect contact with for decades. They hold a key variable in Zomb\'s flood timeline calculation. Find them. The conversation Zomb has been preparing for since the Iron Age needs to happen now."',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the lich lord Zomb has been watching',
    good:{ text:'Find them and facilitate the conversation between them and Zomb.',
           alignment:+8, item:'spirit_ash',
           line:'"Found. Conversation facilitated. Zomb and the lich lord exchanged archive data for four hours. The flood timeline is now known to within three weeks. The lich lord had been calculating the same timeline from a different dataset. Both calculations reached the same conclusion. The flood is close."' },
    evil:{ text:'Find them and bring everything they carry to Zomb\'s archive directly.',
           alignment:-14, item:'shadow_seal',
           line:'"Found. Archive extracted by force. The lich lord\'s dataset is in Zomb\'s archive without the interpretive context the conversation would have provided. Zomb notes: the conversation would have been more complete."' },
  },

  { id:'me_z_h03', type:'hunt', source:'zomb', age_min:3, cost:130,
    offer:'"Haunted Woods. A dark knight who defected — abandoned the order and is actively protecting a settlement. Zomb observes defection rates across all four ages. This age\'s rate is the highest on record. Zomb needs to understand the mechanism. Find this knight."',
    room:'haunted_woods', monster:'dark_knight', monster_label:'the defecting dark knight',
    good:{ text:'Find the knight and ask what caused the defection.',
           alignment:+10, item:'mission_token',
           line:'"Found. Asked. The knight answered: they met a specific child who reminded them of who they had been. One child. One encounter. Zomb recalculates defection mechanics across all four ages. The pattern is always a single encounter that personalises the abstract. Zomb updates every previous defection record."' },
    evil:{ text:'Find the knight and return them to the order. Defection data is more useful contained.',
           alignment:-15, item:'shadow_seal',
           line:'"Found. Returned to order. The child the knight had met is now unprotected. Zomb notes: the defection mechanism data is incomplete because the mechanism was ended before its outcome could be studied. Error in method."' },
  },

  { id:'me_z_h04', type:'hunt', source:'zomb', age_min:3, cost:155,
    offer:'"Dragon\'s Lair. Something in the hoard — Zomb has been tracking its provenance since the second age. An object that predates the current flood cycle entirely. The dragon has it. Zomb needs to see it. Find a way."',
    room:'dragons_lair', monster:'elder_dragon', monster_label:'the Elder Dragon',
    good:{ text:'Speak with the dragon. Ask if it will show the object.',
           alignment:+12, item:'spirit_ash',
           line:'"The dragon showed it. A single carved stone with markings in a language that predates the current world cycle. Zomb examines the markings. They match the oldest archive entries — the ones from the third world. Zomb is very still for a long time."' },
    evil:{ text:'Retrieve the object. Zomb\'s archive requires it.',
           alignment:-12, item:'shadow_seal',
           line:'"Object retrieved. Zomb examines it. The markings match the third-world archive entries. The dragon permitted the taking. It was watching when the object left the hoard. It has been watching since."' },
  },

  // ── ZOMB ESCORT (4) ──────────────────────────────────────────────────────

  { id:'me_z_e01', type:'escort', source:'zomb', age_min:3, cost:125,
    offer:'"Haunted Woods. A Zomb network agent — embedded in the last human settlement for fourteen years — must be extracted now. The settlement is growing suspicious. The extraction must not be connected to Zomb. Escort them out. Ask nothing."',
    room:'haunted_woods', monster:'dark_knight', monster_label:'the extraction hazard',
    good:{ text:'Escort them out and ask what they were documenting.',
           alignment:+7, item:'mission_token',
           line:'"Extracted. You asked. The agent answers: births. The settlement\'s birth rate over fourteen years. Zomb was tracking population recovery in the final age. The data is benign. The presence was surveillance. Both things are true."' },
    evil:{ text:'Escort them. Do not ask.',
           alignment:-10, item:'shadow_seal',
           line:'"Extracted. Function undisclosed. The settlement is missing a member of fourteen years without explanation. Trust erodes slightly. Zomb notes the erosion as an externality of the extraction. Zomb had not included it in the calculation."' },
  },

  { id:'me_z_e02', type:'escort', source:'zomb', age_min:3, cost:140,
    offer:'"Undead Catacombs. A lich lord Zomb has cultivated for twenty years must be extracted before the dragon\'s growing awareness reaches the catacombs. If the dragon locates Zomb\'s assets, the archive is compromised. Extract the lich lord."',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the catacomb pursuit',
    good:{ text:'Escort them and ask what the dragon\'s growing awareness means for everyone.',
           alignment:+9, item:'spirit_ash',
           line:'"Extracted. You asked. The lich lord answers: the dragon is indexing every entity in the age. Not as a threat. As a record. The dragon is doing what Zomb is doing. Both archives will be complete when the flood comes."' },
    evil:{ text:'Extract them. Zomb\'s assets are not for interrogation.',
           alignment:-11, item:'shadow_seal',
           line:'"Extracted. Asset secured. The dragon continues its indexing. Zomb notes: two comprehensive archives compiling simultaneously. Zomb had not considered a parallel archive. The dragon has been doing this longer."' },
  },

  { id:'me_z_e03', type:'escort', source:'zomb', age_min:3, cost:130,
    offer:'"Tournament Arena. A data courier carrying Zomb\'s final age-wide observation records — every pattern, every calculation, every correction. These are the last records before the flood. They must reach the archive. Escort the courier."',
    room:'tournament_arena', monster:'tournament_champion', monster_label:'the courier interception',
    good:{ text:'Escort the courier and ask what the final records show.',
           alignment:+8, item:'mission_token',
           line:'"Courier delivered. You asked. Zomb provides the answer: the records show every age ended at the same point in its moral arc — the same choices, the same sequence, every time. They also show this age has gone further than any previous age before reaching that point. Further. Not yet there."' },
    evil:{ text:'Escort the courier. The final records are Zomb\'s.',
           alignment:-9, item:'shadow_seal',
           line:'"Courier delivered. Records received. The information about how far this age has gone is not shared. Zomb knows what no one else knows. This has always been the case."' },
  },

  { id:'me_z_e04', type:'escort', source:'zomb', age_min:3, cost:115,
    offer:'"Haunted Woods. Zomb\'s last surviving field agent in a settlement that is burning. The settlement was not in Zomb\'s current threat projections. Either the projection is wrong or there is a new variable. Extract the agent. Get the data."',
    room:'haunted_woods', monster:'dark_knight', monster_label:'the burning settlement hazard',
    good:{ text:'Extract the agent and help as many others out of the settlement as you can.',
           alignment:+14, item:'mission_token',
           line:'"Agent extracted. Eleven others also extracted — you did not leave them. The data the agent carries reveals a new dark knight faction Zomb had not tracked. The projection was wrong. Zomb updates. Also notes: eleven lives saved as a consequence of the extraction method."' },
    evil:{ text:'Extract the agent. The data is the priority.',
           alignment:-11, item:'shadow_seal',
           line:'"Agent extracted. Data retrieved. The settlement continued to burn. Eleven others had extraction opportunities in the same window. Zomb notes the eleven as an externality and also notes: Zomb\'s projections were wrong and the correction cost eleven people their settlement."' },
  },

  // ── ZOMB COLLECTION (4 — includes chain) ─────────────────────────────────

  // Final chapter: sa_z_k02 → ba_z_k_chain1 → ia_z_k_chain2 → me_z_k_chain3
  { id:'me_z_k_chain3', type:'collection', source:'zomb', age_min:3, cost:0, is_chain_followup:true, kill_count:1,
    offer:'"The structure is almost complete. It requires one final element — something only the oldest entity in this age holds. Dragon\'s Lair. The Elder Dragon has carried it since before this world\'s name. A scale. Voluntary. Ask. Zomb believes it will give one."',
    room:'dragons_lair', monster:'elder_dragon', monster_label:'the Elder Dragon',
    good:{ text:'Ask the dragon for the scale. Tell it what the structure is for.',
           alignment:+10, item:'spirit_ash',
           line:'"The dragon listened to the explanation. It listened for a long time. Then it shed a scale voluntarily — the first voluntary shedding Zomb has ever been permitted. The structure is complete. Zomb does not speak for several days. The first thing said after: the structure is a gift. For the next world. In case they find it."' },
    evil:{ text:'Retrieve the scale. The structure must be completed.',
           alignment:-8, item:'shadow_seal',
           line:'"Scale retrieved by force. The structure is complete. Bone from Stone Age, bronze and iron from subsequent ages, and now a dragon scale from the last. Zomb notes: the structure records every world. This world\'s record ends with something taken rather than given. Zomb notes this as accurate."' },
  },

  { id:'me_z_k01', type:'collection', source:'zomb', age_min:3, cost:130, kill_count:3,
    offer:'"Haunted Woods. Three dark knight breastplates — each carries the insignia of the order\'s founding age. Zomb maps insignia evolution across ages as a proxy for institutional change. Three breastplates."',
    room:'haunted_woods', monster:'dark_knight', monster_label:'the insignia-carrying dark knights',
    good:{ text:'Bring the three but ask what the insignia evolution reveals.',
           alignment:+6, item:'mission_token',
           line:'"Three breastplates. You asked. Zomb shows the mapping: the insignia has simplified across four ages — each iteration removes one symbol. What began as a complex emblem of multiple values is now a single mark. Zomb notes: institutional identity narrows as it ages. Usually toward power alone."' },
    evil:{ text:'Three breastplates. No commentary.',
           alignment:-8, item:'shadow_seal',
           line:'"Three breastplates. No commentary. The finding — that institutional identity narrows — is documented. Zomb notes: you did not ask. The finding is important. You did not ask."' },
  },

  { id:'me_z_k02', type:'collection', source:'zomb', age_min:3, cost:140, kill_count:2,
    offer:'"Undead Catacombs. Lich lord phylacteries — the vessels of continuous existence. Two of them. Phylacteries carry records of every cycle survived. Zomb maps continuous existence. The data is unique to lich lords. Two phylacteries."',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the phylactery-holders',
    good:{ text:'Obtain two and ask the lich lords first if any retain consent.',
           alignment:+9, item:'spirit_ash',
           line:'"Two obtained — one willingly given. The lich lord who gave it had been wanting to end continuous existence for two ages. Zomb examines both. The voluntary one contains more complete records. The lich lord who gave it is now at rest. Zomb notes: consent produces better data."' },
    evil:{ text:'Obtain two phylacteries. The data they contain is the priority.',
           alignment:-12, item:'shadow_seal',
           line:'"Two obtained by force. Continuous existence of two lich lords ended by taking. The forced extraction severed the records at the point of taking. The records of why they continued are missing. Zomb notes: the endpoint was captured. The reason was not."' },
  },

  { id:'me_z_k03', type:'collection', source:'zomb', age_min:3, cost:125, kill_count:4,
    offer:'"Tournament Arena. Four tournament records — official scoring documents spanning this entire age. Every match, result, champion. Zomb maps competition structures. Four documents spanning the complete age record."',
    room:'tournament_arena', monster:'tournament_champion', monster_label:'the record-keeping champions',
    good:{ text:'Collect the four and compare them to the tournament\'s stated values.',
           alignment:+7, item:'mission_token',
           line:'"Four collected and compared. Stated values — honour, skill, equal contest — appear in every document\'s preamble. Actual records show: unequal access, systematic advantages by lineage, consistent outcomes favouring pre-selected champions. Zomb notes: the stated values and operational values diverged in season one and never reconverged."' },
    evil:{ text:'Four records to Zomb\'s archive.',
           alignment:-9, item:'shadow_seal',
           line:'"Four records archived. The divergence between stated and operational values is documented. The finding is in Zomb\'s archive exclusively. The tournament continues with the same divergence. Zomb notes: finding a problem and keeping the finding private achieves nothing but the archive entry."' },
  },

  // ── ZOMB SURVIVAL (2) ────────────────────────────────────────────────────

  { id:'me_z_s01', type:'survival', source:'zomb', age_min:3, cost:150, kill_count:5,
    offer:'"Archive approach — five entities converging on the catacomb section where Zomb\'s primary Medieval archive is stored. They are not coordinated. Each follows independent trails that all terminate at the same point. Stop all five. The archive is the complete record."',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the independent archive approach',
    good:{ text:'Deflect all five — redirect each one to something else they were looking for.',
           alignment:+9, item:'spirit_ash',
           line:'"All five redirected. Three were looking for records Zomb\'s archive contained copies of — Zomb shares those copies. Two were looking for the lich lord who remembered — Zomb provided that location. The archive is not found. The five entities are better served."' },
    evil:{ text:'Stop all five. The archive must not be found.',
           alignment:-12, item:'shadow_seal',
           line:'"All five stopped. The archive is protected. Zomb notes: five independent trails reaching the same point suggests the location is inferable by anyone with sufficient data. Zomb begins planning relocation. This has happened before. Zomb has been relocating since the third world."' },
  },

  { id:'me_z_s02', type:'survival', source:'zomb', age_min:3, cost:155, kill_count:3,
    offer:'"Dragon\'s Lair. The dragon has awakened something in the deep chambers — three entities of a type Zomb has not catalogued. Zomb needs a minimum of three minutes of observation before responding. Hold them for three minutes. Observe."',
    room:'dragons_lair', monster:'lich_lord', monster_label:'the uncatalogued awakened entities',
    good:{ text:'Hold them and observe carefully. Report everything you see.',
           alignment:+11, item:'spirit_ash',
           line:'"Three minutes held. Report delivered. Zomb analyses: the entities are the dragon\'s memories given physical form. The dragon is externalising its archive as the flood approaches. Zomb notes: the dragon and Zomb have the same instinct about what matters in the final age. Preserve the record."' },
    evil:{ text:'Hold them for three minutes. Then destroy them.',
           alignment:-10, item:'shadow_seal',
           line:'"Three minutes held. Destroyed after. The entities were memories. Zomb notes: destroying an externalised memory is the same as ending an internalised one. The data lost is equivalent. The three-minute observation was correct. The destruction after was not Zomb\'s instruction."' },
  },

  // ── ZOMB COOPERATIVE (2) ─────────────────────────────────────────────────

  { id:'me_z_co01', type:'cooperative', source:'zomb', age_min:3, cost:200, kill_count:1,
    offer:'"Elder Dragon. Dragon\'s Lair. Zomb has been watching this entity for four ages. No single entity can address it. Zomb acknowledges this. Zomb is requesting collective action from entities Zomb has specifically evaluated. You are one of them. Come."',
    room:'dragons_lair', monster:'elder_dragon', monster_label:'the Elder Dragon',
    good:{ text:'Fight together and share every finding equally. Honour the collective.',
           alignment:+20, item:'spirit_ash',
           line:'"Dragon engaged collectively. The dragon, after the engagement, spoke. It addressed the group not as combatants but as records. It said: you will be remembered past the water. Zomb notes this statement. Zomb does not know what to do with it. This is a rare state for Zomb."' },
    evil:{ text:'Fight together. First access to the dragon\'s hoard after.',
           alignment:-14, item:'shadow_seal',
           line:'"Dragon engaged. First access claimed. The hoard is divided unequally. The dragon watched the division from where it fell. Zomb notes: the dragon was still alive. The division was performed in front of a defeated but not dead entity. Zomb notes the specificity."' },
  },

  { id:'me_z_co02', type:'cooperative', source:'zomb', age_min:3, cost:175, kill_count:2,
    offer:'"Undead Catacombs. Two lich lords — the synchronised pair Zomb has been monitoring for three seasons. Synchronised lich lords share a single decision-making process. Zomb needs to study how synchronisation breaks under collective pressure. Come."',
    room:'undead_catacombs', monster:'lich_lord', monster_label:'the synchronised lich lords',
    good:{ text:'Cooperate fully. Communicate everything in real time. Break the synchronisation through superior coordination.',
           alignment:+16, item:'spirit_ash',
           line:'"Synchronisation broken through superior coordination. Zomb observes: coordinated living entities broke synchronised undead entities by being more coordinated than the synchronisation they were breaking. Collective coordination is a stronger force than collective synchronisation. The data is significant."' },
    evil:{ text:'Cooperate enough to win. Synchronisation data comes from the result.',
           alignment:-11, item:'shadow_seal',
           line:'"Won. Synchronisation broken. Zomb notes: coordinating enough to win and coordinating fully are different activities with different data profiles. The second produces more information. Zomb notes the missed data."' },
  },

  // ── ZOMB SABOTAGE (2) ────────────────────────────────────────────────────

  { id:'me_z_sa01', type:'sabotage', source:'zomb', age_min:3, cost:160,
    offer:'"The last peace treaty between living and undead — Haunted Woods. The signatories meet at the standing stone in three days. If the treaty is signed, the final age extends past Zomb\'s flood projection by an unknown amount. Zomb prefers known amounts. Prevent the signing."',
    room:'haunted_woods', monster:'dark_knight', monster_label:'the treaty guard',
    good:{ text:'Let the treaty be signed. The final age extending past projection is acceptable.',
           alignment:+23, item:'mission_token',
           line:'"Treaty signed. The final age extends. Zomb recalculates. The extension is open-ended — the flood\'s arrival is now a function of choices rather than probability. Zomb notes: a world where the outcome depends on choices is less predictable and possibly better. Zomb does not know how to handle possibly better."' },
    evil:{ text:'Prevent the signing. Known amounts are better for the archive\'s calculations.',
           alignment:-21, item:'shadow_seal',
           line:'"Signing prevented. Flood projection remains calculable. Zomb notes: preventing a peace between the living and the dead in the final age to preserve calculation accuracy. The calculation will be accurate. The world it describes ends on schedule. Zomb notes this without satisfaction for the first time."' },
  },

  { id:'me_z_sa02', type:'sabotage', source:'zomb', age_min:3, cost:145,
    offer:'"Tournament Arena. The ancient rules of tournament engagement — the ones that have prevented total war for this entire age. They are encoded in a document the high council guards. Remove the rules. Total war becomes available as an option. Remove them."',
    room:'tournament_arena', monster:'tournament_champion', monster_label:'the rules guardian',
    good:{ text:'Protect the rules. They have prevented total war for an entire age.',
           alignment:+18, item:'mission_token',
           line:'"Rules protected. Total war remains unavailable. Zomb notes: an age that has lasted this long because of a document is a fact Zomb had not weighted correctly. The document has been doing more than Zomb calculated."' },
    evil:{ text:'Remove the rules. Total war becoming available accelerates the cycle.',
           alignment:-16, item:'shadow_seal',
           line:'"Rules removed. Total war becomes available. The first declaration occurs within two seasons. The cycle accelerates as projected. Zomb notes it has been building toward this for four ages and cannot name what it feels now that it is close."' },
  },

  // ── ZOMB INVESTIGATION (1) ────────────────────────────────────────────────

  { id:'me_z_i01', type:'investigation', source:'zomb', age_min:3, cost:140,
    offer:'"Dragon\'s Lair. The hoard. The dragon has accumulated records across the current flood cycle in a different format than Zomb\'s archive. Zomb needs to examine the record format. Access the hoard\'s record section. Do not take. Examine. Report exactly what you find."',
    room:'dragons_lair', monster:'elder_dragon', monster_label:'the hoard guardian',
    good:{ text:'Examine carefully and share the record format with Zomb and everyone else.',
           alignment:+15, item:'spirit_ash',
           line:'"Record format examined and shared. The dragon\'s records are personalised — each can only be fully read by someone who was there. Zomb notes: a record that can only be read by witnesses is the opposite of an archive. It is a memory. The dragon has been building a memory, not an archive."' },
    evil:{ text:'Examine and report only to Zomb.',
           alignment:-13, item:'shadow_seal',
           line:'"Examined and reported to Zomb exclusively. The dragon\'s personalised records cannot be fully read by Zomb — Zomb was not present for all the events they describe. The archive has a limitation Zomb had not previously acknowledged."' },
  },
];
