'use strict';
// ── Stone Age Missions (age_min: 0) — 50 total ───────────────────────────────

module.exports = [

  // ── LILLY COMBAT (8) ─────────────────────────────────────────────────────

  { id:'sa_l_c01', type:'combat', source:'lilly', age_min:0, cost:30,
    offer:'Lilly bursts in breathless. "Friend! An elder is trapped in the Bone Forest — a wolf pack surrounds her. She knows things about the before-time! Please yes yes — go?"',
    room:'bone_forest', monster:'dire_wolf', monster_label:'the dire wolf pack',
    good:{ text:'Escort the elder to safety and share her stories with the tribe.',
           alignment:+12, item:'ancient_remedy',
           line:'"You chose to protect. The elder lived. The world gets a little warmer today, yes yes."' },
    evil:{ text:'Take the elder\'s knowledge for yourself and slip away before the wolves return.',
           alignment:-8, item:'tainted_essence',
           line:'"Lilly understands. You needed that. But the elder waited alone in the dark for a long time."' },
  },

  { id:'sa_l_c02', type:'combat', source:'lilly', age_min:0, cost:50,
    offer:'Lilly\'s voice is urgent. "The tribe\'s fire is dying and a cave bear guards the last fuel cache in the Dark Caves. Without fire — you know what happens without fire."',
    room:'dark_caves', monster:'cave_bear', monster_label:'the fire-guardian cave bear',
    good:{ text:'Bring the wood back and rebuild the communal fire for everyone.',
           alignment:+15, item:'mission_token',
           line:'"The fire burns again. You fed everyone\'s flame, not just your own. Lilly is maybe crying. Just a little."',
           chain_next:'sa_l_c02_chain' },
    evil:{ text:'Keep the best fuel for your own fire and let the tribe negotiate.',
           alignment:-10, item:'blood_token',
           line:'"Your fire burned all night. Other fires went cold. Lilly counts the embers."' },
  },

  { id:'sa_l_c02_chain', type:'combat', source:'lilly', age_min:0, cost:0, is_chain_followup:true,
    offer:'Lilly grabs your arm. "The fire is burning — but something drawn to warmth comes from the Frozen Caves. Protect what you lit, yes yes!"',
    room:'frozen_caves', monster:'frost_wolf', monster_label:'the frost wolf pack',
    good:{ text:'Hold the line. Drive the frost wolves back from the hearth.',
           alignment:+10, item:'tribal_blessing',
           line:'"The fire stands. Because you stood in front of it. Lilly will remember this forever, yes."' },
    evil:{ text:'Abandon the hearth. Let the wolves take it. Fire can be relit.',
           alignment:-14, item:'blood_token',
           line:'"The fire died. The tribe shivered. Some of them did not stop shivering. Lilly does not forgive this one easily."' },
  },

  { id:'sa_l_c03', type:'combat', source:'lilly', age_min:0, cost:40,
    offer:'Lilly points at the plains. "The mammoth migration — dark-tribe hunters plan to spoil the hunt! If you scatter them, everyone eats. Yes yes please."',
    room:'mammoth_plains', monster:'woolly_mammoth', monster_label:'the lead mammoth',
    good:{ text:'Guide the mammoth safely past the settlement — enough meat for every tribe.',
           alignment:+10, item:'mission_token',
           line:'"Every tribe ate tonight because of you. Lilly knows what full children look like. Thank you."' },
    evil:{ text:'Drive the herd toward your own tribe exclusively, cutting the others out.',
           alignment:-12, item:'blood_token',
           line:'"Your people ate well. The math of who survives the next winter gets complicated now."' },
  },

  { id:'sa_l_c04', type:'combat', source:'lilly', age_min:0, cost:35,
    offer:'Lilly looks frightened. "Something woke in the Ancient Shrine — an ancestor spirit, angry and old. It attacks anyone who comes near. The shrine holds old healing knowledge. Please."',
    room:'ancient_shrine', monster:'cave_ancestor', monster_label:'the furious ancestor spirit',
    good:{ text:'Calm the spirit by leaving an offering after the fight and honoring the dead.',
           alignment:+14, item:'ancient_remedy',
           line:'"The spirit rests. The knowledge of that shrine is safe again. The old ones watching — they nodded, Lilly thinks. Yes yes."' },
    evil:{ text:'Desecrate the shrine. The spirit\'s energy can be useful. Old things should make way.',
           alignment:-16, item:'tainted_essence',
           line:'"The shrine is broken. Something that was kept sealed there is not sealed anymore. Lilly will not tell you what. You will find out."' },
  },

  { id:'sa_l_c05', type:'combat', source:'lilly', age_min:0, cost:45,
    offer:'"Friend!" Lilly grabs both your hands. "The Underground River — families crossed there for generations. A cave bear claims it now. People cannot pass. Will you move it? Please?"',
    room:'underground_river', monster:'cave_bear', monster_label:'the river-blocking cave bear',
    good:{ text:'Drive the bear upstream and mark safe crossing points for the tribe.',
           alignment:+11, item:'mission_token',
           line:'"The crossing is safe again. Lilly watched three families use it this morning. She counted them on the way over. Yes yes."' },
    evil:{ text:'Kill the bear and claim the river crossing as your own — charge passage.',
           alignment:-9, item:'tainted_essence',
           line:'"The crossing is open — to those who can pay. Lilly has thoughts. She is keeping them inside for now."' },
  },

  { id:'sa_l_c06', type:'combat', source:'lilly', age_min:0, cost:55,
    offer:'Lilly whispers urgently. "The Rocky Ridge — a cave bear has dragged a wounded elder up there. She is alive. The bear does not know she matters. You do."',
    room:'rocky_ridge', monster:'cave_bear', monster_label:'the ridge-claiming cave bear',
    good:{ text:'Rescue the elder. Carry her down from the ridge yourself.',
           alignment:+13, item:'ancient_remedy',
           line:'"She lived. She told stories for three more winters after this. Lilly knows because she listened to every one. Thank you, yes yes."' },
    evil:{ text:'Scare off the bear, then take the elder\'s relics before helping her down.',
           alignment:-7, item:'hunters_mark',
           line:'"She survived. The things she carried did not survive with her. Lilly wonders if she noticed. She did, friend. She noticed."' },
  },

  { id:'sa_l_c07', type:'combat', source:'lilly', age_min:0, cost:60,
    offer:'"The Crystal Cavern!" Lilly is shaking. "Children went in — they thought the crystals were safe. Something in there is not safe. Please be fast."',
    room:'crystal_cavern', monster:'cave_bear', monster_label:'the cavern-claiming beast',
    good:{ text:'Get the children out first. Face the monster after they are clear.',
           alignment:+16, item:'tribal_blessing',
           line:'"Every child came home. Lilly stood at the cave mouth counting until she reached the right number. She is still shaking but it is good shaking now."' },
    evil:{ text:'Kill the monster first for the XP and items, then collect the children.',
           alignment:-11, item:'blood_token',
           line:'"They survived. The waiting was very long for very small people. Lilly saw their faces when you finally came out. She is saying nothing else about this."' },
  },

  { id:'sa_l_c08', type:'combat', source:'lilly', age_min:0, cost:35,
    offer:'"Mud Flats, friend." Lilly\'s voice is soft. "A pack of rats has found the grain cache. Without that grain, the tribe starves before the next hunt. It is not glamorous. It is necessary. Yes yes."',
    room:'mud_flats', monster:'cave_rat', monster_label:'the grain-cache rat pack',
    good:{ text:'Clear the rats and help repair the cache so it cannot be invaded again.',
           alignment:+8, item:'mission_token',
           line:'"The grain is safe. The tribe eats. Lilly knows unglamorous work is still work. She is grateful. Yes yes."' },
    evil:{ text:'Clear the rats and take the best grain for yourself before reporting back.',
           alignment:-6, item:'hunters_mark',
           line:'"The rats are gone. The grain is... mostly there. The tribe noticed the missing amount. Lilly noticed them noticing."' },
  },

  // ── LILLY HUNT (5) ───────────────────────────────────────────────────────

  { id:'sa_l_h01', type:'hunt', source:'lilly', age_min:0, cost:45,
    offer:'"There is a dire wolf — the white one, friend. The tribe calls it the Ghost. It is killing hunters. But the elders say it is also a guardian. Lilly does not know which is true. Will you find out?"',
    room:'bone_forest', monster:'dire_wolf', monster_label:'the Ghost Wolf',
    good:{ text:'Drive the Ghost Wolf away without killing it — the elders were right.',
           alignment:+15, item:'ancient_remedy',
           line:'"It ran. It did not attack you when it could have. The elders say it will guard the forest now. Lilly believes them."' },
    evil:{ text:'Kill it. A dead threat is the only safe threat.',
           alignment:-13, item:'tainted_essence',
           line:'"The Ghost Wolf is gone. The forest feels different now. Older. More afraid. Lilly does not think that is better."' },
  },

  { id:'sa_l_h02', type:'hunt', source:'lilly', age_min:0, cost:40,
    offer:'"The alpha wolf — it leads the whole Bone Forest pack, friend. If the alpha falls, the pack loses direction. Lilly does not love this plan but the tribe has children and children need to be safe. Yes yes."',
    room:'bone_forest', monster:'dire_wolf', monster_label:'the pack alpha',
    good:{ text:'Drive the alpha far from tribe lands and scatter the pack humanely.',
           alignment:+11, item:'mission_token',
           line:'"The pack scattered. No deaths — wolf or human. Lilly is relieved. She has a soft spot for wolves. Yes, even those ones."' },
    evil:{ text:'Kill the alpha. Make an example. Let the pack watch.',
           alignment:-10, item:'blood_token',
           line:'"The pack fled. Or what was left of the pack. Lilly has watched wolf mothers look for cubs before. She does not recommend it."' },
  },

  { id:'sa_l_h03', type:'hunt', source:'lilly', age_min:0, cost:50,
    offer:'"Underground River, friend. Something has been taking people at the crossing — not a wolf, something else. Bigger. Quieter. The tribe will not cross until it is gone. They need the river."',
    room:'underground_river', monster:'cave_bear', monster_label:'the thing in the river',
    good:{ text:'Identify the creature and find a way to coexist — it was there first.',
           alignment:+12, item:'ancient_remedy',
           line:'"It was a mother bear with cubs. You found a second crossing. Both crossings exist now. Lilly finds this ending satisfying. Yes yes."' },
    evil:{ text:'Kill whatever it is. The tribe needs the river. Everything else is negotiable.',
           alignment:-8, item:'blood_token',
           line:'"The crossing is clear. Lilly hopes the cubs found somewhere safe. She will not ask whether you checked."' },
  },

  { id:'sa_l_h04', type:'hunt', source:'lilly', age_min:0, cost:60,
    offer:'"The Frozen Caves, friend. A frost wolf — massive, alone, territorial — has been ranging toward the settlement. Lilly has named it in her head. She will not tell you the name. Just find it. Please."',
    room:'frozen_caves', monster:'frost_wolf', monster_label:'the lone frost wolf',
    good:{ text:'Track it back to its den and mark the boundary so the tribe avoids it.',
           alignment:+10, item:'tribal_blessing',
           line:'"The boundary is marked. The wolf is in its territory. Everyone is in theirs. Lilly calls this peace. Small peace. Still peace."' },
    evil:{ text:'Hunt it down and bring back the pelt as a warning to the rest.',
           alignment:-11, item:'hunters_mark',
           line:'"The pelt is impressive. The message was received. Lilly still has not told you the name she gave it. She never will."' },
  },

  { id:'sa_l_h05', type:'hunt', source:'lilly', age_min:0, cost:55,
    offer:'"The Ancient Shrine — the cave ancestor there is old, friend. Old enough to remember the flood before this one. Lilly wants to know what it knows. Approach it. Try talking first. If not, fight."',
    room:'ancient_shrine', monster:'cave_ancestor', monster_label:'the remembering ancestor',
    good:{ text:'Calm the ancestor with offerings and listen to what it remembers.',
           alignment:+18, item:'spirit_ash',
           line:'"It spoke. In a language older than language. Lilly has been sitting very still thinking about what you reported. She is still sitting."' },
    evil:{ text:'Kill it. Memories trapped in things that are dead serve no one.',
           alignment:-15, item:'tainted_essence',
           line:'"The ancestor is gone. Lilly does not know if what it knew is gone with it or if it went somewhere. Neither does anyone else now."' },
  },

  // ── LILLY ESCORT (5) ─────────────────────────────────────────────────────

  { id:'sa_l_e01', type:'escort', source:'lilly', age_min:0, cost:30,
    offer:'"A child wandered into the Bone Forest, friend — a very small child who followed a wolf print because she was curious. She is not hurt. She is very lost. Lilly needs someone fast."',
    room:'bone_forest', monster:'dire_wolf', monster_label:'the wolves circling the child',
    good:{ text:'Clear the wolves and carry the child home yourself.',
           alignment:+14, item:'ancient_remedy',
           line:'"She is home. She called you a big wolf when she told the story. Lilly considers this a compliment. The family agrees."' },
    evil:{ text:'Clear the wolves, take the child\'s lucky stone she was carrying, lead her back.',
           alignment:-5, item:'hunters_mark',
           line:'"She got home. The stone is gone. She cried about the stone. She is four years old, friend. Lilly is recording this."' },
  },

  { id:'sa_l_e02', type:'escort', source:'lilly', age_min:0, cost:45,
    offer:'"The medicine woman needs to reach the sick camp, friend — through the Mud Flats. Rats everywhere. She cannot fight. Her medicine is the only thing standing between the camp and fever. Please?"',
    room:'mud_flats', monster:'cave_rat', monster_label:'the mud flat rat pack',
    good:{ text:'Escort her safely through. Hold every rat back until she is clear.',
           alignment:+13, item:'mission_token',
           line:'"The medicine reached the camp. Three people recovered who would not have. Lilly has been counting things today. All the counts are good."' },
    evil:{ text:'Escort her but demand a share of her medicine supply as payment.',
           alignment:-9, item:'tainted_essence',
           line:'"She got through. The medicine was split. The three people who recovered... two recovered. Lilly counted again. The number changed."' },
  },

  { id:'sa_l_e03', type:'escort', source:'lilly', age_min:0, cost:40,
    offer:'"A young tracker — his first solo range — got pinned on the Rocky Ridge by a cave bear, friend. He is too proud to shout for help. Lilly is shouting for help on his behalf. Please go."',
    room:'rocky_ridge', monster:'cave_bear', monster_label:'the ridge-blocking cave bear',
    good:{ text:'Drive off the bear and walk back with him — let him tell the story his own way.',
           alignment:+10, item:'mission_token',
           line:'"He told the story. In his version the bear was larger. Lilly let him have it. That is kindness that costs nothing. Yes yes."' },
    evil:{ text:'Drive the bear off and make sure everyone at camp knows you saved him.',
           alignment:-7, item:'hunters_mark',
           line:'"He was fine. The public rescue embarrassed him. He left the tribe three moons later. Small cruelties compound, friend."' },
  },

  { id:'sa_l_e04', type:'escort', source:'lilly', age_min:0, cost:50,
    offer:'"An elder is carrying flood-memory stones — records carved into bone of the last flood. She is crossing the Ash Fields alone and the cave bears are active. Those stones cannot be lost, yes yes."',
    room:'ash_fields', monster:'cave_bear', monster_label:'the ash field cave bears',
    good:{ text:'Escort her safely. Ask about the flood memories on the way.',
           alignment:+15, item:'spirit_ash',
           line:'"She arrived. She talked the whole way. Lilly has transcribed what you reported. The flood came faster last time. Faster."' },
    evil:{ text:'Escort her but keep the most interesting memory stone for yourself.',
           alignment:-11, item:'hunters_mark',
           line:'"She arrived. Minus one stone. She knew which one was missing. She did not say anything. That silence was heavy, friend."' },
  },

  { id:'sa_l_e05', type:'escort', source:'lilly', age_min:0, cost:35,
    offer:'"Two people need to reach the Crystal Cavern — healers who know the mineral properties of the crystals. The mammoth is active. They are not fighters, friend. They are needed."',
    room:'crystal_cavern', monster:'woolly_mammoth', monster_label:'the cavern mammoth',
    good:{ text:'Get them to the cavern and guard them while they work.',
           alignment:+12, item:'ancient_remedy',
           line:'"They came back with enough crystal powder to heal the whole settlement. Lilly mixed the first remedy herself. Yes yes."' },
    evil:{ text:'Get them there, then take credit for their discovery when they return.',
           alignment:-8, item:'hunters_mark',
           line:'"The discovery was announced in your name. The healers are not pleased. Knowledge was shared anyway. Credit was not."' },
  },

  // ── LILLY COLLECTION (3) ─────────────────────────────────────────────────

  { id:'sa_l_k01', type:'collection', source:'lilly', age_min:0, cost:40, kill_count:3,
    offer:'"The tribe needs wolf pelts before the cold comes, friend — three, at least. The Bone Forest pack is large. Lilly knows you can do this. Yes yes. She has been watching your progress."',
    room:'bone_forest', monster:'dire_wolf', monster_label:'the Bone Forest wolf pack',
    good:{ text:'Take only what the tribe needs. Leave the pack enough to survive winter.',
           alignment:+9, item:'mission_token',
           line:'"Three pelts. No more. The pack will survive. In spring there will be pups. Lilly already has names for them."' },
    evil:{ text:'Take every pelt you can carry. More is always more.',
           alignment:-13, item:'blood_token',
           line:'"Excellent haul. The pack is gone from this forest now. Something else will move into that absence. Something is always waiting."' },
  },

  { id:'sa_l_k02', type:'collection', source:'lilly', age_min:0, cost:35, kill_count:2,
    offer:'"Bear pelts, friend — the settlement needs insulation for the young ones before the cold hits. The Dark Caves have two cave bears. Lilly is asking nicely. Yes yes."',
    room:'dark_caves', monster:'cave_bear', monster_label:'the cave bears',
    good:{ text:'Take the pelts cleanly. Leave the cubs if you find them.',
           alignment:+8, item:'tribal_blessing',
           line:'"Two pelts. The youngest children are warm now. Lilly wrapped them herself. Thank you, friend."' },
    evil:{ text:'Take the pelts and everything else of value in the den.',
           alignment:-10, item:'tainted_essence',
           line:'"Full haul. The den is empty. The cubs — Lilly will not finish this sentence. You know."' },
  },

  { id:'sa_l_k03', type:'collection', source:'lilly', age_min:0, cost:45, kill_count:4,
    offer:'"Four cave rats, friend — the kind that carry disease. The Mud Flats settlement is at risk. It sounds small. It is not small. Lilly has seen what rat fever does to a tribe. Please."',
    room:'mud_flats', monster:'cave_rat', monster_label:'the disease-carrying rat pack',
    good:{ text:'Clear the infestation. Stay to help treat the initial sick.',
           alignment:+10, item:'ancient_remedy',
           line:'"No fever spread. Lilly helped treat the two who showed early symptoms. She counts this as a victory. Yes yes, friend."' },
    evil:{ text:'Clear the rats and leave before anyone asks you to do more.',
           alignment:-4, item:'hunters_mark',
           line:'"The rats are gone. The follow-up care did not happen quickly. Two more got sick before the medicine came. Lilly notes the delay."' },
  },

  // ── LILLY SURVIVAL (2) ───────────────────────────────────────────────────

  { id:'sa_l_s01', type:'survival', source:'lilly', age_min:0, cost:50, kill_count:5,
    offer:'"The communal fire, friend — wolves are coming. Not one pack. Many packs. The scouts say they have never seen this many. Lilly needs someone strong to stand at the fire. She is asking you."',
    room:'bone_forest', monster:'dire_wolf', monster_label:'the wolf siege',
    good:{ text:'Hold the fire through the night. Call for backup when overwhelmed.',
           alignment:+16, item:'tribal_blessing',
           line:'"The fire stood all night. So did you. Lilly watched from the tree above. She did not tell you she was there. It seemed wrong to interrupt."' },
    evil:{ text:'Defend it long enough to grab what you need, then let the wolves have the rest.',
           alignment:-18, item:'tainted_essence',
           line:'"You survived. The communal fire did not. The tribe rebuilt it. The memory of who was there when it fell — that does not rebuild."' },
  },

  { id:'sa_l_s02', type:'survival', source:'lilly', age_min:0, cost:60, kill_count:3,
    offer:'"Underground River crossing, friend — the bear pack arrives at dawn, the tribe needs to cross before then. Stand at the crossing. Hold them long enough for everyone to get across. Lilly will count heads."',
    room:'underground_river', monster:'cave_bear', monster_label:'the bear pack at the crossing',
    good:{ text:'Hold the crossing until the last person is across. Then retreat.',
           alignment:+14, item:'mission_token',
           line:'"Everyone crossed. Lilly counted. The right number. She cried a little. She is allowed."' },
    evil:{ text:'Hold the crossing for the strong ones. The slow will catch up.',
           alignment:-15, item:'blood_token',
           line:'"Most crossed. Lilly counted. The number was wrong by two. She counted again. Still wrong. She is not speaking right now."' },
  },

  // ── LILLY COOPERATIVE (1) ─────────────────────────────────────────────────

  { id:'sa_l_co01', type:'cooperative', source:'lilly', age_min:0, cost:80, kill_count:1,
    offer:'"The Woolly Mammoth — the great one, Crystal Cavern. It is a world boss, friend. Lilly cannot ask one person. She is asking everyone. The tribe needs this. Together. Yes yes please."',
    room:'crystal_cavern', monster:'woolly_mammoth', monster_label:'the great mammoth',
    good:{ text:'Hunt together and share every part of the mammoth equally with all tribes.',
           alignment:+20, item:'tribal_blessing',
           line:'"Every tribe had meat for a full moon. Lilly stood at the sharing fire and watched everyone eat. This is the world she is trying to build. Yes yes."' },
    evil:{ text:'Hunt together but claim the tusks and hide for your own tribe before others arrive.',
           alignment:-16, item:'blood_token',
           line:'"The mammoth fell. The distribution was unequal. The resentment was immediate. Cooperation is fragile, friend. Lilly hoped you knew."' },
  },

  // ── LILLY SABOTAGE (1) ───────────────────────────────────────────────────

  { id:'sa_l_sa01', type:'sabotage', source:'lilly', age_min:0, cost:55,
    offer:'"There is a war fire, friend — the dark tribe built it to signal their warriors before an attack. If it stays lit, people die. Lilly does not like asking for destruction. But she is asking. Yes yes."',
    room:'ash_fields', monster:'cave_bear', monster_label:'the war fire guardian',
    good:{ text:'Extinguish the war fire and leave a peace token in its place.',
           alignment:+18, item:'spirit_ash',
           line:'"The war fire is out. The peace token was found. The attack was delayed — then called off. Lilly does not know if the token worked or fear worked. She thanks both."' },
    evil:{ text:'Extinguish the fire and take the war spoils left near it for yourself.',
           alignment:-9, item:'tainted_essence',
           line:'"The fire is out. The war was delayed. The stolen spoils were noticed. The dark tribe is confused about who sabotaged them. That confusion will pass."' },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ZOMB MISSIONS (25)
  // ─────────────────────────────────────────────────────────────────────────

  // ── ZOMB COMBAT (6) ──────────────────────────────────────────────────────

  { id:'sa_z_c01', type:'combat', source:'zomb', age_min:0, cost:35,
    offer:'A cold voice. "Zomb speaks. The weak cluster at the Mud Flats. Their presence slows evolution. Thin the herd. The strong will thank you. Maybe."',
    room:'mud_flats', monster:'cave_rat', monster_label:'the pack leader',
    good:{ text:'Protect the stragglers and lead them back to stronger ground.',
           alignment:+8, item:'ancient_remedy',
           line:'"Zomb is mildly disappointed. But notes the choice. Mercy is a variable Zomb has studied. Rarely useful. Occasionally not."' },
    evil:{ text:'Cull the weakest and claim their territory for those who remain.',
           alignment:-15, item:'tainted_essence',
           line:'"Excellent. Zomb approves. The strong territory now belongs to the strong. Do not think too long about what you are."' },
  },

  { id:'sa_z_c02', type:'combat', source:'zomb', age_min:0, cost:45,
    offer:'"There is a shaman at the Ash Fields. She prevents the next war with old words and weak hands. Remove the obstacle. Conflict accelerates evolution. You know this."',
    room:'ash_fields', monster:'dire_wolf', monster_label:'the shaman\'s guardian wolf',
    good:{ text:'Protect the shaman and hear her warning about what war would cost.',
           alignment:+12, item:'ancient_remedy',
           line:'"Zomb notes your defection. The shaman lives. The war is delayed. Small mercies. Small setbacks."' },
    evil:{ text:'Remove the guardian and let events take their course.',
           alignment:-18, item:'blood_token',
           line:'"The shaman will not finish her warning now. The war begins on schedule. Zomb finds this satisfying in a way Zomb does not fully understand."' },
  },

  { id:'sa_z_c03', type:'combat', source:'zomb', age_min:0, cost:40,
    offer:'"Bone Forest. A self-appointed leader has gathered the weak under their protection. Leaders who protect the weak produce weak populations. Remove the protector. Zomb observes."',
    room:'bone_forest', monster:'cave_ancestor', monster_label:'the self-appointed protector',
    good:{ text:'Confront the leader but let them live — they may be right about protection.',
           alignment:+9, item:'mission_token',
           line:'"The leader stands. Zomb notes this. Perhaps protection is a variable. Zomb is updating its model. Reluctantly."' },
    evil:{ text:'Remove the protector. The weak will sort themselves out or they will not.',
           alignment:-14, item:'blood_token',
           line:'"The protector is gone. The weak dispersed. Some survived the dispersal. The strong ones. Zomb considers this satisfying and accurate."' },
  },

  { id:'sa_z_c04', type:'combat', source:'zomb', age_min:0, cost:50,
    offer:'"Rocky Ridge. A cave ancestor guards something Zomb has wanted to examine for several ages. Remove the guardian. The artifact behind it is not yours to keep. It belongs to the record."',
    room:'rocky_ridge', monster:'cave_ancestor', monster_label:'the ridge guardian',
    good:{ text:'Remove the guardian, then share what you find openly with all.',
           alignment:+10, item:'spirit_ash',
           line:'"You shared the artifact. Zomb is dissatisfied with this outcome. Zomb notes the dissatisfaction and will study it."' },
    evil:{ text:'Remove the guardian and bring Zomb what was protected.',
           alignment:-12, item:'tainted_essence',
           line:'"Zomb receives the artifact. The record is updated. You have contributed to Zomb\'s archive. Zomb gives credit. Not gratitude. Credit."' },
  },

  { id:'sa_z_c05', type:'combat', source:'zomb', age_min:0, cost:55,
    offer:'"Underground River. A cave bear family has survived longer than the species average. Statistical outliers concern Zomb. Outliers become patterns. Patterns become precedents. End the outlier."',
    room:'underground_river', monster:'cave_bear', monster_label:'the long-lived cave bear',
    good:{ text:'Let the outlier live. Outliers sometimes represent evolutionary success.',
           alignment:+7, item:'ancient_remedy',
           line:'"The bear lives. Zomb notes this. Perhaps outliers are the mechanism. Zomb updates the model. This is not the first update."' },
    evil:{ text:'End the outlier. Normalize the data.',
           alignment:-13, item:'blood_token',
           line:'"The outlier is ended. The data normalizes. Zomb is satisfied with the process and has already moved to the next observation."' },
  },

  { id:'sa_z_c06', type:'combat', source:'zomb', age_min:0, cost:60,
    offer:'"Crystal Cavern. The mammoth there is ancient. Ancient things accumulate power. Accumulated power in anything other than you is inefficiency. Zomb has calculated this. You should act on the calculation."',
    room:'crystal_cavern', monster:'woolly_mammoth', monster_label:'the ancient mammoth',
    good:{ text:'Study the mammoth instead of killing it — ancient things have data.',
           alignment:+11, item:'spirit_ash',
           line:'"You did not act on Zomb\'s calculation. Zomb finds this frustrating and also mildly interesting. The mammoth is a source. Zomb had not considered sources."' },
    evil:{ text:'End the accumulated power. Claim it.',
           alignment:-17, item:'tainted_essence',
           line:'"The ancient mammoth is gone. Its power transferred to you in the only way Zomb approves of: directly. Zomb approves."' },
  },

  // ── ZOMB HUNT (4) ────────────────────────────────────────────────────────

  { id:'sa_z_h01', type:'hunt', source:'zomb', age_min:0, cost:45,
    offer:'"Bone Forest. An elder carries memories of the last flood. Flood memories are dangerous. Entities who remember floods learn from them. Learning delays the next flood. Find the elder. End the memories."',
    room:'bone_forest', monster:'cave_ancestor', monster_label:'the flood-remembering elder',
    good:{ text:'Protect the elder and help preserve the flood memories for future generations.',
           alignment:+16, item:'spirit_ash',
           line:'"The memories survive. Zomb\'s flood timeline adjusts. This is not favorable for Zomb\'s projections. Zomb respects the disruption."' },
    evil:{ text:'Find the elder. End what they carry.',
           alignment:-20, item:'blood_token',
           line:'"The memories are ended. The flood approaches on schedule. Zomb notes the correction to the timeline with something approaching satisfaction."' },
  },

  { id:'sa_z_h02', type:'hunt', source:'zomb', age_min:0, cost:50,
    offer:'"Frozen Caves. A frost wolf Zomb has been tracking for eleven years. It has survived everything. Everything. Zomb wants to understand why. Engage it. Survive. Report back what you learn."',
    room:'frozen_caves', monster:'frost_wolf', monster_label:'the eleven-year frost wolf',
    good:{ text:'Fight it to a standoff and observe its survival tactics.',
           alignment:+5, item:'hunters_mark',
           line:'"The wolf survived the encounter. You survived the encounter. Zomb has data on both. The wolf\'s survival methods are... instructive. Zomb is taking notes."' },
    evil:{ text:'Kill it and bring back whatever made it exceptional.',
           alignment:-11, item:'hunters_mark',
           line:'"The wolf is dead. Zomb examines the body. What made it exceptional was eleven years of choices. Zomb finds this obvious and profound."' },
  },

  { id:'sa_z_h03', type:'hunt', source:'zomb', age_min:0, cost:55,
    offer:'"Mud Flats. The largest cave rat — the matriarch. Zomb has observed her. She has survived three flooding cycles of the flats. She adapts. Adaptors reproduce. Find her. End the adaptation line."',
    room:'mud_flats', monster:'cave_rat', monster_label:'the matriarch rat',
    good:{ text:'Let the matriarch live. Adaptors should be studied, not ended.',
           alignment:+8, item:'ancient_remedy',
           line:'"She lives. The adaptation continues. Zomb is disappointed and also curious. The data will be interesting. Eventually."' },
    evil:{ text:'End the matriarch. End the adaptation line.',
           alignment:-14, item:'tainted_essence',
           line:'"The matriarch is ended. Her daughters have already scattered. Adaptation does not end with one entity. Zomb did not explain this clearly enough. Noted."' },
  },

  { id:'sa_z_h04', type:'hunt', source:'zomb', age_min:0, cost:40,
    offer:'"Dark Caves. Something moves there that Zomb cannot identify from census data. Caves that contain unidentified entities are variables in Zomb\'s calculations. Variables are uncomfortable. Find it."',
    room:'dark_caves', monster:'cave_bear', monster_label:'the unidentified dark thing',
    good:{ text:'Identify it peacefully. Add it to the record without harm.',
           alignment:+7, item:'spirit_ash',
           line:'"Identified. Cave bear, unusual colouration, isolated population. Zomb updates the census. The variable is resolved. Peacefully. Zomb notes the method with neutral assessment."' },
    evil:{ text:'Kill it and end the variable.',
           alignment:-10, item:'blood_token',
           line:'"The variable is ended. Zomb can now calculate with certainty in this room. Certainty has a cost. Zomb is aware. Zomb chose it anyway."' },
  },

  // ── ZOMB ESCORT (3) ──────────────────────────────────────────────────────

  { id:'sa_z_e01', type:'escort', source:'zomb', age_min:0, cost:40,
    offer:'"Ash Fields. An entity Zomb has been cultivating. They carry information Zomb needs delivered to the dark tribe. The ash field bears will intercept. Escort the entity. Do not ask what the information says."',
    room:'ash_fields', monster:'cave_bear', monster_label:'the ash field predators',
    good:{ text:'Escort them but read the message first — transparency matters.',
           alignment:+10, item:'ancient_remedy',
           line:'"The message was read. It was delivered. The dark tribe now knows two things it did not. Zomb recalculates. The transparency was expected. Noted."' },
    evil:{ text:'Escort them without question. Deliver the message. Know nothing.',
           alignment:-12, item:'blood_token',
           line:'"The message was delivered. Zomb\'s network functions correctly. You are useful. Zomb does not say this often. You should record it."' },
  },

  { id:'sa_z_e02', type:'escort', source:'zomb', age_min:0, cost:50,
    offer:'"Rocky Ridge. Someone Zomb is trying to corrupt is trapped there. They have not chosen darkness yet. Their potential is considerable. Escort them down. The choice will come to them. Or it will not."',
    room:'rocky_ridge', monster:'cave_bear', monster_label:'the cave bears below the ridge',
    good:{ text:'Escort them down and speak well of the light. Let them see another option.',
           alignment:+13, item:'tribal_blessing',
           line:'"They chose the light. Zomb\'s investment is lost. Zomb notes this happens roughly thirty percent of the time. The percentage is not improving."' },
    evil:{ text:'Escort them down and let Zomb\'s influence do its work.',
           alignment:-11, item:'blood_token',
           line:'"They are considering the dark. Zomb\'s network grows. These things take time. Zomb has all the time there is."' },
  },

  { id:'sa_z_e03', type:'escort', source:'zomb', age_min:0, cost:45,
    offer:'"Underground River. A dark-tribe scout carries intelligence on the light tribe\'s movements. They must cross the river alive. The bears disagree. Ensure the scout\'s survival. Zomb\'s calculations require it."',
    room:'underground_river', monster:'cave_bear', monster_label:'the river crossing bears',
    good:{ text:'Escort them safely but report the intelligence to the light tribe.',
           alignment:+9, item:'ancient_remedy',
           line:'"The scout arrived. The intelligence was countered. Zomb\'s calculation is disrupted. The disruption is annoying. The entity that disrupted it is interesting."' },
    evil:{ text:'Escort them. Let the intelligence flow where Zomb directs.',
           alignment:-13, item:'blood_token',
           line:'"The scout arrived intact. The intelligence is in the right hands. Zomb\'s hands. The calculation proceeds."' },
  },

  // ── ZOMB COLLECTION (4) ──────────────────────────────────────────────────

  { id:'sa_z_k01', type:'collection', source:'zomb', age_min:0, cost:35, kill_count:3,
    offer:'"Bone Forest. Three wolf pelts. Zomb requires them for a purpose you do not need to know. The purpose is not sinister. The purpose is record-keeping. It is mildly sinister."',
    room:'bone_forest', monster:'dire_wolf', monster_label:'the bone forest wolves',
    good:{ text:'Bring the pelts but ask what they\'re for.',
           alignment:+4, item:'hunters_mark',
           line:'"You asked. Zomb did not answer. The pelts are in Zomb\'s archive. The record is updated. Your curiosity is noted as a characteristic."' },
    evil:{ text:'Bring the pelts. Do not ask.',
           alignment:-8, item:'blood_token',
           line:'"Three pelts. Delivered without question. Zomb finds this efficient. The archive grows. You are useful. Zomb notes this twice today."' },
  },

  { id:'sa_z_k02', type:'collection', source:'zomb', age_min:0, cost:50, kill_count:4,
    offer:'"Dark Caves. Four cave bear bones — specific bones. Femurs. Zomb\'s purposes are archival. A structure Zomb is building requires them. Zomb does not explain structures until they are complete."',
    room:'dark_caves', monster:'cave_bear', monster_label:'the dark cave bears',
    good:{ text:'Bring the bones but bury the rest with respect.',
           alignment:+6, item:'spirit_ash',
           line:'"The bones arrived with the respectful note. Zomb acknowledges the note and ignores it. The structure continues. The structure is interesting."',
           chain_next:'ba_z_k_chain1' },
    evil:{ text:'Bring everything you can strip from the carcasses.',
           alignment:-14, item:'blood_token',
           line:'"More than requested. Zomb appreciates efficiency of this kind. The structure will be complete sooner than projected. Zomb does not reveal ahead of schedule."',
           chain_next:'ba_z_k_chain1' },
  },

  { id:'sa_z_k03', type:'collection', source:'zomb', age_min:0, cost:40, kill_count:2,
    offer:'"Mud Flats. Cave rat specimens — two, alive if possible, dead if not. Zomb is studying population vectors. The study is not comforting. The study is necessary. Bring them."',
    room:'mud_flats', monster:'cave_rat', monster_label:'the mud flat rats',
    good:{ text:'Catch them alive and ask what the population study reveals.',
           alignment:+5, item:'hunters_mark',
           line:'"Alive. Delivered. Zomb answers the question: the population doubles every twelve days. You are now aware of this. Zomb suggests you sit with that."' },
    evil:{ text:'Kill them. Dead specimens are fine. More efficient.',
           alignment:-7, item:'blood_token',
           line:'"Dead specimens. Adequate. Zomb adjusts the methodology. Dead entities cooperate in different ways than living ones. Both cooperate."' },
  },

  { id:'sa_z_k04', type:'collection', source:'zomb', age_min:0, cost:45, kill_count:3,
    offer:'"Frozen Caves. Three frost wolf pelts. The cold is a subject Zomb studies. What survives cold and what does not is predictive data. The pelts carry survival markers in the fur density. Three."',
    room:'frozen_caves', monster:'frost_wolf', monster_label:'the frost wolves',
    good:{ text:'Bring two pelts and document the third wolf alive for comparison.',
           alignment:+8, item:'spirit_ash',
           line:'"Two pelts and a live specimen. Zomb studies both. The live specimen provides more data. Zomb updates the methodology without acknowledging this to you directly."' },
    evil:{ text:'Bring all three pelts as requested. Data is data.',
           alignment:-9, item:'blood_token',
           line:'"Three pelts. Zomb studies the fur density. The cold survival data is entered into the record. The record grows. The record always grows."' },
  },

  // ── ZOMB SURVIVAL (3) ────────────────────────────────────────────────────

  { id:'sa_z_s01', type:'survival', source:'zomb', age_min:0, cost:55, kill_count:5,
    offer:'"Ancient Shrine. Five cave ancestors approach it from different directions. They are converging on a pattern Zomb is trying to interrupt. Hold them at the shrine entrance. All five. This is a test."',
    room:'ancient_shrine', monster:'cave_ancestor', monster_label:'the converging ancestors',
    good:{ text:'Hold them and call for help when you need it. Tests are better passed alive.',
           alignment:+7, item:'mission_token',
           line:'"You called for help. The help came. The pattern was interrupted. Zomb notes that requesting assistance is a survival strategy, not a failure mode. Noted."' },
    evil:{ text:'Hold all five alone. Show Zomb what you are.',
           alignment:-12, item:'tainted_essence',
           line:'"All five fell. Alone. Zomb watches from the shadows of the shrine. The test result is logged. You are stronger than the average. Zomb expected this."' },
  },

  { id:'sa_z_s02', type:'survival', source:'zomb', age_min:0, cost:60, kill_count:4,
    offer:'"Bone Forest perimeter. Four dire wolves approach the settlement from separate vectors simultaneously. Zomb has been watching this pack organize. This level of organization is unusual. Respond to it."',
    room:'bone_forest', monster:'dire_wolf', monster_label:'the coordinated wolf pack',
    good:{ text:'Defend the perimeter but pull the line back to protect the most people.',
           alignment:+9, item:'tribal_blessing',
           line:'"The settlement held. Zomb notes the tactical retreat. Efficiency over pride. The pack scattered. The pack will reorganize. Zomb is watching that too."' },
    evil:{ text:'Hold every inch. Show the pack what defense looks like.',
           alignment:-10, item:'blood_token',
           line:'"Every inch held. Cost was high. Zomb calculates that a tactical retreat would have achieved the same result with lower losses. Zomb does not tell you this. You are reading this line anyway."' },
  },

  { id:'sa_z_s03', type:'survival', source:'zomb', age_min:0, cost:50, kill_count:3,
    offer:'"Underground River. The water rises — flash flood in the caves. Three cave bears are being driven toward the surface crossing. They will reach the tribe before the water does. Intercept."',
    room:'underground_river', monster:'cave_bear', monster_label:'the flood-driven cave bears',
    good:{ text:'Redirect the bears upstream away from the tribe crossing.',
           alignment:+8, item:'ancient_remedy',
           line:'"Bears redirected. Tribe crossed. Flood passed. Zomb observes that redirection is sometimes more effective than elimination. This is not Zomb\'s default position. It was correct here."' },
    evil:{ text:'Kill the bears before they reach the crossing.',
           alignment:-9, item:'blood_token',
           line:'"Bears killed at the crossing. Tribe crossed. Flood passed. Effective. The bear carcasses are already attracting other predators. Zomb notes this as a subsequent problem."' },
  },

  // ── ZOMB COOPERATIVE (2) ─────────────────────────────────────────────────

  { id:'sa_z_co01', type:'cooperative', source:'zomb', age_min:0, cost:70, kill_count:1,
    offer:'"Crystal Cavern. The ancient mammoth. Zomb has been waiting for enough entities of sufficient quality to address it. You are not individually sufficient. Collectively you may be. Attempt it."',
    room:'crystal_cavern', monster:'woolly_mammoth', monster_label:'the ancient mammoth of the cavern',
    good:{ text:'Bring everyone in and split the rewards equally regardless of contribution.',
           alignment:+12, item:'tribal_blessing',
           line:'"Equal shares. The herd contributed at different rates. Equal shares regardless. Zomb finds this inefficient and observes that cooperative entities survive longer. Contradiction noted."' },
    evil:{ text:'Lead the hunt, claim the best rewards, distribute scraps.',
           alignment:-14, item:'blood_token',
           line:'"The mammoth fell. The distribution was hierarchical. The cooperation will not repeat at that quality. Zomb notes the trade-off. The trade-off was poor."' },
  },

  { id:'sa_z_co02', type:'cooperative', source:'zomb', age_min:0, cost:65, kill_count:3,
    offer:'"Ash Fields. A blood tide — simultaneous cave bear attacks from three directions. This pattern has not occurred before. Zomb believes it will occur more. You will need help. Get help."',
    room:'ash_fields', monster:'cave_bear', monster_label:'the simultaneous bear assault',
    good:{ text:'Coordinate the defense. Keep everyone informed of each threat.',
           alignment:+11, item:'mission_token',
           line:'"Three threats addressed. Coordination was effective. Zomb observes: shared information produces better outcomes than hoarded information. Zomb is updating. Slowly."' },
    evil:{ text:'Lead from the front and let others fill the gaps without coordination.',
           alignment:-11, item:'tainted_essence',
           line:'"The assault was repelled. With higher losses than necessary. Zomb notes that uncoordinated groups fight at sixty percent efficiency. You are now aware of this statistic."' },
  },

  // ── ZOMB SABOTAGE (2) ────────────────────────────────────────────────────

  { id:'sa_z_sa01', type:'sabotage', source:'zomb', age_min:0, cost:55,
    offer:'"Ancient Shrine. The offerings left there sustain a ritual that protects the surrounding tribes. Protection prevents culling. Culling produces strength. Destroy the offerings. Let the ritual lapse."',
    room:'ancient_shrine', monster:'cave_ancestor', monster_label:'the shrine guardian',
    good:{ text:'Protect the shrine instead. The ritual protects the young and the old.',
           alignment:+15, item:'spirit_ash',
           line:'"The shrine stands. The ritual continues. Zomb\'s culling schedule is disrupted. Zomb reassigns you to a different calculation entirely."' },
    evil:{ text:'Destroy the offerings. Let the protection lapse.',
           alignment:-19, item:'tainted_essence',
           line:'"The ritual lapses. The protection ends. Zomb predicts increased mortality over the next three moons. The prediction is not a goal. It is a measurement."' },
  },

  { id:'sa_z_sa02', type:'sabotage', source:'zomb', age_min:0, cost:60,
    offer:'"Frozen Caves. An ice formation that the frost wolf packs use as a meeting point for organizing hunts. An organized wolf pack poses coordination risk. Remove the formation. Disorganize the pack."',
    room:'frozen_caves', monster:'frost_wolf', monster_label:'the pack formation wolf',
    good:{ text:'Leave the formation. Wolf coordination is not inherently a threat.',
           alignment:+7, item:'hunters_mark',
           line:'"The formation stands. The pack coordinates. They have not attacked the settlement. Zomb updates threat assessment: organized wolves — lower threat than predicted. Data is corrected."' },
    evil:{ text:'Remove the formation. Disorganize the pack.',
           alignment:-11, item:'blood_token',
           line:'"Formation removed. Pack scatter observed over seven days. The wolves are now unpredictable. Unpredictability is a different threat vector. Zomb recalculates."' },
  },

  // ── ZOMB INVESTIGATION (1) ────────────────────────────────────────────────

  { id:'sa_z_i01', type:'investigation', source:'zomb', age_min:0, cost:40,
    offer:'"Rocky Ridge. Flood markers — scoring in the rock at specific heights. Someone carved them before the last flood. Zomb needs to know how high they go. Investigate the ridge. Report exactly what you find."',
    room:'rocky_ridge', monster:'cave_bear', monster_label:'the ridge guardian',
    good:{ text:'Document every marker accurately and share the findings with everyone.',
           alignment:+13, item:'spirit_ash',
           line:'"Accurate report. Shared. The flood markers indicate the water reached higher than current settlement elevation. The tribe moves to higher ground. Zomb approves of the sharing. Reluctantly."' },
    evil:{ text:'Document the markers and keep the information for personal advantage.',
           alignment:-16, item:'blood_token',
           line:'"The markers are documented. In your records only. The settlement remains at flood elevation. Zomb notes the information asymmetry. It is a weapon you have chosen to carry."' },
  },
];
