'use strict';

const AGES = [
  {
    id           : 0,
    name         : 'Stone Age',
    xp_threshold : 5000,
    tagline      : 'Fire was invented last Tuesday. Congrats.',
  },
  {
    id           : 1,
    name         : 'Bronze Age',
    xp_threshold : 25000,
    tagline      : 'Shiny rocks. Sharp shiny rocks.',
  },
  {
    id           : 2,
    name         : 'Iron Age',
    xp_threshold : 75000,
    tagline      : 'Progress hurts. So do swords.',
  },
  {
    id           : 3,
    name         : 'Medieval',
    xp_threshold : 200000,
    tagline      : 'Plague, knights, and dragons. The full package.',
  },
];

const MONSTER_TEMPLATES = {
  // ── Stone Age ──────────────────────────────────────────────────────────────
  cave_rat: {
    id          : 'cave_rat',
    name        : 'Cave Rat',
    age         : 0,
    description : 'A mangy rat the size of a small dog. Teeth like jagged flint.',
    hp          : 8,
    str         : 2,
    dex         : 4,
    xp          : 5,
    gold_min    : 2,
    gold_max    : 8,
    loot        : [{ id: 'rat_pelt', chance: 0.35 }],
    respawn_min : 3,
    aggro       : false,
  },
  dire_wolf: {
    id          : 'dire_wolf',
    name        : 'Dire Wolf',
    age         : 0,
    description : 'A wolf the size of a horse. It is not friendly.',
    hp          : 22,
    str         : 6,
    dex         : 5,
    xp          : 18,
    gold_min    : 8,
    gold_max    : 22,
    loot        : [{ id: 'wolf_pelt', chance: 0.5 }, { id: 'wolf_fang', chance: 0.3 }],
    respawn_min : 8,
    aggro       : true,
  },
  cave_bear: {
    id          : 'cave_bear',
    name        : 'Cave Bear',
    age         : 0,
    description : 'An enormous bear with claws like bone daggers. Absolutely furious.',
    hp          : 48,
    str         : 10,
    dex         : 3,
    xp          : 42,
    gold_min    : 22,
    gold_max    : 55,
    loot        : [{ id: 'bear_pelt', chance: 0.65 }, { id: 'bone_club', chance: 0.22 }],
    respawn_min : 20,
    aggro       : true,
  },
  woolly_mammoth: {
    id          : 'woolly_mammoth',
    name        : 'Woolly Mammoth',
    age         : 0,
    description : 'The ground shakes with each step. A living mountain of fur and tusks.',
    hp          : 160,
    str         : 18,
    dex         : 2,
    xp          : 220,
    gold_min    : 90,
    gold_max    : 200,
    loot        : [{ id: 'mammoth_hide', chance: 0.9 }, { id: 'mammoth_tusk', chance: 0.6 }, { id: 'flood_blade', chance: 0.015 }],
    respawn_min : 60,
    aggro       : false,
    is_boss     : true,
  },

  // ── Bronze Age ─────────────────────────────────────────────────────────────
  war_boar: {
    id          : 'war_boar',
    name        : 'War Boar',
    age         : 1,
    description : 'A massive boar with bronze-capped tusks. Someone trained this thing to kill.',
    hp          : 38,
    str         : 9,
    dex         : 6,
    xp          : 32,
    gold_min    : 18,
    gold_max    : 38,
    loot        : [{ id: 'boar_tusk', chance: 0.5 }, { id: 'dried_meat', chance: 0.4 }],
    respawn_min : 10,
    aggro       : true,
  },
  tribal_warrior: {
    id          : 'tribal_warrior',
    name        : 'Tribal Warrior',
    age         : 1,
    description : 'A painted warrior with a bronze spear and absolutely zero interest in diplomacy.',
    hp          : 48,
    str         : 12,
    dex         : 8,
    xp          : 52,
    gold_min    : 35,
    gold_max    : 70,
    loot        : [{ id: 'bronze_shard', chance: 0.45 }, { id: 'iron_spear', chance: 0.12 }],
    respawn_min : 12,
    aggro       : true,
  },
  bronze_golem: {
    id          : 'bronze_golem',
    name        : 'Bronze Golem',
    age         : 1,
    description : 'A lumbering construct of ancient bronze, bound together by forgotten sorcery. Slow. Very angry.',
    hp          : 90,
    str         : 16,
    dex         : 2,
    xp          : 100,
    gold_min    : 70,
    gold_max    : 120,
    loot        : [{ id: 'bronze_shard', chance: 0.8 }, { id: 'bronze_sword', chance: 0.15 }],
    respawn_min : 25,
    aggro       : false,
  },
  ancient_guardian: {
    id          : 'ancient_guardian',
    name        : 'Ancient Guardian',
    age         : 1,
    description : 'A colossal armoured figure that has stood at this threshold since the world began. It has been waiting for something worth killing.',
    hp          : 240,
    str         : 24,
    dex         : 6,
    xp          : 350,
    gold_min    : 175,
    gold_max    : 350,
    loot        : [{ id: 'ancient_relic', chance: 0.95 }, { id: 'bronze_sword', chance: 0.5 }, { id: 'flood_blade', chance: 0.02 }, { id: 'before_time_armor', chance: 0.02 }],
    respawn_min : 90,
    aggro       : false,
    is_boss     : true,
  },

  // ── Iron Age ───────────────────────────────────────────────────────────────
  iron_wolf: {
    id          : 'iron_wolf',
    name        : 'Iron Wolf',
    age         : 2,
    description : 'A war-trained wolf fitted with iron plates along its spine. Fast, disciplined, and furious.',
    hp          : 65,
    str         : 12,
    dex         : 10,
    xp          : 65,
    gold_min    : 35,
    gold_max    : 75,
    loot        : [{ id: 'wolf_pelt', chance: 0.5 }, { id: 'iron_ingot', chance: 0.2 }],
    respawn_min : 12,
    aggro       : true,
  },
  iron_warrior: {
    id          : 'iron_warrior',
    name        : 'Iron Warrior',
    age         : 2,
    description : 'A seasoned soldier in battered iron armour. The dents are trophies, not damage.',
    hp          : 95,
    str         : 18,
    dex         : 7,
    xp          : 105,
    gold_min    : 55,
    gold_max    : 100,
    loot        : [{ id: 'iron_ingot', chance: 0.45 }, { id: 'iron_sword', chance: 0.1 }],
    respawn_min : 15,
    aggro       : true,
  },
  iron_knight: {
    id          : 'iron_knight',
    name        : 'Iron Knight',
    age         : 2,
    description : 'A fortress of iron plate striding towards you at speed. Each footstep shakes the ground.',
    hp          : 140,
    str         : 24,
    dex         : 5,
    xp          : 170,
    gold_min    : 100,
    gold_max    : 180,
    loot        : [{ id: 'iron_ingot', chance: 0.7 }, { id: 'war_hammer', chance: 0.12 }, { id: 'runed_stone', chance: 0.25 }],
    respawn_min : 30,
    aggro       : false,
  },
  iron_colossus: {
    id          : 'iron_colossus',
    name        : 'Iron Colossus',
    age         : 2,
    description : 'A monument to iron-age hubris — a golem the size of a house, forged in volcanic heat, cooled in blood. The volcano built it. Now it\'s very much your problem.',
    hp          : 380,
    str         : 32,
    dex         : 3,
    xp          : 550,
    gold_min    : 300,
    gold_max    : 550,
    loot        : [{ id: 'runed_stone', chance: 0.95 }, { id: 'war_hammer', chance: 0.45 }, { id: 'iron_armor', chance: 0.3 }, { id: 'before_time_armor', chance: 0.025 }],
    respawn_min : 120,
    aggro       : false,
    is_boss     : true,
  },

  // ── Stone Age extras ──────────────────────────────────────────────────────
  cave_ancestor: {
    id          : 'cave_ancestor',
    name        : 'Cave Ancestor',
    age         : 0,
    description : 'An ancient being of stone and sinew that predates any name for it. It has been in this shrine since before your species had fire.',
    hp          : 75,
    str         : 12,
    dex         : 7,
    xp          : 75,
    gold_min    : 40,
    gold_max    : 80,
    loot        : [{ id: 'bear_pelt', chance: 0.6 }, { id: 'wolf_fang', chance: 0.4 }, { id: 'stone_axe', chance: 0.15 }],
    respawn_min : 30,
    aggro       : true,
  },
  frost_wolf: {
    id          : 'frost_wolf',
    name        : 'Frost Wolf',
    age         : 0,
    description : 'A dire wolf adapted to the frozen caves — white-furred, silent, and deeply territorial about ice.',
    hp          : 38,
    str         : 8,
    dex         : 9,
    xp          : 36,
    gold_min    : 15,
    gold_max    : 35,
    loot        : [{ id: 'wolf_pelt', chance: 0.65 }, { id: 'wolf_fang', chance: 0.4 }],
    respawn_min : 10,
    aggro       : true,
  },

  // ── Bronze Age extras ──────────────────────────────────────────────────────
  tribal_high_priest: {
    id          : 'tribal_high_priest',
    name        : 'Tribal High Priest',
    age         : 1,
    description : 'Covered head to toe in ritual markings. The staff in their hand has ended more lives than the warriors who guard them.',
    hp          : 110,
    str         : 17,
    dex         : 10,
    xp          : 130,
    gold_min    : 75,
    gold_max    : 130,
    loot        : [{ id: 'bronze_shard', chance: 0.65 }, { id: 'ancient_relic', chance: 0.3 }, { id: 'iron_spear', chance: 0.08 }],
    respawn_min : 25,
    aggro       : true,
  },

  // ── Iron Age extras ────────────────────────────────────────────────────────
  iron_sentinel: {
    id          : 'iron_sentinel',
    name        : 'Iron Sentinel',
    age         : 2,
    description : 'A watchman encased entirely in iron plate who has not left their post in forty years. The post is now wherever you are standing.',
    hp          : 165,
    str         : 26,
    dex         : 4,
    xp          : 195,
    gold_min    : 120,
    gold_max    : 200,
    loot        : [{ id: 'iron_ingot', chance: 0.7 }, { id: 'runed_stone', chance: 0.3 }, { id: 'war_hammer', chance: 0.12 }],
    respawn_min : 35,
    aggro       : false,
  },

  // ── Medieval extras ────────────────────────────────────────────────────────
  royal_lich: {
    id          : 'royal_lich',
    name        : 'Royal Lich',
    age         : 3,
    description : 'The animated remains of a king who refused death so utterly that death eventually gave him the deed to the catacombs and left.',
    hp          : 185,
    str         : 24,
    dex         : 14,
    xp          : 300,
    gold_min    : 160,
    gold_max    : 280,
    loot        : [{ id: 'elder_rune', chance: 0.7 }, { id: 'dark_crystal', chance: 0.5 }, { id: 'steel_sword', chance: 0.08 }],
    respawn_min : 45,
    aggro       : true,
  },

  // ── Secret / Explore-only monsters ────────────────────────────────────────
  cave_ghoul: {
    id          : 'cave_ghoul',
    name        : 'Cave Ghoul',
    age         : 0,
    description : 'Something that used to be human and decided it preferred the dark. Pale, fast, very upset about being disturbed.',
    hp          : 55,
    str         : 9,
    dex         : 6,
    xp          : 52,
    gold_min    : 28,
    gold_max    : 65,
    loot        : [{ id: 'rat_pelt', chance: 0.4 }, { id: 'bone_club', chance: 0.2 }],
    respawn_min : 999,
    aggro       : true,
    no_respawn  : true,
  },
  bronze_shade: {
    id          : 'bronze_shade',
    name        : 'Bronze Shade',
    age         : 1,
    description : 'The echo of a Bronze Age warrior that refuses to accept the age has ended. Semi-transparent, fully angry.',
    hp          : 100,
    str         : 16,
    dex         : 9,
    xp          : 108,
    gold_min    : 65,
    gold_max    : 115,
    loot        : [{ id: 'bronze_shard', chance: 0.6 }, { id: 'boar_tusk', chance: 0.3 }],
    respawn_min : 999,
    aggro       : true,
    no_respawn  : true,
  },
  iron_revenant: {
    id          : 'iron_revenant',
    name        : 'Iron Revenant',
    age         : 2,
    description : 'A fallen Iron Age knight reanimated by pure grudge. The armour is rusted but the hatred is freshly maintained.',
    hp          : 130,
    str         : 22,
    dex         : 10,
    xp          : 158,
    gold_min    : 95,
    gold_max    : 155,
    loot        : [{ id: 'iron_ingot', chance: 0.55 }, { id: 'runed_stone', chance: 0.25 }],
    respawn_min : 999,
    aggro       : true,
    no_respawn  : true,
  },
  shadow_stalker: {
    id          : 'shadow_stalker',
    name        : 'Shadow Stalker',
    age         : 3,
    description : 'A thing woven from the shadow between shadows. It follows very quietly and is surprised when people notice it.',
    hp          : 145,
    str         : 26,
    dex         : 16,
    xp          : 208,
    gold_min    : 138,
    gold_max    : 228,
    loot        : [{ id: 'dark_crystal', chance: 0.55 }, { id: 'elder_rune', chance: 0.2 }],
    respawn_min : 999,
    aggro       : true,
    no_respawn  : true,
  },

  // ── Medieval ───────────────────────────────────────────────────────────────
  dark_knight: {
    id          : 'dark_knight',
    name        : 'Dark Knight',
    age         : 3,
    description : 'A knight who traded their soul for power and got a fair price. The armour is black, the eyes are worse.',
    hp          : 115,
    str         : 20,
    dex         : 10,
    xp          : 155,
    gold_min    : 90,
    gold_max    : 160,
    loot        : [{ id: 'dark_crystal', chance: 0.4 }, { id: 'steel_sword', chance: 0.1 }],
    respawn_min : 18,
    aggro       : true,
  },
  wraith: {
    id          : 'wraith',
    name        : 'Wraith',
    age         : 3,
    description : 'What\'s left when grief outlasts the body. Barely visible, terrifyingly fast, and deeply resentful of the living.',
    hp          : 80,
    str         : 15,
    dex         : 16,
    xp          : 135,
    gold_min    : 70,
    gold_max    : 130,
    loot        : [{ id: 'dark_crystal', chance: 0.6 }, { id: 'elder_rune', chance: 0.15 }],
    respawn_min : 14,
    aggro       : true,
  },
  tournament_champion: {
    id          : 'tournament_champion',
    name        : 'Tournament Champion',
    age         : 3,
    description : 'Ten years undefeated. Six feet of bored, professional violence looking for a worthy opponent. They will not find one in you, but they\'ll try anyway.',
    hp          : 175,
    str         : 28,
    dex         : 8,
    xp          : 245,
    gold_min    : 150,
    gold_max    : 250,
    loot        : [{ id: 'dark_crystal', chance: 0.35 }, { id: 'battle_axe', chance: 0.14 }, { id: 'plate_armor', chance: 0.08 }],
    respawn_min : 35,
    aggro       : false,
  },
  lich_lord: {
    id          : 'lich_lord',
    name        : 'Lich Lord',
    age         : 3,
    description : 'A sorcerer who refused death so persistently that death eventually became embarrassed and left. He\'s been insufferable ever since.',
    hp          : 155,
    str         : 22,
    dex         : 12,
    xp          : 275,
    gold_min    : 140,
    gold_max    : 260,
    loot        : [{ id: 'elder_rune', chance: 0.75 }, { id: 'dark_crystal', chance: 0.5 }, { id: 'enchanted_cloak', chance: 0.1 }],
    respawn_min : 40,
    aggro       : true,
  },
  elder_dragon: {
    id          : 'elder_dragon',
    name        : 'Elder Dragon',
    age         : 3,
    description : 'Older than the world\'s current name. The scorch marks on every surface within a hundred metres suggest it has been here a while. The piles of gold confirm it is not planning to leave.',
    hp          : 580,
    str         : 42,
    dex         : 8,
    xp          : 1150,
    gold_min    : 700,
    gold_max    : 1200,
    loot        : [{ id: 'dragon_scale', chance: 0.95 }, { id: 'elder_rune', chance: 0.8 }, { id: 'battle_axe', chance: 0.5 }, { id: 'flood_blade', chance: 0.04 }, { id: 'before_time_armor', chance: 0.04 }],
    respawn_min : 180,
    aggro       : false,
    is_boss     : true,
  },
};

const ITEM_TEMPLATES = {
  // ── Stone Age weapons ──────────────────────────────────────────────────────
  fists: {
    id: 'fists', name: 'Fists', type: 'weapon', slot: 'weapon',
    damage_min: 1, damage_max: 3, value: 0, age: 0,
  },
  flint_knife: {
    id: 'flint_knife', name: 'Flint Knife', type: 'weapon', slot: 'weapon',
    damage_min: 2, damage_max: 6, value: 30, age: 0,
    description: 'Sharp enough to hurt, small enough to lose.',
  },
  bone_club: {
    id: 'bone_club', name: 'Bone Club', type: 'weapon', slot: 'weapon',
    damage_min: 4, damage_max: 9, value: 80, age: 0,
    description: 'A femur repurposed as a blunt instrument.',
  },
  stone_axe: {
    id: 'stone_axe', name: 'Stone Axe', type: 'weapon', slot: 'weapon',
    damage_min: 5, damage_max: 11, value: 160, age: 0,
    description: 'Lashed flint on a branch. Surprisingly effective.',
  },
  sharpened_stick: {
    id: 'sharpened_stick', name: 'Sharpened Stick', type: 'weapon', slot: 'weapon',
    damage_min: 2, damage_max: 4, value: 10, age: 0,
    description: 'You sharpened a stick. A start.',
  },
  // Stone Age armor
  hide_tunic: {
    id: 'hide_tunic', name: 'Hide Tunic', type: 'armor', slot: 'body',
    defense: 2, value: 40, age: 0,
    description: 'Animal hide stitched together.',
  },
  bone_bracers: {
    id: 'bone_bracers', name: 'Bone Bracers', type: 'armor', slot: 'arms',
    defense: 3, value: 90, age: 0,
    description: 'Forearm guards made from large bones.',
  },
  mammoth_hide: {
    id: 'mammoth_hide', name: 'Mammoth Hide Armor', type: 'armor', slot: 'body',
    defense: 8, value: 400, age: 0,
    description: 'Heavy but legendary. Smells incredible (bad).',
  },
  // Stone Age consumables
  dried_meat: {
    id: 'dried_meat', name: 'Dried Meat', type: 'consumable',
    heal: 15, value: 20, age: 0,
    description: 'Chewy, questionable, life-saving.',
  },
  healing_herb: {
    id: 'healing_herb', name: 'Healing Herb', type: 'consumable',
    heal: 30, value: 50, age: 0,
    description: 'Bitter leaf with miraculous healing properties.',
  },
  // Stone Age materials
  rat_pelt    : { id: 'rat_pelt',     name: 'Rat Pelt',      type: 'material', value: 5,  age: 0 },
  wolf_pelt   : { id: 'wolf_pelt',    name: 'Wolf Pelt',     type: 'material', value: 15, age: 0 },
  wolf_fang   : { id: 'wolf_fang',    name: 'Wolf Fang',     type: 'material', value: 10, age: 0 },
  bear_pelt   : { id: 'bear_pelt',    name: 'Bear Pelt',     type: 'material', value: 30, age: 0 },
  mammoth_tusk: { id: 'mammoth_tusk', name: 'Mammoth Tusk',  type: 'material', value: 80, age: 0 },

  // ── Bronze Age weapons ─────────────────────────────────────────────────────
  bronze_sword: {
    id: 'bronze_sword', name: 'Bronze Sword', type: 'weapon', slot: 'weapon',
    damage_min: 7, damage_max: 15, value: 300, age: 1,
    description: 'Cast bronze, double-edged. A genuine upgrade over sharpened rock.',
  },
  iron_spear: {
    id: 'iron_spear', name: 'Iron-Tipped Spear', type: 'weapon', slot: 'weapon',
    damage_min: 9, damage_max: 18, value: 380, age: 1,
    description: 'Long reach, devastating thrust. Keep your distance and use it.',
  },
  // Bronze Age armor
  leather_armor: {
    id: 'leather_armor', name: 'Leather Armor', type: 'armor', slot: 'body',
    defense: 5, value: 200, age: 1,
    description: 'Cured leather plates. Actual protection, not just modesty.',
  },
  bronze_shield: {
    id: 'bronze_shield', name: 'Bronze Shield', type: 'armor', slot: 'arms',
    defense: 6, value: 250, age: 1,
    description: 'A round bronze buckler. Blocks hits, makes a satisfying clang.',
  },
  // Bronze Age consumable
  cave_mushroom: {
    id: 'cave_mushroom', name: 'Cave Mushroom', type: 'consumable',
    heal: 45, value: 60, age: 1,
    description: 'Glows faintly. Tastes terrible. Works brilliantly.',
  },
  // Bronze Age materials
  boar_tusk    : { id: 'boar_tusk',     name: 'Boar Tusk',      type: 'material', value: 20, age: 1 },
  bronze_shard : { id: 'bronze_shard',  name: 'Bronze Shard',   type: 'material', value: 25, age: 1 },
  ancient_relic: { id: 'ancient_relic', name: 'Ancient Relic',  type: 'material', value: 200, age: 1 },

  // ── Iron Age weapons ───────────────────────────────────────────────────────
  iron_sword: {
    id: 'iron_sword', name: 'Iron Sword', type: 'weapon', slot: 'weapon',
    damage_min: 10, damage_max: 20, value: 450, age: 2,
    description: 'Forged iron, properly balanced. A serious weapon for serious people.',
  },
  war_hammer: {
    id: 'war_hammer', name: 'War Hammer', type: 'weapon', slot: 'weapon',
    damage_min: 13, damage_max: 25, value: 550, age: 2,
    description: 'Heavy, slow, and absolutely devastating. Armour means nothing to this.',
  },
  // Iron Age armor
  iron_armor: {
    id: 'iron_armor', name: 'Iron Armor', type: 'armor', slot: 'body',
    defense: 12, value: 450, age: 2,
    description: 'Full iron plate. Heavy as regret, protective as a mother.',
  },
  iron_helm: {
    id: 'iron_helm', name: 'Iron Helm', type: 'armor', slot: 'head',
    defense: 6, value: 220, age: 2,
    description: 'Iron dome for your skull. Dents beautifully.',
  },
  // Iron Age consumable
  health_potion: {
    id: 'health_potion', name: 'Health Potion', type: 'consumable',
    heal: 80, value: 80, age: 2,
    description: 'Red, thick, alarmingly effective. Don\'t ask what\'s in it.',
  },
  // Iron Age materials
  iron_ingot  : { id: 'iron_ingot',   name: 'Iron Ingot',   type: 'material', value: 40,  age: 2 },
  runed_stone : { id: 'runed_stone',  name: 'Runed Stone',  type: 'material', value: 120, age: 2 },

  // ── Medieval weapons ───────────────────────────────────────────────────────
  steel_sword: {
    id: 'steel_sword', name: 'Steel Sword', type: 'weapon', slot: 'weapon',
    damage_min: 15, damage_max: 28, value: 700, age: 3,
    description: 'Tempered steel with a master\'s edge. The finest blade short of magic.',
  },
  battle_axe: {
    id: 'battle_axe', name: 'Battle Axe', type: 'weapon', slot: 'weapon',
    damage_min: 17, damage_max: 32, value: 850, age: 3,
    description: 'Double-headed, horribly heavy, and absolutely magnificent.',
  },
  // Medieval armor
  plate_armor: {
    id: 'plate_armor', name: 'Plate Armor', type: 'armor', slot: 'body',
    defense: 18, value: 800, age: 3,
    description: 'Full articulated plate. You\'re basically a walking fortress now.',
  },
  enchanted_cloak: {
    id: 'enchanted_cloak', name: 'Enchanted Cloak', type: 'armor', slot: 'body',
    defense: 10, value: 600, age: 3,
    description: 'A cloak woven from shadow and spite. Lighter than iron, smarter than wood.',
  },
  // Medieval consumable
  dragon_brew: {
    id: 'dragon_brew', name: 'Dragon Brew', type: 'consumable',
    heal: 200, value: 150, age: 3,
    description: 'Distilled from dragon blood by someone with absolutely no survival instinct.',
  },
  // Medieval materials
  dark_crystal: { id: 'dark_crystal', name: 'Dark Crystal',  type: 'material', value: 180, age: 3 },
  dragon_scale : { id: 'dragon_scale', name: 'Dragon Scale',  type: 'material', value: 600, age: 3 },
  elder_rune   : { id: 'elder_rune',   name: 'Elder Rune',    type: 'material', value: 900, age: 3 },

  // ── Death's weapons (owner-locked to username 'death') ────────────────────
  stone_scythe: {
    id: 'stone_scythe', name: 'Stone Scythe', type: 'weapon', slot: 'weapon',
    damage_min: 7, damage_max: 13, value: 0, age: 0,
    owner: 'death', cannot_drop: true,
    description: 'A scythe carved from obsidian. Predates the concept of farming.',
  },
  bronze_scythe: {
    id: 'bronze_scythe', name: 'Bronze Scythe', type: 'weapon', slot: 'weapon',
    damage_min: 12, damage_max: 22, value: 0, age: 1,
    owner: 'death', cannot_drop: true,
    description: 'Cast bronze, curved for a single purpose. The handle is worn smooth by ten thousand harvests.',
  },
  iron_scythe: {
    id: 'iron_scythe', name: 'Iron Scythe', type: 'weapon', slot: 'weapon',
    damage_min: 18, damage_max: 32, value: 0, age: 2,
    owner: 'death', cannot_drop: true,
    description: 'Forged iron, given a blade that curves like a last breath.',
  },
  reapers_scythe: {
    id: 'reapers_scythe', name: "The Reaper's Scythe", type: 'weapon', slot: 'weapon',
    damage_min: 30, damage_max: 55, value: 0, age: 3,
    owner: 'death', cannot_drop: true,
    description: 'The original. The one that started the whole business. It hums when it swings.',
  },
  void_pet: {
    id: 'void_pet', name: 'The Void', type: 'pet', slot: null,
    value: 0, age: 0,
    owner: 'death', cannot_drop: true,
    description: 'The Void itself, condensed into something that follows you around and occasionally heals you.',
  },

  // ── Flood Relics (pre-dates all ages — founder-only equippable) ─────────────
  flood_blade: {
    id: 'flood_blade', name: 'The Flood Blade', type: 'weapon', slot: 'weapon',
    damage_min: 25, damage_max: 45, value: 0, age: 0,
    founder_only: true,
    cannot_drop : true,
    description: 'Forged before the first flood. It remembers every world. Non-founders feel it resist their grip.',
  },
  before_time_armor: {
    id: 'before_time_armor', name: 'Armour of the Before-Time', type: 'armor', slot: 'body',
    defense: 25, value: 0, age: 0,
    founder_only: true,
    cannot_drop : true,
    description: 'Hammered from the bones of the old world. Pre-dates the current age. Non-founders cannot wear it.',
  },
  flood_wraith: {
    id: 'flood_wraith', name: 'Flood Wraith', type: 'pet', slot: null,
    value: 0, age: 0,
    cannot_drop : true,
    description: 'The ghost of your old Stone Age companion, following you through the reset. Loyal beyond death.',
  },
};

module.exports = { AGES, MONSTER_TEMPLATES, ITEM_TEMPLATES };
